argoproj/argo-helm

- charts/argo/values.yaml
I've found that helm has issues with conditional sub charts of a sub chart so I think it'd be better to have minio not be installed as part of the chart by default so if you want to leverage this chart as part of another chart you don't have to worry about unintended resources getting created on cluster.
> set minio to not be installed by default

- charts/argo/Chart.yaml
- charts/argo/README.md
- charts/argo/templates/apply-workflow-crd-job.yaml
- charts/argo/templates/ui-deployment.yaml
- charts/argo/templates/ui-service.yaml
- charts/argo/templates/worfkflow-controller-secrets-access.yaml
- charts/argo/templates/workflow-controller-config-map.yaml
- charts/argo/templates/workflow-controller-deployment.yaml
- charts/argo/templates/workflow-controller-minio-secret-crb.yaml
- charts/argo/values.yaml
- Changed the default `workflow-controller` installation to use the `ServiceAccount` that is created and bound.
- Customized the instanceID logic:
- No longer defaults to installed (this was very difficult to see/understand when coming from starter tutorials)
- Kept logic to allow for release name or explicit mappings but changed structure a bit
- Added in optional configuration for:
- CRD Install hook's ServiceAccount to allow clean install if your
default roles aren't privledged
- Optional Pod and Service annotations
- Controller logging level configuration
- Minio Customizations
- Changed the Secret configuration to properly represent the path of a secret instead of the actual contents
- Changed the names of the secret and service that are represented to mirror that of the underlying …
> Chart Grooming

- charts/argo/templates/ui-crb.yaml
This was binding roles to the service account in the `.Release.Name` instead of `.Release.Namespace` namespace
> Fix typo in ui-crb.yaml

- charts/argo/templates/NOTES.txt
So that commands work for non-default namespaces.
> Print namespace in notes.

- charts/argo-events/templates/argo-events-cluster-roles.yaml
- charts/argo-events/templates/argo-events-sa.yaml
I found argo-events chart doesn't set namespace on service account and clusterrole correctly.
> Set namespace on service accounts and clusterrole

- charts/argo-events/templates/gateway-controller-configmap.yaml
- charts/argo-events/templates/sensor-controller-configmap.yaml
- charts/argo-events/values.yaml
it's helpful to be able to control whether or not the controllers listen on all namespaces when we install them.
this adds a configurable option `singleNamespace` which is a boolean, and controls that behaviour
> add a toggle to allow the controllers to listen on all namespaces

- charts/argo-events/Chart.yaml
- charts/argo-events/values.yaml
I think a container image should use a fixed tag instead of latest tag.
https://helm.sh/docs/chart_best_practices/#images
> Set specific version to argo-events images

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-redis-deployment.yaml
- charts/argo-cd/templates/argocd-redis-service.yaml
- charts/argo-cd/values.yaml
This is to fix https://github.com/argoproj/argo-helm/issues/45
Added a deployment for redis based on https://raw.githubusercontent.com/argoproj/argo-cd/v0.12.0/manifests/install.yaml
Updated all container image tags to 0.12.0.
Bumped appVersion and chart version.
I've tested this on my cluster and it works fine.
> Support argocd 0.12.0

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server-deployment.yaml
- charts/argo-cd/values.yaml
Allowing extra arguments to be specified for argocd-server.
This is useful, for instance, if you need to change the basehref or use insecure when using ingress
https://github.com/argoproj/argo-cd/blob/master/docs/ingress.md
> Allow extraargs for argocd server

- charts/argo-cd/templates/argocd-server-service.yaml
- charts/argo-cd/values.yaml
Added annotations to `argo-cd-server-service.yaml`.
it's useful for backend configuration.
```
apiVersion: v1
kind: Service
metadata:
name: argocd-server
labels:
app.kubernetes.io/name: {{ include "argo-cd.name" . }}-server
helm.sh/chart: {{ include "argo-cd.chart" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
app.kubernetes.io/part-of: {{ include "argo-cd.name" . }}
app.kubernetes.io/component: server
annotations:
{{ toYaml .Values.server.serviceAnnotations | indent 4}}{{- end }}
```
> Adding Service Annotation to argo-cd helm chart

- charts/argo/templates/workflow-crd.yaml
Without this change, you end up with the following error on rolling upgrades:
```
Error: customresourcedefinitions.apiextensions.k8s.io "workflows.argoproj.io" already exists
ERROR: Job failed: exit code 1
```
> workflow-crd.yaml: delete before hook creation

- charts/argo/templates/workflow-controller-config-map.yaml
- charts/argo/values.yaml
adds a configurable stanza for the workflow-controller-configmap.yaml
```
controller:
metricsConfig:
enabled: false
path: /metrics
port: 8080
```
> add metricsConfig to the argo-workflow configmap

- charts/argo-cd/templates/argocd-application-controller-deployment.yaml
- charts/argo-cd/templates/argocd-dex-server-deployment.yaml
- charts/argo-cd/templates/argocd-repo-server-deployment.yaml
- charts/argo-cd/templates/argocd-server-deployment.yaml
- charts/argo-cd/values.yaml
This adds new parameters to each Deployment in the argo-cd chart, allowing users to specify custom volumes to mount.  This makes it possible to use a Git repository self-signed certificates by manually adding a "known_hosts" file, as recommended in the documentation: https://argoproj.github.io/argo-cd/user-guide/private-repositories/
`volumes` and `volumeMounts` parameters are added to each Deployment, with defaults set to empty.
This change was tested by templating the chart with default parameters, and by templating it with volume mounts specified for each service.
> argo-cd: Add volume parameters to Deployments

- charts/argo-events/Chart.yaml
- charts/argo-events/templates/argo-events-cluster-roles.yaml
- charts/argo-events/templates/argo-events-sa.yaml
- charts/argo-events/values.yaml
When using the charts accross namespaces we need the SA and bindings to be created in all of them.  Otherwise the sensor and gateway controllers just crash or complain about RBAC errors.
> Multi-namespace RBAC support

- charts/argo/templates/workflow-controller-config-map.yaml
- charts/argo/values.yaml
Adds the option to persist workflow logs to default `artifactRepository`
> Add archiveLogs option to Argo workflow controller config map

- charts/argo-cd/templates/argocd-cm.yaml
- charts/argo-cd/values.yaml
https://argoproj.github.io/argo-cd/user-guide/application_sources/#config-management-plugins
Added `configManagementPlugins` option because it was not supported.
> Add configManagementPlugins option to argo-cd

- charts/argo-cd/templates/argocd-server-clusterrole.yaml
- charts/argo-cd/templates/argocd-server-clusterrolebinding.yaml
Adding the ClusterRole and ClusterRoleBinding allows argocd-server
to
read the necessary resources to deploy applications
to the default
cluster.
Closes #61
> fix(argocd): Adds argocd-server ClusterRole and ClusterRoleBinding

- charts/argo/Chart.yaml
- charts/argo/templates/ui-deployment.yaml
- charts/argo/values.yaml
Allow UI to watch for workflow in the namespace it is installed.
Existing release will have no change.
> Add force namespace isolation for UI

- charts/argo-ci/templates/ci-deployment.yaml
- charts/argo-ci/values.yaml
- charts/argo/templates/ui-deployment.yaml
- charts/argo/templates/workflow-controller-deployment.yaml
- charts/argo/values.yaml
This pull request will enable configuration of image pull policy in the following charts: 
- argo 
- argo-ci 
When using the argo helm chart in an environment that is closed off from the internet, it is important to allow images to be pre-loaded and leveraged.
> Enable image pull policy in argo & argo-ci

- charts/argo/templates/workflow-controller-config-map.yaml
- charts/argo/values.yaml
I'd like to configure `containerRuntimeExecutor`. Would you consider merging this change?
> Make containerRuntimeExecutor configurable

- charts/argo/templates/ui-service.yaml
- charts/argo/values.yaml
Guys I think that Argo-ui is used a lot internally in companies through VPN, therefore it would make sense to allow for setting static IP address for internal loadBalancer. WDYT ?
> loadBalancerIP support in argo-ui

- charts/argo/Chart.yaml
- charts/argo/templates/workflow-controller-config-map.yaml
- charts/argo/templates/workflow-controller-service.yaml
- charts/argo/templates/workflow-controller-servicemonitor.yaml
- charts/argo/values.yaml
This PR does several things:
- update to the latest version of Argo (v2.3.0)
- allow to enable telemetry endpoint, the same way the metrics endpoint is enabled (personal comment: i suggest to merge this two endpoints in the Argo product to simplify things)
- allow to activate Prometheus ServiceMonitor for both metrics and telemetry endpoints
- add a Service resource for both metrics and telemetry endpoints (needed for Prometheus ServiceMonitor)
I've tried to match the current way of declaring resources in the Argo chart.
> Update Argo to v2.3.0 and add support for Prometheus operator

- charts/argo-cd/values.yaml
Hey,
there is an incorrect image tag at argocd-ui.
Recognized after **helm install argo/argo-cd**
> Fixed typo at argocd-ui

- charts/argo/Chart.yaml
- charts/argo/templates/ui-deployment.yaml
- charts/argo/templates/workflow-controller-deployment.yaml
The argo helm chart does not deploy on Kubernetes 1.16 because it is still trying to deploy using the deprecated extensions/v1betax of the Deployment object.
This PR simply change it to apps/v1 and add the selector field;
```bash
helm install --name argo --namespace argo .
```
```bash
kubectl get all -n argo
NAME                                            READY   STATUS    RESTARTS   AGE
pod/argo-ui-54d674fdfd-254sl                    1/1     Running   0          3m41s
pod/argo-workflow-controller-6c5544f94d-5vl5s   1/1     Running   0          3m41s
NAME              TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
service/argo-ui   ClusterIP   10.99.128.160   <none>        80/TCP    3m41s
NAME                                       READY   UP-TO-DATE   AVAILABLE   AGE …
```
> Deployment extensions/v1beta1 is deprecated in Kubernetes 1.16

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-cm.yaml
- charts/argo-cd/values.yaml
This PR allows the user to configure anonymous access to ArgoCD using a new `enableAnonymousAccess` field in `values.yaml`. The new field defaults to `false`.
This is convenient for local or highly trusted deployments of ArgoCD.
Checklist:
> argo-cd: allow anonymous access

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/crds/application-crd.yaml
- charts/argo-cd/templates/crds/appproject-crd.yaml
The pattern is standard to support 'helm upgrade' for charts that define CRDs.
> argo-cd/crds: add 'hook-delete-policy: before-hook-creation'

- charts/argo/Chart.yaml
- charts/argo/templates/workflow-controller-deployment.yaml
Checklist:
This change just exposes the metrics port of the workflow controller pod if the metrics are enabled.
> expose workflow metrics port

- charts/argo/Chart.yaml
- charts/argo/README.md
- charts/argo/templates/ui-cluster-role.yaml
- charts/argo/templates/workflow-aggregate-roles.yaml
- charts/argo/templates/workflow-controller-clusterrole.yaml
- charts/argo/templates/workflow-template-crd.yaml
- charts/argo/values.yaml
Notable changes:
* Default argo image is 2.4.2
* WorkflowTemplate CRD is created
* RBAC is updated to include workflowtemplate permissions
* CRD install is disabled with a Helm flag in order to be more compatible with tools such as [Reckoner](https://github.com/fairwindsops/reckoner)
* README suggests where to find CRDs for manual install
I have installed this chart using the values that I had for my previous install of Argo on 2.3.0 and it installs cleanly. I tested running both standard workflows and submitting templates and workflows that use templates.
Checklist:
> Update argo chart for 2.4.2

- charts/argo-events/Chart.yaml
- charts/argo-events/templates/argo-events-cluster-roles.yaml
- charts/argo-events/templates/argo-events-sa.yaml
The suffix -sa is redundant, remove it to be consistent with
ServiceAccount naming in argo, and argo-cd charts.
Checklist:
> [argo-events] Rename argo-events-sa to argo-events

- .circleci/config.yml
- .circleci/lintconf.yaml
- CONTRIBUTING.md
- charts/argo-cd/Chart.yaml
- charts/argo-ci/Chart.yaml
- charts/argo-ci/values.yaml
- charts/argo-events/Chart.yaml
- charts/argo/Chart.yaml
- scripts/lint.sh
This updates the Helm linting system with the following changes:
- Import lintconf.yaml with small change to comment distance in order to
match existing values.yaml standards
- Update Chart.yaml and values.yaml in each chart to pass linting
standards
- Maintainers added to each chart from OWNERS + CODEOWNERS, the linter
requires GitHub usernames so argo-events maintainer names were converted
- README updated with documentation around chart standards and testing
- A local shell script added for running lint tests locally
Checklist:
> Fix up chart linting, add docs and lint script

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
Checklist:
> K8S tolerations should contain list instead of object

- charts/argo-events/Chart.yaml
- charts/argo-events/README.md
- charts/argo-events/ci/test-values.yaml
- charts/argo-events/templates/argo-events-cluster-roles.yaml
- charts/argo-events/templates/argo-events-sa.yaml
- charts/argo-events/values.yaml
Bumped the version of argo-events to v0.11 and updated the clusterrole to be able to view workflowTemplates just like the clusterroles in the argo installation.
I also had to update the way that serviceAccount was handled when additionaSaNamespaces was set in order to work.  I also added a test-values.yaml in order to include this in testing if the chart-test install tests are running.
Chart has been installed using the additional namespaces value in a test cluster.
Checklist:
* [ x ] I have update the chart version in `Chart.yaml` following Semantic Versioning.
* [ x ] Any new values are backwards compatible and/or have sensible default.
* [ x ] I have followed the testing instructions in the [contributing guide](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md).
* [ x ] …
> [argo-events] v0.11 update

- CONTRIBUTING.md
The part-of is incorrect compared to the argo-cd helm chart, which
installs this crd as a part of argocd (without the dash).
Checklist:
> Fix delete crd command

- charts/argo-cd/.helmignore
- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/crds/application-crd.yaml
- charts/argo-cd/templates/crds/appproject-crd.yaml
- charts/argo-cd/templates/dex/deployment.yaml
- charts/argo-cd/values.yaml
This bumps the version of ArgoCD to 1.3 and the chart version to 1.1 due
to a CRD change. Restored conditional CRDs to correct #27. Additionally,
some value defaults were added so Helm strict linting could pass.
Checklist:
> [charts/argo-cd] Update to 1.3, some chart cleanup

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-repo-server/repository-credentials-secret.yaml
- charts/argo-cd/values.yaml
* Argo CD Helm Chart: Add a Secret Resource in Repo Server for configuring Repository Credentials
Checklist:
> ArgoCD: Configure Repository Credentials in Values

- charts/argo-cd/Chart.yaml
- charts/argo-cd/values.yaml
Extra arg handling changed in v1 release #129 , and expects map rather than list.
Just updating the comment to align with that expectation.
With the previous doc, I got the following in deployment:
```
containers:
- command:
- argocd-server
...
- --0=map[insecure:true]
image: argoproj/argocd:v1.3.0
```
And got a straight error when a pod started:
```
time="2019-11-25T11:24:29Z" level=fatal msg="unknown flag: --0"
```
Checklist:
> Correct the values.yaml comment for extra arg

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-application-controller/servicemonitor.yaml
- charts/argo-cd/templates/argocd-repo-server/servicemonitor.yaml
- charts/argo-cd/templates/argocd-server/servicemonitor.yaml
Why do we need it:
When I enable Metrics and run `helm template ./` i receive next template 
```
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
name: release-name-argocd-server
labels:
app.kubernetes.io/name: argocd-server
helm.sh/chart: argo-cd-1.2.2
app.kubernetes.io/instance: release-name
app.kubernetes.io/managed-by: Tiller
app.kubernetes.io/part-of: argocd
app.kubernetes.io/component: server
null
spec:
endpoints:
- port: metrics
interval: 30s
path: /metrics
namespaceSelector:
matchNames:
- default
selector:
matchLabels:
app.kubernetes.io/instance: release-name
app.kubernetes.io/name: argocd-server-metrics
app.kubernetes.io/component: server
---
```
`null` is incorrect 
Also when I try to install or upgrade my release I receive error. 
```
UPGRADE FAILED …
```
> [charts/argo-cd] Fix servicemonitors

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-application-controller/deployment.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/templates/dex/deployment.yaml
- charts/argo-cd/templates/redis/deployment.yaml
- charts/argo-cd/values.yaml
> [charts/argo-cd] add support of custom environment variables

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/values.yaml
This pull request allows the configuration of custom tooling as described in https://argoproj.github.io/argo-cd/operator-manual/custom_tools/ .
Checklist:
> Allow custom tools for argo-cd in helm chart

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-application-controller/prometheusrule.yaml
- charts/argo-cd/values.yaml
This patch adds a few simple rules which you can leverage to make
sure that your infrastructure is up to date.  They are optional
and opt-in only.
There is not a lot of customization initially but this is a start
of a simple framework to deliver this.
Checklist:
> [argo-cd] Added simple PrometheusRule

- charts/argo-cd/Chart.yaml
> fix: Bump appVersion to v1.3.6 for ArgoCD

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-application-controller/deployment.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/templates/redis/deployment.yaml
- charts/argo-cd/values.yaml
Signed-off-by: David J. M. Karlsen <david@davidkarlsen.com>
Adds security-context.
I wonder if it makes sense to reuse some other charts for dex / redis to avoid reinventing the wheel for these?
Checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/argoproj/argo-helm/185)
> feat: Add securityContext. Fixes #96

- charts/argo-cd/Chart.yaml
- charts/argo-ci/Chart.yaml
- charts/argo-events/Chart.yaml
- charts/argo/Chart.yaml
The path to the argo.png image has changed in
the Argo repository.
The helm charts icon URL still points to the
old URL which is invalid. The image has moved
from /argo.png to /docs/assets/argo.png.
Checklist:
> fix: Update Argo icon URL for the Helm charts

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-application-controller/deployment.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/templates/dex/deployment.yaml
- charts/argo-cd/templates/redis/deployment.yaml
- charts/argo-cd/values.yaml
> feat: add kubernetes version tag and set container security capabilities

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/route.yaml
This spec.subdomain field is not part of OpenShift 3.11 route OpenAPI
specification and since it's empty it can safely be removed without impacting
OpenShift 4.
Checklist:
> fix: remove spec.subdomain field from OpenShift route

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-configs/argocd-secret.yaml
- charts/argo-cd/values.yaml
Automatically setting password modification time to the current time leads to
it changing every time the chart is rendered. Ironically, this is a problem
when Argo CD manages itself using this chart ;-)
Checklist:
> Allow manually setting password modification time

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/values.yaml
The official Argo-CD HA manifests do not scale the dex server
or the application controller past 1 because they still have
local caches and cannot support more than one pod at a time
Signed-off-by: Carson Anderson <ca@carsonoid.net>
Checklist:
> feat: Make server component replicas configurable

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
Add the replica values to the readme.
Checklist:
> docs: add replica values to the readme

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/templates/_helpers.tpl
- charts/argo-rollouts/templates/argo-rollouts-aggregate-roles.yaml
- charts/argo-rollouts/templates/argo-rollouts-clusterrole.yaml
- charts/argo-rollouts/templates/argo-rollouts-clusterrolebinding.yaml
- charts/argo-rollouts/templates/argo-rollouts-deployment.yaml
- charts/argo-rollouts/templates/argo-rollouts-metrics-service.yaml
- charts/argo-rollouts/templates/argo-rollouts-role.yaml
- charts/argo-rollouts/templates/argo-rollouts-rolebinding.yaml
- charts/argo-rollouts/templates/argo-rollouts-sa.yaml
- charts/argo-rollouts/templates/crds/analysis-run-crd.yaml
- charts/argo-rollouts/templates/crds/analysis-template-crd.yaml
- charts/argo-rollouts/templates/crds/experiment-crd.yaml
- charts/argo-rollouts/templates/crds/rollout-crd.yaml
- charts/argo-rollouts/values.yaml
I've created this chart based on https://github.com/argoproj/argo-rollouts/tree/v0.7.0/manifests
Checklist:
> feat: Add chart for argo-rollouts

- charts/argo/Chart.yaml
- charts/argo/crds/workflow-template-crd.yaml
Why
---
The Helm chart wasn't installing the `workflow-template` CRD.
Checklist:
Closes #234
> fix: Add missing CRD to the `crds` directory

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-application-controller/service.yaml
- charts/argo-cd/templates/argocd-repo-server/service.yaml
- charts/argo-cd/values.yaml
When using istio with argocd the ports need to be named with the correct prefixes so it gets routed correctly. Therefore it would be nice to be able to configure port names of the helm chart.
Checklist:
> fix: Make port names configurable for repo-server and controller

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
VolumeMounts have to be indented with 8 spaces. Fixes #238 
Checklist:
> fix: volumeMounts indention for argocd-server

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-application-controller/deployment.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-repo-server/hpa.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/hpa.yaml
- charts/argo-cd/values.yaml
This PR adds a horizontal pod autoscaling to the server and repoServer components. The HPA template is inspired by the official nginx controller-hpa: https://github.com/helm/charts/blob/master/stable/nginx-ingress/templates/controller-hpa.yaml
Fixes https://github.com/argoproj/argo-helm/issues/218
Checklist:
> feat: Add HPA for ArgoCD server and repoServer components

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-repo-server/hpa.yaml
- charts/argo-cd/templates/argocd-server/hpa.yaml
Argocd is displaying a diff on HPA resources as k8s is internally reordering the metrics (see: https://github.com/argoproj/argo-cd/issues/1079).
With this PR, the metrics should be in same order as k8s wants to.
Checklist:
> fix: reorder hpa metrics to avoid displaying diffs in argocd

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-application-controller/deployment.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/templates/dex/deployment.yaml
- charts/argo-cd/templates/redis/deployment.yaml
- charts/argo-cd/values.yaml
A new global parameter has been introduced  `global.ImagePullSecreet =[]`, it allows deploying original chart with docker images from private repositories. Private repositories are quite a typical thing for the corporate world.
More info about ImagePullSecrets https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
Carefully tested with the latest version of argo and argocd-chart
Checklist:
> feat: Support ImagePullSecrets parameter (support private registries)

- charts/argo/Chart.yaml
- charts/argo/templates/server-deployment.yaml
- charts/argo/values.yaml
> fix: Hotfix server.baseHref value not being used

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/NOTES.txt
- charts/argo-cd/templates/argocd-application-controller/deployment.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/servicemonitor.yaml
Supersedes #244 (I messed up the rebase :man_facepalming: )
Relates to #232
This change allows ArgoCD chart to render multiple times the same flag with different values
Mainly, if not only, used to specify multiple Redis Sentinel addresses
https://github.com/argoproj/argo-cd/blob/5ec5aeb002cfc9167dba0fb77e7a08a2dc0932cf/manifests/ha/base/overlays/argocd-application-controller-deployment.yaml#L16
https://github.com/argoproj/argo-cd/blob/aeb48b0a69be764f381511f7749d1e094fc79225/util/cache/cache.go#L33
```
--sentinel
```
using this syntax
```
controller:
extraArgs:
- --sentinel
- argocd-redis-ha-announce-0
- --sentinel
- argocd-redis-ha-announce-1
- --sentinel
- argocd-redis-ha-announce-2
```
instead of
```
controller:
extraArgs:
sentinel=argocd-redis-ha-announce-0: …
```
> feat: extraArgs allows same flag multiple times

- charts/argo-cd/Chart.yaml
- charts/argo-cd/values.yaml
Addresses issue #281 
Inconsistency introduced in #265
Checklist:
> fix: set extraArgs default to be a sequence

- charts/argo-cd/Chart.yaml
- charts/argo-cd/values.yaml
An accented character snuck into values.yaml: `bitbucketUUÌD` rather than `bitbucketUUID`
Checklist:
> fix: remove foreign character

- charts/argo/Chart.yaml
- charts/argo/templates/server-deployment.yaml
- charts/argo/values.yaml
This PR provides a way to specify additional command line arguments for `argo-server`. This gives chart users the flexibility in invoking `argo-server` without having to modify the chart.
One of the ways this can be used is to specify a custom config map. Currently, the chart creates a config map for the workflow controller and configures its command line to use it. It does not configure `argo-server` to use that map, however. That means `argo-server` installed via the chart cannot pick up persistence database configuration  and is unable to show archived workflows. Being able to specify a config map via extraArgs helps mitigate issues like this.
Checklist:
> feat: Add support for extra arguments to Argo Server

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-server/service.yaml
- charts/argo-cd/values.yaml
I added a parameter for ArgoCD service. This pull request is similar to https://github.com/argoproj/argo-helm/pull/44. I want to set `loadBalancerSourceRanges` in ArgoCD.
Checklist:
> feat: Add loadBalancerSourceRanges parameter for ArgoCD service resource

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/service.yaml
The [README.md](https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/README.md) file lists the `server.service.labels` setting, and so does the [values.yaml](https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/values.yaml) file:
```yaml
service:
annotations: {}
labels: {}
type: ClusterIP
```
However, in the [argocd-server/service.yaml](https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/templates/argocd-server/service.yaml) file this setting was not implemented. This commit adds that functionality.
Checklist:
> fix: implementing server service labels

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
Checklist:
Simply upgrading the Argo CD version from v1.5.1 to v1.5.2, as the upgrade is strongly recommended to tackle the serious vulnerability detailed in https://github.com/argoproj/argo-cd/blob/master/docs/security_considerations.md#cve-2020-5260---possible-git-credential-leak
> fix: Upgrade Argo CD with v1.5.2 for security patch

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/ingress.yaml
- charts/argo/Chart.yaml
- charts/argo/templates/server-ingress.yaml
> fix: use networking.k8s.io/v1beta1 apiVersion for ingress if supported

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-server/backendconfig.yaml
- charts/argo-cd/values.yaml
Hi!
This PR wants to add configuration about [CRD BackendConfig in Google Kubernetes Engine](https://cloud.google.com/kubernetes-engine/docs/concepts/backendconfig) to argocd-server.
Checklist:
> feat: add BackendConfig configuration for GKE

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
Currently the  `openshift.enabled` flag causes the repo server to have an invalid command
argument. It's also not documented yet.
Signed-off-by: Johannes Siebel <johannes.siebel@gmail.com>
Checklist:
> fix: usage of openshift.enabled flag

- charts/argo/Chart.yaml
- charts/argo/templates/workflow-controller-config-map.yaml
- charts/argo/values.yaml
This adds support for the new Argo workflow defaults [feature](https://github.com/argoproj/argo/blob/master/docs/default-workflow-specs.md) to the chart.
Checklist:
> feat: Adds support for workflow defaults in Argo.

- charts/argo/Chart.yaml
- charts/argo/templates/server-cluster-role.yaml
- charts/argo/templates/workflow-controller-clusterrole.yaml
- Grant secret permission to argo server
- Limit the secrets permissions of the workflow controller
Checklist:
> fix: Argo Server Secrets Permissions 

- charts/argo/Chart.yaml
- charts/argo/templates/server-ingress.yaml
- charts/argo/values.yaml
We use AWS EKS to host our cluster.  When we setup services using https we normally use ACM for the certificate, route53 for the domain and an ALB for handling the traffic to the service itself.  As part of this we like to put an http -> https redirect on port 80.  To do this we need to add another backend, as well as add an additional annotation on the load balancer.
```
alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
```
This PR just gives us the ability to add the additional listener rule on the ALB to perform that redirect.
Checklist:
> feat: Allow custom paths for server ingress

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
Mention bcrypt hashing for admin password value
It took me while to figure out that value needs to be hashed. I spend an hour searching why it's not working for me when I was passing plain text password. :)
Checklist:
> docs: Mention bcrypt hashing for admin password in README.md

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-server/service.yaml
- charts/argo-cd/values.yaml
feat: Allows to route traffic via istio to split gRPC from http
Checklist:
> feat: Allow argo-cd server service port names to be configured.

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
Updating argocd version to 1.5.3
Updating documentation and default values.
Bumping patch on chart version.
Checklist:
> chore: Upgrade Argo CD version to 1.5.3

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
> fix: fix typo in readme.

- charts/argo/Chart.yaml
- charts/argo/crds/cluster-workflow-template-crd.yaml
- charts/argo/templates/cluster-workflow-template-crd.yaml
- charts/argo/templates/server-cluster-role.yaml
- charts/argo/templates/workflow-aggregate-roles.yaml
- charts/argo/templates/workflow-controller-clusterrole.yaml
This PR adds chart support for `ClusterWorkflowTemplate`, a feature implemented in Argo 2.8. It adds the CRD and modifies the RBAC rules to allow the workflow controller and the server to access the `ClusterWorkflowTemplate` objects. The chart's minor version has been bumped because the changes are new features.
Checklist:
> feat: Add support for ClusterWorkflowTemplates (a 2.8 feature).

- charts/argo/Chart.yaml
- charts/argo/templates/workflow-controller-config-map.yaml
- charts/argo/values.yaml
Sometimes one needs to specify environment for the Argo workflow executor pods. For example, to control behavior of the AWS client.
Checklist:
> feat: Enable specifying environment for Argo  workflow executor.

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/service.yaml
Hey team, while trying to set some elb security groups, I ran into an error:
```bash
Comparing release=argocd, chart=argo/argo-cd
in ./helmfile.yaml: failed processing release argocd: helm exited with status 1:
Error: Failed to render chart: exit status 1: Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Service.spec): unknown field "loadBalancerSourceranges" in io.k8s.api.core.v1.ServiceSpec
Error: plugin "diff" exited with error
Running after_script
00:01
Uploading artifacts for failed job
ERROR: Job failed: exit code 1
```
Upon looking at the chart, it appears there is a typo on the key `loadBalancerSourceRanges` -- per kube [docs](https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provi …
> fix: typo on spec.loadBalancerSourceRanges for argocd-server/service.yaml

- charts/argo/Chart.yaml
- charts/argo/templates/workflow-controller-config-map.yaml
keyPrefix is deprecated; use keyFormat instead: https://github.com/argoproj/argo/blob/master/config/config.go#L183
Checklist:
> fix: workflow-controller-config-map.yaml

- charts/argo/Chart.yaml
- charts/argo/values.yaml
This has simply added the comment `archive: false` flag to the values.yaml file.
I have added it because it must be set to true in order for argo to actually start archiving old workflows. I had no idea the flag exised and it was only after hunting around on the argo website for a while that I found this:
https://argoproj.github.io/docs/argo/workflow-archive.html
Upon trying that the system sprang to life and all was good with the world.
I just thought having this here might save someone else the trouble!
Checklist:
> docs: Add archive option to values.yaml to clarify persistence options

- CODEOWNERS
- CONTRIBUTING.md
- charts/argocd-notifications/.helmignore
- charts/argocd-notifications/Chart.yaml
- charts/argocd-notifications/README.md
- charts/argocd-notifications/templates/_helpers.tpl
- charts/argocd-notifications/templates/configmap.yaml
- charts/argocd-notifications/templates/deployment.yaml
- charts/argocd-notifications/templates/role.yaml
- charts/argocd-notifications/templates/rolebinding.yaml
- charts/argocd-notifications/templates/secret.yaml
- charts/argocd-notifications/templates/serviceaccount.yaml
- charts/argocd-notifications/values.yaml
The following chart is a contribution from work done at https://github.com/Bandwidth/ to facilitate installing https://github.com/argoproj-labs/argocd-notifications via Helm chart based on https://github.com/argoproj-labs/argocd-notifications/blob/master/manifests/install.yaml
Checklist:
> feat: Helm chart contribution for argocd-notifications

- charts/argocd-notifications/Chart.yaml
- charts/argocd-notifications/templates/deployment.yaml
- charts/argocd-notifications/values.yaml
- Move `strategy` from the Pod template spec to the Deployment spec
- Add `updateStrategy` value for configuring Deployment `strategy`
Checklist:
> fix: ArgoCD Notifications - Deployment manifest udpateStrategy

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/route.yaml
Status fields prevent resources from converging.
Checklist:
> fix: remove Argo CD server route status field

- charts/argocd-notifications/Chart.yaml
- charts/argocd-notifications/templates/secret.yaml
- charts/argocd-notifications/values.yaml
Checklist:
Thanks for adding this @andyfeller! It looks like the existing version adds support for slack, but I didn't see webhooks. This adds support for webhooks (see: https://argoproj-labs.github.io/argocd-notifications/services/webhook/).
> feat(argocd-notifications): Add support for webhook triggers

- charts/argo/Chart.yaml
- charts/argo/templates/workflow-controller-config-map.yaml
- charts/argo/values.yaml
This change will allow to configure the Argo Server SSO [support](https://github.com/argoproj/argo/pull/2745) (new feature in Argo 2.9).
This should only be merged after Argo v2.9.0 is released.
Checklist:
> feat(argo): Adds SSO configuration for Argo Server.

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-application-controller/serviceaccount.yaml
- charts/argo-cd/templates/argocd-server/serviceaccount.yaml
- charts/argo-cd/values.yaml
Updates the argo-cd helm chart allowing you to specify annotations for the ServiceAccounts for Controller and Server. Additionally adds a few missing parameters to the README.md.
Need these changes in order to add the IAM/EKS Service Account roles to enable cross-account cluster access. Looks like server is required for the argocd cli activity and Controller for the sync. 
Checklist:
> feat(argocd): Allow specifying annotations for serviceaccounts

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-server/ingress-grpc.yaml
- charts/argo-cd/values.yaml
This is based on the information found at https://argoproj.github.io/argo-cd/operator-manual/ingress/
Checklist:
> feat: Enable dedicated grpc ingress for argo-cd-server

- charts/argocd-notifications/Chart.yaml
- charts/argocd-notifications/templates/_helpers.tpl
- charts/argocd-notifications/templates/bots/slack/deployment.yaml
- charts/argocd-notifications/templates/bots/slack/role.yaml
- charts/argocd-notifications/templates/bots/slack/serviceaccount.yaml
- charts/argocd-notifications/templates/serviceaccount.yaml
This PR 
- Updates slack bot service account role permissions with configmap / secret
- Updates slack bot service account create to not require secret creation
- Ensures all service account naming is consistent via `argocd-notifications.bots.slack.serviceAccountName`
- Changes the default serviceaccount name to be suffixed with -bot for backwards compat.
Checklist:
> argocd-notifications: fix serviceaccount name

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/templates/argo-rollouts-deployment.yaml
- charts/argo-rollouts/values.yaml
I've simply updated the templates here such that I can set the requests and limits for argo-rollouts locally in values files.
I left the true default as it was -- there are no requests or limits for Argo Rollouts by default.
I wrote in some guessed "defaults if you want them" as comments in the values file.  They're based on one environment I have access to, but I admit that I see wide variance between environments so I don't know how useful those are.  :shrug: They're a starting point.
Checklist:
> feat: argo-rollouts resources in helm values

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-configs/argocd-cm.yaml
- charts/argo-cd/templates/argocd-configs/argocd-rbac-cm.yaml
- charts/argo-cd/templates/argocd-configs/argocd-ssh-known-hosts-cm.yaml
- charts/argo-cd/templates/argocd-configs/argocd-tls-certs-cm.yaml
- charts/argo-cd/values.yaml
This PR add support for annotating the ConfigMaps. This is useful when deploying ArgoCD with Spinnaker: [by default Spinnaker adds a suffix to the configmap](https://spinnaker.io/reference/providers/kubernetes-v2/#strategy), making the ArgoCD deployment fail.
Failing deployment
Versioned ConfigMaps
Unversioned ConfigMaps
Working deployment
The other deployments are not working because they're missing a Pod Security Policy, I will address that in another PR.
Checklist:
> feat: Add support for configmaps annotations

- charts/argocd-notifications/Chart.yaml
- charts/argocd-notifications/templates/_helpers.tpl
- charts/argocd-notifications/templates/bots/slack/service.yaml
- charts/argocd-notifications/templates/deployment.yaml
- charts/argocd-notifications/templates/service-metrics.yaml
- charts/argocd-notifications/templates/servicemonitor.yaml
- charts/argocd-notifications/values.yaml
Checklist:
This PR
* Adds monitoring to the controller
* Adds `logLevel` option
* Adds slack bot service annotations allowing external DNS registration, e.g.:
```
annotations:
external-dns.alpha.kubernetes.io/hostname:  argocd-notifications-bot.example.com
```
documentation:
* argocd-notifications metrics -> https://github.com/argoproj-labs/argocd-notifications/blob/master/docs/monitoring.md
> [argocd-notifications] add monitoring and slack bot service annotations

- charts/argocd-notifications/Chart.yaml
- charts/argocd-notifications/templates/deployment.yaml
- charts/argocd-notifications/values.yaml
- **Argo Notifications**: Add `extraArgs` value
- Allow for setting arbitrary extra arguments for the argo-notifications binary. Primarily we need this for `--argocd-repo-server` as we have some environments which run with a non-standard repo server service name.
Checklist:
> feat: Argo Notifications - add extraArgs value

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/templates/argo-rollouts-clusterrole.yaml
The `ClusterRole` is missing the necessary permissions to list and delete `pods` causing the **restart** command to fail because the controller only has `list` and `delete` verb permissions for its own namespace through its namespaced role definition.
I've updated the `ClusterRole` to include the following rule to allow the controller to execute its restarts:
```yaml
- apiGroups:
- ""
resources:
- pods
verbs:
- list
- delete
```
1) Install argo-rollouts in its own namespace with `.Values.clusterInstall` set to `true`.
2) Install a `Rollout` resource in different rollout and have it create a replicaset with pods
3) Run `kubectl argo rollouts restart ROLLOUT_NAME -n YOUR_NAMESPACE`
The command silently fails and nothing happens to my Rollout and the following error was emitted in the …
> fix(argo-rollouts): When running argo-rollouts cluster-wide, the restart command is unable to restart pods

- charts/argocd-notifications/Chart.yaml
- charts/argocd-notifications/templates/deployment.yaml
- charts/argocd-notifications/values.yaml
This PR adds the ability to set arbitrary annotations on the deployment via `podAnnotations`. My use case was to add annotations that allow Datadog to scrape metrics from the pod.
Checklist:
> feat: argocd-notifications 1.0.10 add podAnnotations

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/templates/argo-rollouts-metrics-service.yaml
- charts/argo-rollouts/values.yaml
This allows user to add the necessary annotation on the metrics service to allow prometheus scraping.
Checklist:
> feat(argo-rollouts): Add configurable annotation to the metrics service

- charts/argo/Chart.yaml
- charts/argo/templates/workflow-controller-cluster-roles.yaml
This adds support for the PodDisruptionBudget feature of Argo.  Without this, PDBs will fail to be created/managed.
Ref:  https://github.com/argoproj/argo/blob/dae0f2df1ffcc8a2ff4f3dce1ea7da3f34587e2f/manifests/cluster-install/workflow-controller-rbac/workflow-controller-clusterrole.yaml#L84-L91
Checklist:
> fix(argo):  add missing rbac to support pdbs

- charts/argocd-notifications/Chart.yaml
- charts/argocd-notifications/templates/bots/slack/deployment.yaml
- charts/argocd-notifications/templates/bots/slack/service.yaml
- charts/argocd-notifications/values.yaml
Checklist:
Changes:
Adds support for configuring the bot listening port for people who want it to listen on 443 (for example)
> feat: add support for configuring bot port

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/ingress-grpc.yaml
- charts/argo-cd/templates/argocd-server/ingress.yaml
- charts/argo-cd/values.yaml
Similar to #317, this allows us to add extra paths to Argo CD.
This adds compatibility with the ALB Ingress Controller when using EKS
to be able to add the additional listener rule to perform a HTTP->HTTPS
redirect on port 80.
Unfortunately, we can't use the same structure as used in #317 because
there is an existing .Values.server.ingress.paths that we have to maintain
backwards compatibility with. The existing one is hard-coded to use a
fixed serviceName and servicePort, which doesn't work for the EKS ALB case.
Instead, we add .Values.server.ingress.extraPaths (and a similar var for
ingressGrpc) where a user directly specifies the entire rule, including
the path and backend information. Examples are added to the values.yaml
file for the extra path for EKS, with an empty list as a …
> feat: Argo CD allow custom paths for ingress

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/ingress-grpc.yaml
- charts/argo-cd/templates/argocd-server/ingress.yaml
> fix: Helm giving linting error when no ingress or ingressGrpc extraPaths are given

- charts/argo/Chart.yaml
- charts/argo/templates/workflow-controller-config-map.yaml
- charts/argo/values.yaml
Checklist:
This PR allows GCS to be configured as the default artifact repository.
[PR 344](https://github.com/argoproj/argo-helm/pull/344) attempts to fix this but does not work as `s3` has defaults which Argo will use instead of any values in `gcs`.
Example gcs output:
```
config: |
artifactRepository:
gcs:
bucket: my-argo-artifacts
keyFormat: '{{workflow.namespace}}/{{workflow.name}}/'
```
Example minio/s3 output:
```
config: |
artifactRepository:
s3:
accessKeySecret:
key: accesskey
name: argo-workflows-minio
secretKeySecret:
key: secretkey
name: argo-workflows-minio
bucket: argo-artifacts
endpoint: argo-workflows-minio:9000
insecure: true
```
> feat: Support GCS artifactRepository

- charts/argo-cd/Chart.yaml
- charts/argo-cd/values.yaml
> chore: bump argocd to version to v1.7.6

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
When upgrading to the latest 1.7.x images of ArgoCD, we experienced issues with the repo server starting up due to https://github.com/argoproj/argo-cd/issues/4127.
This incorporates fixes from https://github.com/argoproj/argo-cd/pull/4136.
Checklist:
> fix: Adding EmptyDir Volume for ArgoCD Repo Server on OpenShift

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/dex/deployment.yaml
- charts/argo-cd/templates/dex/service.yaml
- charts/argo-cd/templates/dex/servicemonitor.yaml
- charts/argo-cd/values.yaml
Since https://github.com/argoproj/argo-cd/pull/3249 metrics are turned on in `dex`, but not on in helm chart
Checklist:
> feat: add metrics for argo-cd/dex

- charts/argo/Chart.yaml
- charts/argo/templates/server-cluster-roles.yaml
This change gives Argo server the permission to read events, to the event display [feature](https://github.com/argoproj/argo/issues/3673) in 2.11.
Checklist:
> feat(argo): Allow Argo server read access to events.

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
> fix: default argocd version in documentation

- charts/argo/Chart.yaml
- charts/argo/templates/server-crb.yaml
- charts/argo/templates/server-sa.yaml
- charts/argo/values.yaml
In some situation, one needs to provide Argo Server with a different set of permissions. For example, to prohibit editing of workflow templates or prohibit creating new ones. This PR will allow users to use externally created service account which can be bound to a role with any desired set of permissions.
Checklist:
> feat(Argo): Make Argo Server service account creation conditional.

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
While uid_entrypoint.sh contains the OpenShift specific manipulation of
/etc/passwd it also starts the reposerver via tini and so ensures that any
zombies produced by reposerver and its decendants are collected.
This matches the behaviour from the manifests included with the main ArgoCD
project. See:
* https://github.com/argoproj/argo-cd/blob/f93da5346c3dfe0ec75549fd78b2d30ce7d5cfad/manifests/base/repo-server/argocd-repo-server-deployment.yaml#L24
* https://github.com/argoproj/argo-cd/pull/3721
* https://github.com/argoproj/argo-cd/issues/3611
Checklist:
> fix(argocd): Unconditionally start reposerver with uid_entrypoint.sh

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/dex/deployment.yaml
This imports the change made in this PR https://github.com/argoproj/argo-cd/pull/3136/ 
This fixes the issue where the dex server init container `copyutil` runs more than once and ends up in a crashLoopBackoff state because the target file of the `cp` command is currently in use.
Checklist:
* [✅] I have update the chart version in `Chart.yaml` following Semantic Versioning.
* [✅ ] Any new values are backwards compatible and/or have sensible default.
* [✅ ] I have followed the testing instructions in the [contributing guide](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md).
* [✅ ] I have signed the CLA and the build is green.
* [✅ ] I will test my changes again once merged to master and published.
Changes are automatically published when merged to `master`. They are not …
> fix(argocd): Make dex init container not overwrite argocd-util

- charts/argo/Chart.yaml
- charts/argo/crds/cluster-workflow-template-crd.yaml
- charts/argo/crds/cron-workflow-crd.yaml
- charts/argo/crds/workflow-crd.yaml
- charts/argo/crds/workflow-eventbinding-crd.yaml
- charts/argo/crds/workflow-template-crd.yaml
- charts/argo/templates/server-cluster-roles.yaml
- charts/argo/values.yaml
Changes taken from this comparison: https://github.com/argoproj/argo/compare/release-2.10...release-2.11?expand=1#diff-e6a7473c56a01263d2a13719d20af959R46 (`manifests/quick-start-minimal.yaml` diff)
Checklist:
> feat: upgrade argo to v2.11

- charts/argo/Chart.yaml
- charts/argo/templates/server-deployment.yaml
- charts/argo/templates/workflow-controller-deployment.yaml
- charts/argo/values.yaml
Checklist:
---
This PR adds support to optionally use PriorityClasses in the Argo Workflows chart. In case the value is omitted, the pod will run with the cluster defaults.
Priority classes allow pods to avoid being evicted if there's resource contention in a cluster. In case of a race condition, the smaller priority pods will be kicked out first; similarly, when the kube-scheduler makes scheduling decisions, it will ensure first the higher priority pods get deployed.
This can be quite an important parameter for the Argo Workflows main components, as a [random user workflow](https://github.com/argoproj/argo/blob/346292b1b0152d5bfdc0387a8b2c11b5d6d5bac1/workflow/controller/workflowpod.go#L667-L6 …
> feat(argo): add PriorityClass support

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/dex/service.yaml
Currently `.Values.dex.metrics.service.annotations` is not used anywhere - this adds that to the template.
Checklist:
> fix: Add annotations and labels to dex service [argo-cd]

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/service.yaml
- charts/argo-cd/values.yaml
Named target ports are not supported by GCE health checks, so when deploying argocd on GKE and exposing it via GCE ingress, the health checks fail and the load balancer returns a 502. This PR makes it possible to opt-out of using named target port for argocd.
Checklist:
> fix(argocd): optional named target port

- charts/argo/Chart.yaml
- charts/argo/templates/server-deployment.yaml
- charts/argo/values.yaml
https://github.com/argoproj/argo/pull/4350 started using the `/tmp` directory for storing temporary files created for the purposes of downloading artifacts. But the standard image the project built is created from scratch and does not contain `/tmp`. The project's own manifests were updated to map the directory using an `emptyDir` volume, but this chart was not updated.  That started causing failures for users of this chart.
This change adds the `/tmp` mapping into the chart, thus fixing the artifact downloading.
Checklist:
> fix(argo): Map the /tmp directory into server pods.

- charts/argo/Chart.yaml
- charts/argo/templates/server-cluster-roles.yaml
- charts/argo/values.yaml
Currently, the chart allows the Argo server to access all the secrets in the namespace. It's not good security practice, as an attacker taking over a server pod will have access to all of them. This change adds support for restricting the secrets the server can read to a given list so that only need-to-know secrets can be allowed.
Checklist:
> feat(Argo): Add secret access whitelist for server.

- charts/argo/Chart.yaml
- charts/argo/templates/workflow-controller-deployment.yaml
Checklist:
the current podworkers templating includes an entire map of objects when we just want the one value. A quick test:
```
$ git checkout master
$ helm template argo charts/argo --set 'controller.podWorkers=64' > old.txt
$ git checkout fix_pod_workers_deployment_arg
$ helm template argo charts/argo --set 'controller.podWorkers=64' > new.txt
$ diff old.txt new.txt -C 1
*** 377,379 ****
- "--pod-workers"
!           - "map[Capabilities:0x29b90a0 Chart:0xc000294360 Files:map[.helmignore:[35 32 80 97 116 116 101 114 110 115 32 116 111 32 105 103 110 111 114 101 32 119 104 101 110 32 98 117 105 108 100 105 110 103 32 112 97 99 107 97 103 101 115 46 10 35 32 84 104 105 115 32
115 117 112 112 …
```
> fix --pod-workers helm context

- charts/argo/Chart.yaml
- charts/argo/templates/server-deployment.yaml
- charts/argo/values.yaml
Checklist:
This fixes the issue raised in https://github.com/argoproj/argo-helm/issues/505. It's worth noting this implementation is different than the suggestion in the original issue. Instead of requiring users to update both the `extraArgs` and readiness probe http scheme to enable tls, we can automatically change the http scheme if tls is enabled.
Tested this locally by:
* Deploying the chart with no extra args
* Submitting workflow defined in the app notes
* Update the values.yaml to have `server.secure: true` and re-deploy the chart
* Submitting workflow defined in the app notes
My test results:
✅ confirmed that the chart was deployed successfully with `server.secure` set to false
✅ …
> fix(argo): Use https for readiness probe in secure mode

- charts/argo/Chart.yaml
- charts/argo/templates/workflow-controller-deployment.yaml
- charts/argo/values.yaml
This PR adds support for setting custom environment variables on the workflow controller.
Checklist:
> feat(argo): Add support for setting env vars for workflow controller.

- charts/argo/Chart.yaml
Checklist:
---
Hello everyone !
https://helm.sh/docs/faq/#chartyaml-apiversion-bump
I propose a change of `apiVersion` in version 2 to have a stability on helm3. 
Thanks 👍
> feat(argo): bump apiVersion and support helm3

- .circleci/chart-testing.yaml
- .circleci/config.yml
- charts/argo-cd/Chart.yaml
- charts/argo-cd/crds/crd-application.yaml
- charts/argo-cd/crds/crd-project.yaml
- charts/argo-cd/requirements.lock
- charts/argo-cd/requirements.yaml
- charts/argo/Chart.yaml
- charts/argo/requirements.lock
- charts/argo/requirements.yaml
- charts/argo/templates/cluster-workflow-template-crd.yaml
- charts/argo/templates/cron-workflow-crd.yaml
- charts/argo/templates/server-cluster-roles.yaml
- charts/argo/templates/workflow-controller-cluster-roles.yaml
- charts/argo/templates/workflow-crd.yaml
- charts/argo/templates/workflow-template-crd.yaml
- charts/argo/values.yaml
- scripts/publish.sh
This PR adds some permissions missing for Argo v2.12:
- When SSO is enabled Argo server needs access to the `sso` secret.
- Access to service accounts by the server is only required when RBAC is enabled.
- The workflow controller needs access to particular lease objects to implement leader elections.
Checklist:
> fix(argo): Add RBAC permissions for v2.12.

- charts/argo/Chart.yaml
- charts/argo/templates/server-cluster-roles.yaml
- charts/argo/values.yaml
Currently, the chart uses `.Values.server.rbac` for settings related to the RBAC authorization configuration. But the server itself uses the settings under `.Values.server.sso.rbac`, which results in a discrepancy and confusion. This change make the chart use `.Values.server.sso.rbac` as well.
Checklist:
> fix(Argo): Unify settings for activating rbac.

- charts/argo/Chart.lock
- charts/argo/Chart.yaml
- charts/argo/requirements.yaml
This PR moves the chart dependencies into `Chart.yaml`. Using `dependencies.yaml` is deprecated and Helm is issuing warnings for it.
Checklist:
> fix(argo): Move dependencies into Chart.yaml.

- charts/argo-cd/Chart.yaml
- charts/argo-cd/crds/crd-application.yaml
- charts/argo-cd/crds/crd-project.yaml
This PR makes the schema attributes compatible with `apiextensions.k8s.io/v1` after #541 bumped the version without this adjustment.
Best viewed with whitespace diff [suppressed](https://github.com/argoproj/argo-helm/pull/545/files?w=1).
Checklist:
> fix(argo-cd): Fixes CRD schema.

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/templates/argo-rollouts-deployment.yaml
You can't install 0.4.0 chart, because of k8s validation error
Problem:
https://github.com/argoproj/argo-helm/commit/8baf0d4465e8784fdd0c769d3db000e221e1aab9
Invalid Deployment manifest
```
Error: unable to build kubernetes objects from release manifest: error validating \"\": error validating data: ValidationError(Deployment.spec.template.spec.containers): invalid type for io.k8s.api.core.v1.PodSpec.containers: got \"map\", expected \"array\"\n", "stderr": "Error: unable to build kubernetes objects from release manifest: error validating \"\": error validating data: ValidationError(Deployment.spec.template.spec.containers): invalid type for io.k8s.api.core.v1.PodSpec.containers: got \"map\", expected \"array\"\n", "stderr_lines": ["Error: unable to build kubernetes objects from release …
```
> fix(argo-rollouts): Fix critical deployment schema bug

- charts/argo-cd/Chart.yaml
- charts/argo-cd/values.yaml
The dex image needs to be bumped to at least [v2.23.0](https://github.com/dexidp/dex/releases/tag/v2.23.0) for `staticClients.secretEnv` to work, but why not go to latest. For reference, this is the full config I'm using to have Argo Workflows share the Argo CD Okta SSO connector:
argo-cd/values.yaml:
```yaml
dex:
image:
tag: v2.26.0
env:
- name: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
valueFrom:
secretKeyRef:
name: argo-workflows-sso
key: client-secret
...
server:
config:
dex.config: |
staticClients:
- id: argo-workflows-sso
name: Argo Workflow
redirectURIs:
- https://argo-workflows.mydomain.com/oauth2/callback
secretEnv: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
```
argo/values.yaml:
```yaml
server:
extraArgs:
- --auth-mode=sso
sso:
issuer: https://argo-cd.mydomain.com/api/dex
clientId:
name: …
```
> fix(argo-cd): bump dex image for secretEnv in staticClients to work

- .circleci/chart-testing.yaml
- .circleci/config.yml
- charts/argo-cd/Chart.yaml
- charts/argo-cd/requirements.lock
- charts/argo-cd/requirements.yaml
- charts/argo-cd/values.yaml
* Update argo-cd to 1.7.11
* Move redis to new official repository instead of helm/stable: https://github.com/helm/charts/pull/21567
* Update redis-ha to the last 5.x version of redis (5.0.6)
* Update the bundled redis to 5.0.10 and use the redis alpine image as in https://github.com/argoproj/argo-cd/pull/4767
Checklist:
> feat(argo-cd): Argo CD 1.7.11

- .circleci/config.yml
- CONTRIBUTING.md
- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo/Chart.yaml
- charts/argo/values.yaml
This PR corrects misspellings identified by the [check-spelling action](https://github.com/marketplace/actions/check-spelling).
The misspellings have been reported at https://github.com/jsoref/argo-helm/commit/299fe87c58ad9546213d999ff4059579e55d5cc5#commitcomment-46477627
The action reports that the changes in this PR would make it happy: https://github.com/argoproj/argo-helm/commit/f3179dd57732fb4cac60ef10ccfdb6efea1f44d9
Note: this PR does not include the action. If you're interested in running a spell check on every PR and push, that can be offered separately.
---
Checklist:
---
I'll update the chart versions once the content changes are deemed acceptable (and probably squash). I leave …
> chore: Spelling

- charts/argo/Chart.yaml
- charts/argo/templates/server-ingress.yaml
- charts/argo/values.yaml
Signed-off-by: Artyom Bakhtin <a@bakhtin.net>
We use `cert-manager` to manage SSL certificates inside the EKS cluster. Depending on the value of `labels` in Ingress object, `cert-manager` selects a matching method to solve HTTP01/DNS01 challenge (https://cert-manager.io/docs/installation/upgrading/upgrading-0.7-0.8/#performing-an-incremental-switch-to-the-new-format).
Adding support for custom `labels` in Server Ingress object to allow it to work with `cert-manager`. Or just in case one needs to add custom labels for some other reason.
Checklist:
> feat: Allow custom labels in Server Ingress

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/templates/crds/analysis-run-crd.yaml
- charts/argo-rollouts/templates/crds/analysis-template-crd.yaml
- charts/argo-rollouts/templates/crds/cluster-analysis-template-crd.yaml
- charts/argo-rollouts/templates/crds/experiment-crd.yaml
- charts/argo-rollouts/templates/crds/rollout-crd.yaml
When trying to install the current version of argo-rollouts charts the error:
```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(CustomResourceDefinition.spec): unknown field "additionalPrinterColumns" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "subresources" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "validation" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "version" in …
```
> fix(argo-rollouts): update argo-rollouts charts to CRD new format

- charts/argo-cd/Chart.yaml
- charts/argo-cd/crds/crd-project.yaml
This fixes #578, which caused by switching of the `AppProject` CRD to the API version `apiextensions.k8s.io/v1`. Under that version Kubernetes [no longer](https://kubernetes.io/blog/2019/06/20/crd-structural-schema/#pruning-don-t-preserve-unknown-fields) stores undeclared fields, which would cause Kubernetes to drop the `status` field when saving the `AppProject` objects. The change adds specification for the `status` field and its subfields.
Checklist:
> feat(argo-cd): Add spec for the status field of AppProject CRD.

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/templates/crds/analysis-run-crd.yaml
- charts/argo-rollouts/templates/crds/analysis-template-crd.yaml
- charts/argo-rollouts/templates/crds/cluster-analysis-template-crd.yaml
- charts/argo-rollouts/templates/crds/rollout-crd.yaml
This Pull request updates the cdr schemas to the current version. It also adds back properties removed from the manifest in https://github.com/argoproj/argo-rollouts/pull/114/files since the validation fails if they are missing on the current API extensions version.
Checklist:
> fix(argo-rollouts): update cdr schema to current version

- charts/argo/Chart.yaml
- charts/argo/templates/workflow-controller-crb.yaml
#530 changed the `cluster-template` `ClusterRoleBinding`s into namespace-scoped `RoleBinding`s when `singleNamespace` is set in values. That change is incorrect as the `cluster-template` role grants permissions on cluster-scoped objects, and binding it with a namespace scoped `RoleBinding` will _not_ grant the subjects the expected permissions. This binding has to be `ClusterRoleBinding`.
Checklist:
> fix(argo): Restore cluster template role binding to be ClusterRoleBinding.

- charts/argo/Chart.yaml
- charts/argo/templates/server-cluster-roles.yaml
- charts/argo/templates/server-crb.yaml
- charts/argo/templates/workflow-controller-cluster-roles.yaml
This is a followup on #593, as the server role binding needs to be cluster scope as well. Thanks to @stefansedich for the catch.
Checklist:
> fix(argo): Restore server cluster-template to be a ClusterRoleBinding.

- charts/argo/Chart.yaml
- charts/argo/templates/workflow-aggregate-roles.yaml
The aggregateable roles need to be `ClusterRoles`, per the Kubernetes [docs](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles).
Checklist:
> fix(argo): @vladlosev Restores aggregated roles to be ClusterRoles.

- charts/argo/Chart.yaml
- charts/argo/templates/workflow-aggregate-roles.yaml
This is quick fix for an issue I introduced in #595. Thanks to @kostas-theo for pointing it out.
Checklist:
> fix(argo): Add missing API version to aggregate roles.

- CODEOWNERS
- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-application-controller/deployment.yaml
> fix(argo-cd): hard coded .selector.matchLabels

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/requirements.lock
- charts/argo-cd/requirements.yaml
This upgrades the redis-ha helm chart to v4.10.4 from v4.10.1.
Changelog: https://github.com/DandyDeveloper/charts/compare/9a334385...a83e96da
The main reason is to fix the kubernetes probes for redis.
We have been hit by an issue similar to https://github.com/bitnami/charts/issues/2441 where the liveness/readiness probes leave lots of zombie processes behind that eventually starve the system from threads and PIDs.
The timeout that wraps the redis-cli call is always left as defunc even though the probes actually succeed.
redis-ha v4.10.4 totally removed the timeout, while everything still works as expected.
The timeout was introduced in https://github.com/helm/charts/pull/11355 as a workaround for https://github.com/kubernetes/kubernetes/pull/58925 which has been fixed a long time ago. …
> fix(argo-cd): Upgrade redis-ha to v4.10.4

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-configs/argocd-cm.yaml
- charts/argo-cd/values.yaml
Checklist:
* Can someone provide more context here?
---
I need to wrap the `argo-cd` chart in a parent chart to enable templating of specific items in the `argocd-cm` and `argocd-secret` resources. The Secret template has a flag that supports this, but the CM does not. Adding this flag provides a simple solution to my problem. 
Please let me know if you folks need anything else -- Thanks!
> feat(argo-cd): adds configEnabled flag to allow parent chart to own CM

- charts/argo-cd/Chart.yaml
- charts/argo-cd/crds/crd-project.yaml
When creating a tokens, the respective metadata is not being keeped on the respective AppProject, this is happening due to the AppProject CRD not defining correctly the status.jwtTokensByRole object. This MR fixes it.
Checklist:
> fix(argo-cd): appproject crd status tokens items

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/_helpers.tpl
- charts/argo-cd/templates/redis/service.yaml
Found a missing usage of the label templating function introduced in #627.
While here I also noticed, that the whitespace trimming could be improved with this:
```diff
--- a/charts/argo-cd/templates/_helpers.tpl
+++ b/charts/argo-cd/templates/_helpers.tpl
@@ -133,7 +133,7 @@ Selector labels
{{- define "argo-cd.selectorLabels" -}}
{{- if .name -}}
app.kubernetes.io/name: {{ include "argo-cd.name" .context }}-{{ .name }}
-{{- end }}
+{{ end -}}
app.kubernetes.io/instance: {{ .context.Release.Name }}
{{- if .component }}
app.kubernetes.io/component: {{ .component }}
```
This is especially useful, when using the function without defining the `name` parameter. This resulted in an additional empty newline.
Checklist:
Changes are automatically published when merged to `master`. They are not …
> fix(argo-cd): One occurrence of label templating was missing

- charts/argo-cd/.helmignore
- charts/argo-cd/Chart.yaml
This should fix #585:
```bash
$ helm dependency update
Getting updates for unmanaged Helm repositories...
...Successfully got an update from the "https://dandydeveloper.github.io/charts/" chart repository
(..)
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading redis-ha from repo https://dandydeveloper.github.io/charts/
Deleting outdated charts
$ helm template .
Error: found in Chart.yaml, but missing in charts/ directory: redis-ha
```
Ref:
- https://github.com/argoproj/argo-helm/issues/585
- https://helm.sh/docs/chart_template_guide/helm_ignore_file/
Is there a reason why you deleted this file completely two years ago, @jdeprin / @alexec? (https://github.com/argoproj/argo-helm/pull/129)
Checklist:
Changes are automatically published when merged to `master`. They are not …
> fix(argo-cd): only exclude *.tgz in the top-level chart dir

- charts/argo-events/Chart.yaml
- charts/argo-events/crds/eventbus-crd.yml
- charts/argo-events/crds/eventsource-crd.yml
- charts/argo-events/crds/sensor-crd.yml
- charts/argo-events/templates/eventbus-crd.yaml
- charts/argo-events/templates/eventsource-crd.yaml
- charts/argo-events/templates/sensor-crd.yaml
This is to fix the issue which I raised here: https://github.com/argoproj/argo-helm/issues/599
Checklist:
> fix(argo-events): spec.versions.schema Required for argo-events crds

- charts/argo/Chart.yaml
- charts/argo/templates/workflow-controller-deployment.yaml
- charts/argo/values.yaml
Hi,
this PR add support of extraArgs to controller deployment, for cases like this: https://github.com/argoproj/argo-workflows/blob/master/docs/managed-namespace.md (`--managed-namespace` flag)
Checklist:
> fix(argo): add extraArgs to controller deployment

- charts/argo/Chart.yaml
- charts/argo/templates/server-cluster-roles.yaml
argo-server permission has been fixed in https://github.com/argoproj/argo-workflows/pull/3929, not yet reflected in here.
Checklist:
> fix(argo): Fix argo-server webhook permission

- .github/pull_request_template.md
As I opened several PRs in the past, I wondered what CLA stands for. As described in the [project news](https://github.com/argoproj/argoproj#news), Argo Project has moved from the CLA to the DCO and this might be a leftover from that time:
> ## News
> 
> Argo Project is moving from CLA to DCO as a simpler way to track contributions.
> Argo Project has moved from the CLA to the DCO.
> * https://github.com/apps/dco/
> 
> Please start signing off your contributions by doing ONE of the following:
> Please signoff your contributions by doing ONE of the following:
> * Use `git commit -s ...` with each commit to add the signoff or
> * Manually add a `Signed-off-by: Your Name <your.email@example.com>` to each commit message.
> 
> The email address must match your primary GitHub email. You do NOT …
> chore: Update PR template to include notes on DCO

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-configs/cluster-secrets.yaml
- charts/argo-cd/values.yaml
I thought it would be a good idea to implement _External Cluster Credentials/Clusters_ from [Declarative Setup](https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/#clusters)
I was not sure, where to put the config in the values. (Also opened an issue here: https://github.com/argoproj/argo-helm/issues/631)
Checklist:
> feat(argo-cd): Add ability to handle cluster credentials

- charts/argo-applicationset/Chart.yaml
- charts/argo-applicationset/README.md
- charts/argo-applicationset/ci/default-values.yaml
- charts/argo-applicationset/ci/leader-election-values.yaml
- charts/argo-applicationset/templates/rbac.yaml
Signed-off-by: Matteo Ruina <matteo.ruina@gmail.com>Note on DCO:
- Fix https://github.com/argoproj/argo-helm/pull/650#issuecomment-818881677
- Add testing values to use with `ct`
- Update the documentation 
`ct` output at https://gist.github.com/maruina/4834393a87458127209fe66fa83fabeb
Checklist:
> fix(argo-applicationset): Fix leader election rbac

- charts/argo-cd/Chart.lock
- charts/argo-cd/Chart.yaml
> Issue #675: Update redis-ha helm chart to 4.10.4

- charts/argo-events/Chart.yaml
- charts/argo-events/templates/eventbus-controller-deployment.yaml
- charts/argo-events/templates/eventsource-controller-deployment.yaml
- charts/argo-events/templates/sensor-controller-deployment.yaml
- charts/argo-events/values.yaml
This change adds support for annotating pods generated by the main Argo Events controllers with custom annotations. This is needed, for example, for interacting with third party services collecting data from them.
Checklist:
> feat(argo-events): Add support for pod annotations.

- charts/argo/Chart.yaml
- charts/argo/values.yaml
Some referenced URL were out dated due to [argo-workflow](https://argoproj.github.io/argo-workflows/) website's upgrade, so I fixed them. 😄 
Signed-off-by: Yuki Kitakata <yuki.kita22@gmail.com>
Note on DCO:
Checklist:
> chore(argo): fix referenced URL

- charts/argo-ci/Chart.yaml
- charts/argo-ci/README.md
- charts/argo-ci/requirements.lock
- charts/argo-ci/requirements.yaml
Signed-off-by: Oliver Bähler <oliverbaehler@hotmail.com>
Since this chart is no longer used we officially should deprecate it. Therefore we can also exclude it for the new lint workflow. Last change has been 8 months ago. 
Note on DCO:
Checklist:
> feat(argo-ci): deprecate argo-ci helm chart

- charts/argo-events/Chart.yaml
- charts/argo-events/templates/argo-events-cluster-roles.yaml
Finishing off the work started here (https://github.com/argoproj/argo-helm/pull/667) to fix https://github.com/argoproj/argo-helm/pull/666
Checklist:
> fix(argo-events): add missing status resources in rbac clusterrole

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-configs/cluster-secrets.yaml
- charts/argo-cd/values.yaml
Allow custom labels on remote cluster for usage with AppicationSet cluster generator label selector
https://argocd-applicationset.readthedocs.io/en/stable/Generators/#label-selector
Note on DCO:
Checklist:
> feat(argo-cd): Add label to cluster-secrets for usage with appSet cluster selector

- charts/argo-events/Chart.yaml
- charts/argo-events/templates/eventbus-controller-deployment.yaml
- charts/argo-events/templates/eventsource-controller-deployment.yaml
- charts/argo-events/templates/sensor-controller-deployment.yaml
- charts/argo-events/values.yaml
> feat(argo-events): add priorityClassName and podLabels options

- charts/argo/Chart.yaml
- charts/argo/templates/NOTES.txt
Fix wrong MinIO service name in argo/templates/NOTES.txt
Signed-off-by: Ryan Lo <lowc1012@gmail.com>
Note on DCO:
Checklist:
> chore(argo): Fix service name in argo/templates/NOTES.txt

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/templates/crds/analysis-run-crd.yaml
- charts/argo-rollouts/templates/crds/analysis-template-crd.yaml
- charts/argo-rollouts/templates/crds/cluster-analysis-template-crd.yaml
- charts/argo-rollouts/templates/crds/experiment-crd.yaml
- charts/argo-rollouts/templates/crds/rollout-crd.yaml
Follows https://github.com/argoproj/argo-rollouts/pull/1069 and fixes #604
This is just following along from prior work in the argo-rollouts repository to ensure that upgrades can happen between prior CRD API versions.
Checklist:
> fix: spec.preserveUnknownFields must be set to false to allow upgrades from v1beta1

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/templates/argo-rollouts-clusterrole.yaml
- charts/argo-rollouts/templates/argo-rollouts-deployment.yaml
- add destinationrule to clusterrolebinding
Signed-off-by: Hui Kang <hui.kang@salesforce.com>
> feat (argo-rollout): add resources to argo-rollouts deployment

- charts/argo-events/Chart.yaml
- charts/argo-events/values.yaml
Updating helm chart to version 1.3.1 of argo-events.
Signed-off-by: Alec Rajeev <alecinthecloud@gmail.com>
Note on DCO:
Checklist:
> chore(argo-events): update argo-events to app version 1.3.1

- charts/argo-cd/Chart.lock
- charts/argo-cd/Chart.yaml
Signed-off-by: Aniek Gul <aniekgul@hotmail.com>
This brings the redis-ha version in-line with what [argocd is using](https://github.com/argoproj/argo-cd/blob/master/manifests/ha/base/redis-ha/chart/requirements.yaml).
Checklist:
> chore(argo-cd): upgrade redis-ha version to 4.12.14

- CODEOWNERS
According to documentation, the pattern `/path/*` only allows approval on this level:
~~~
docs/*  docs@example.com
/docs/ @doctocat
~~~
Ref: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners#codeowners-syntax
Note on DCO:
Checklist:
> chore: remove '*' in CODEOWNERS to allow recursive approvals

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-application-controller/servicemonitor.yaml
- charts/argo-cd/templates/argocd-repo-server/servicemonitor.yaml
- charts/argo-cd/templates/argocd-server/servicemonitor.yaml
- charts/argo-cd/templates/dex/servicemonitor.yaml
- charts/argo-cd/values.yaml
My production environment is using 60s scrape interval:
- Some charts has no defaults(so used default value in prometheus and it is just works)
- Some charts has 30s defaults in values files
- This chart has hardcoded values in manifests, so no chance to use 60s interval
It is better to have no defaults at all, ServiceMonitor will be fallback to scrapeInterval from defined prometheus configuration, so one place to change scrape intervals and only one reason to add it manually - to override defaults if it really need
Checklist:
```
helm template test-release -n test-namespace -f .\values.yaml  . > templated.yaml
```
```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata: …
```
> feat(argo-cd): Extract ServiceMonitor interval to values

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
Fix typo introduced in https://github.com/argoproj/argo-helm/pull/743
Note on DCO:
Checklist:
> fix(argo-cd): envFrom in repoServer

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/templates/argo-rollouts-deployment.yaml
> fix(argo-rollouts): Removed duplicated resources declaration

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/certificate.yaml
- charts/argo-cd/values.yaml
Fixes #756
The TLS secret created by cert-manager has the same secret name as the argocd secret. This should not work. This PR will fix it. 
> fix(argo-cd): Fix duplicate secret

- charts/argo-cd/Chart.yaml
- charts/argo-cd/values.yaml
This follows upstream latest version and bumps default version of image tag used.
Note on DCO:
Checklist:
> feat(argo-cd): Bump default version to v2.0.3

- charts/argo-cd/Chart.yaml
- charts/argo-cd/values.yaml
We missed the update to dex v2.27.0 in the argo-cd release 1.8.2: https://github.com/argoproj/argo-cd/releases/tag/v1.8.2
The update to 2.27.0 should reduce the security issue(s):
Ref:https://artifacthub.io/packages/helm/argo/argo-cd?modal=security-report
Note on DCO:
Checklist:
> fix(argo-cd): Update dex to v2.27.0

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/README.md
- charts/argo-rollouts/templates/_helpers.tpl
- charts/argo-rollouts/templates/argo-rollouts-aggregate-roles.yaml
- charts/argo-rollouts/templates/argo-rollouts-clusterrole.yaml
- charts/argo-rollouts/templates/argo-rollouts-clusterrolebinding.yaml
- charts/argo-rollouts/templates/argo-rollouts-deployment.yaml
- charts/argo-rollouts/templates/argo-rollouts-metrics-service.yaml
- charts/argo-rollouts/templates/argo-rollouts-role.yaml
- charts/argo-rollouts/templates/argo-rollouts-rolebinding.yaml
- charts/argo-rollouts/templates/argo-rollouts-sa.yaml
- charts/argo-rollouts/templates/argo-rollouts-service-monitor.yaml
- charts/argo-rollouts/templates/crds/analysis-run-crd.yaml
- charts/argo-rollouts/templates/crds/analysis-template-crd.yaml
- charts/argo-rollouts/templates/crds/cluster-analysis-template-crd.yaml
- charts/argo-rollouts/templates/crds/experiment-crd.yaml
- charts/argo-rollouts/templates/crds/rollout-crd.yaml
- charts/argo-rollouts/values.yaml
Resolves #740 
This also resolves #754 since we now use the template function `"argo-rollouts.fullname"` whenever possible.
Note on DCO:
Checklist:
> feat(argo-rollouts): Update manifests for v1.0.1

- charts/argo-events/Chart.yaml
- charts/argo-events/values.yaml
Upstream is changing to `quay.io`:
https://github.com/argoproj/argo-events/blob/master/manifests/base/sensor-controller/sensor-controller-deployment.yaml#L21
Let's change this in the chart default too.
Note on DCO:
Checklist:
> chore(argo-events): Use container images from quay.io

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/README.md
- charts/argo-rollouts/templates/argo-rollouts-metrics-service.yaml
- charts/argo-rollouts/templates/argo-rollouts-service-monitor.yaml
- charts/argo-rollouts/values.yaml
With the upgrade to version 1.0.0 of the chart, a regression was introduced.
Before, even if you had not installed in your cluster the CoreOS Service Monitor, the chart would allow you to expose a metrics service for your metrics provider to read.
Now, if you do not set `controller.metrics.serviceMonitor.enabled` on your release, the service will not be created, breaking metric exports.
But, if you set `controller.metrics.serviceMonitor.enabled`, it will attempt to create a `ServiceMonitor.monitoring.coreos.com/v1` resource, which, if you do not have it installed in your cluster, breaks the release.
This makes it so the metrics Service is always deployed, allowing people who do not have the CoreOS ServiceMonitor to also make use of these metrics.
Note on DCO:
If the DCO action in the …
> fix(argo-rollouts): Allow metrics service without ServiceMonitor

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/values.yaml
In this PR https://github.com/argoproj/argo-helm/pull/769 , `fullnameOverride` was added but it was not defined on `values.yaml`, so I added it. 🙋 
Note on DCO:
Checklist:
> docs(argo-workflows): Add missing value on values.yaml

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/_helpers.tpl
- charts/argo-workflows/templates/server/server-ingress.yaml
- charts/argo-workflows/values.yaml
This PR fixes #794.
Checklist:
> fix(argo-workflows): use template for ingress .Capabilities

- charts/argo-cd/Chart.yaml
- charts/argo-cd/values.yaml
Signed-off-by: Alex Andrews <alias-dev@protonmail.com>
Note on DCO:
Checklist:
> fix(argo-cd): fix missing colon in example service definitions

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/controller/workflow-controller-deployment.yaml
- charts/argo-workflows/values.yaml
> chore(argo-workflows): update workflows version to most 3.0.7

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-repo-server/servicemonitor.yaml
This PR fixes a typo in the servicemonitor.yaml for the repo server component. Probably due to copy paste errors.
Note on DCO:
Checklist:
> fix(argo-cd): Typo in repo server service monitor

- CODEOWNERS
Using correct pattern to match all Chart subfolder (https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-code-owners#codeowners-syntax). Currently not matching all Codeowners.
Note on DCO:
Checklist:
> chore: Fix CODEOWNERS syntax

- .github/workflows/lint-and-test.yml
It seems that the current KinD action (v1.1.0) is broken for an unknown reason. The KinD node is in **NotReady** state forever and therefore no pods can be scheduled.
```logs
Events:
Type     Reason            Age                From               Message
----     ------            ----               ----               -------
Warning  FailedScheduling  70s (x8 over 10m)  default-scheduler  0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
```
Example CI jobs which currently fail:
- https://github.com/argoproj/argo-helm/pull/797/checks?check_run_id=2987333533
(https://github.com/argoproj/argo-helm/pull/797)
- https://github.com/argoproj/argo-helm/pull/812/checks?check_run_id=2975847989 …
> chore(chart-testing-action): Update components

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-configs/argocd-gpg-keys-cm.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/values.yaml
Resolves #457
Note on DCO:
Checklist:
> feat(argo-cd): Add ability to manage GnuPG keys

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/ingress-grpc.yaml
- charts/argo-cd/templates/argocd-server/ingress.yaml
- charts/argo-cd/values.yaml
Resolves #821
Modern GKE versions only accept ImplementationSpecific as pathType for the ingress resource, so here we added a new value for the pathType which can be used to set pathType on demand, the default value is still Prefix for backward compatability
Note on DCO:
Checklist:
> feat(argo-cd): Add pathType value to ingress

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/templates/argo-rollouts-clusterrole.yaml
- charts/argo-rollouts/templates/argo-rollouts-role.yaml
With the addition of notification-engine support on Argo Rollouts, the app now needs read access to configmaps
Currently rollouts fail on master tag due to lack of configmap read access
Note on DCO:
Checklist:
> fix(argo-rollouts): Add ConfigMap read access to support notification-engine

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/_helpers.tpl
- charts/argo-cd/templates/redis/deployment.yaml
- charts/argo-cd/templates/redis/serviceaccount.yaml
- charts/argo-cd/values.yaml
Resolves #809
While here, I noticed that there might exist clashing ServiceAccount resources when the default names of `controller`, `dex`, `server` and `repoServer` are cleared. This is an edge case but its fixed now :-)
Note on DCO:
Checklist:
> fix(argo-cd): Add ServiceAccount for redis

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
Related to discussion in PR https://github.com/argoproj/argo-helm/pull/828
Checklist:
> docs(argo-cd): Upgrading notes for ServiceAccount change in 3.8.1

- index.yaml
The chart "argo-lite" does not exist as source anymore. The intent for this PR is to don't list this old chart on Artifact Hub anymore.
IMHO updating the index file manually would be the simplest trick to do this.
> chore: Flag argo-lite chart as deprecated to remove it from Artifact Hub

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/controller/workflow-controller-cluster-roles.yaml
- charts/argo-workflows/templates/controller/workflow-controller-config-map.yaml
Signed-off-by: kobejn-jb jakubbielawski89@gmail.com
This PR comes with the following changes:
It allows for the controller to work with InstanceID while using leases
It fixes a controller Role/ClusterRole, now it allows to read and update leases with names ending with -<your instance ID> when controller is set to use InstanceID
This PR intends to solve the following use case. In case when controller is set to use InstanceID controller role does not allow to get/watch/update/path/delete leases with names different from "workflow-controller-lease" and "workflow-controller-lease" but controller tries to use lease named "workflow-controller-lease-<provided InstanceID>". Now trying to use controller with InstanceID it results with error:
`E0713 13:43:58.014735       1 leaderelection.go:325] …
> fix(argo-workflows): Fix controller Role/ClusterRole to work with InstanceID

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/values.yaml
Remove old default executor serviceaccount unused configuration entries.
> fix(argo-workflows): remove old default init service account

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/crds/argoproj.io_workflows.yaml
This is the implementation of the accepted solution to this argo-workflows issue: https://github.com/argoproj/argo-workflows/issues/6256
The solution comes from https://github.com/kubernetes/kubernetes/issues/102749 and solves the problem (in Kubernetes v1.19.10+ and v1.20+) of pod completing and argo not being able to retrieve their updates statuses, instead giving:
```
Error updating workflow: Timeout: request did not complete within requested timeout 34s Timeout
```
Signed-off-by: kostas-theo <ktheo@oneconcern.com>
Note on DCO:
Checklist:
Changes are automatically published when merged to …
> fix(argo-workflows): pod status pending issue

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/values.yaml
Small documentation change of the values.yaml of the argo workflows chart.
Checklist:
> docs: Rename argocd references to argoworkflows in workflow chart

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
Note on DCO:
Checklist:
* [X ] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#versioning)
* [X ] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#changelog).
* [X ] Any new values are backwards compatible and/or have sensible default.
* [X ] I have signed off all my commits as required by …
> feat(argo-cd): Bump default version to v2.0.5

- index.yaml
In recent PR https://github.com/argoproj/argo-helm/pull/844 the changelog was not updated. To fulfil what was requested in issue #735 we update the changelog in post :-)
Note on DCO:
Checklist:
> fix(argo-cd): Update changelog for recent PR #844

- charts/argo-cd/Chart.yaml
- charts/argo-cd/values.yaml
Enable `server.staticAssets.enabled` by default (was disabled in #846). It looks like neither https://github.com/argoproj/argo-cd/commit/561452ac943a8f83e17c66eb72200f4a66ee3ae3 or https://github.com/argoproj/argo-cd/commit/e68618d168b1eeeec1b60af562922d5791197e02 have made it into a release yet so the default should stick to enabled for now.
Signed-off-by: Lucas Bickel <lucas.bickel@adfinis.com>
Note on DCO:
Checklist:
Does not address  #843 but adresses all the comments from people getting hit by …
> fix(argo-cd): re-enable not yet deprecated staticassets flag

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/alb-grpc-service.yaml
To use AWS Load Balancer Controller, you need to set the service type as NodePort.
Note on DCO:
Checklist:
> fix(argo-cd): Set type of service for gRPC as NodePort.

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/templates/argo-rollouts-deployment.yaml
- charts/argo-rollouts/values.yaml
Signed-off-by: Hui Kang <hui.kang@salesforce.com>
Note on DCO:
Checklist:
> fix(argo-rollouts): Add missing liveness and readiness probe

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/controller/workflow-controller-deployment.yaml
- charts/argo-workflows/templates/server/server-deployment.yaml
- charts/argo-workflows/values.yaml
My use-case for this is using persistence with a GCP CloudSQL database, using the sidecar pattern for the cloud-sql-proxy
Note on DCO:
Checklist:
> feat(argo-workflows): Add support for extra containers in server & controller deployment

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-server/alb-grpc-service.yaml
- charts/argo-cd/values.yaml
The Service Type needed depends on the annotation `alb.ingress.kubernetes.io/target-type` on the ingress. This PR allows users to set the service type to Cluster IP if they are using IP Mode for the ingress. By default the target type is instance and requires the service to be of type NodePort.
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/how-it-works/#ingress-traffic
Checklist:
> fix(argo-cd): AWS GRPC Service Type

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/_helpers.tpl
Fixes #722
Note on DCO:
Checklist:
> fix(argo-cd): Fix (full)nameOverride redis-ha sub-chart

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/values.yaml
A quick and tiny PR to fix ArgoCD Repo Server failing to due the entrypoint script rename on v2.1.0
Per @davidkarlsen suggestion, I've removed entrypoint.sh from the command block to defer to the entrypoint defined in the Dockerfile 
This PR also removes the `--staticassets` conditional block I introduced for an older ArgoCD server release
(Creating this PR to unblock anyone trying to use v.2.1.0, noticed #884 was inactive for the past 2 days)
Note on DCO:
Checklist:
> fix(argo-cd): Remove ArgoCD repo server entrypoint script from command block and drop --staticassets field 

- charts/argocd-applicationset/Chart.yaml
- charts/argocd-applicationset/crds/crd-applicationset.yaml
- charts/argocd-applicationset/values.yaml
Upgrade to latest application set version - relates to https://github.com/argoproj/argo-helm/pull/885 but upgrades CRDs to support new generators and fixes image repository.
> feat(argocd-applicationset): Upgrade application-set to version 0.2.0

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/dex/service.yaml
- charts/argo-cd/values.yaml
I'm parameterizing dex service ports for istio-ingress. With original 'http' setting it's returning 403.
More info: https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/#explicit-protocol-selection
Note on DCO:
Checklist:
> feat(argo-cd): Parameterizing dex ports names due to istio 403 errors

- charts/argocd-notifications/Chart.yaml
- charts/argocd-notifications/templates/configmap.yaml
- charts/argocd-notifications/templates/secret.yaml
Resolves https://github.com/argoproj/argo-helm/issues/779 as a workaround.
Support of custom names can be added after 1.12.0 release via `config-map-name` and `secret-name` switches.
Note on DCO:
Checklist:
> fix(argocd-notifications): Use correct names for ConfigMap and Secret

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/controller/workflow-controller-config-map.yaml
- charts/argo-workflows/values.yaml
Hi,
This PR adds the controller `containerRuntimeExecutors` params to the configuration map. In my case I needed it to partially enable the Emissary executor on some workflows according to the [upgrade guide](https://github.com/argoproj/argo-workflows/blob/master/docs/upgrading.md#ab361667a-featcontroller-emissary-executor--4925).
Default value does not change the current behaviour. However, a commented version of the documentation has been linked. Don't know whether or not you will find it useful.
Thanks in advance for considering this change.
Note on DCO:
Checklist:
Changes are automatically …
> feat(argo-workflows): Add controller containerRuntimeExecutors param to configmap

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-application-controller/deployment.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/templates/dex/deployment.yaml
- charts/argo-cd/templates/redis/deployment.yaml
`mergeOverwrite` is in-place first args object.  
Applying this function to `.Values` object replaces the struct.
sprig function template has  `deepCopy` funtion for to solve this problem.
https://github.com/Masterminds/sprig/issues/188
---
Note on DCO:
Checklist:
> fix(argo-cd): global podLabels/podAnnotations object unexpected merge

- charts/argocd-image-updater/Chart.yaml
- charts/argocd-image-updater/templates/deployment.yaml
Resolve real problem of https://github.com/argoproj/argo-helm/pull/931
Checklist:
> fix(argocd-image-updater): Add scratch space for /tmp

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/templates/_helpers.tpl
We are using `{{default .Chart.AppVersion .Values.controller.image.tag}}` for image tag in [deployment.yaml](https://github.com/argoproj/argo-helm/blob/master/charts/argo-rollouts/templates/argo-rollouts-deployment.yaml#L34).  But in `_helpers.tpl` we are using `app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}` causing two out of sync information about the application's version
> fix(argo-rollouts): use `image.tag` in labels if provided

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-application-controller/deployment.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/templates/dex/deployment.yaml
- charts/argo-cd/templates/redis/deployment.yaml
- charts/argo-cd/values.yaml
Signed-off-by: Sander van Schie <sandervanschie@gmail.com>
Note on DCO:
Checklist:
Pod Topology Spread Constraints can be useful when you want to enforce spread of pods, but want to spin up more pods than you have different topologies. For example if you want to spread 6 pods across your 3 availability zones, it will place 2 in every zone. With podAntiAffinity it would only be able to spin up 3 pods (when using requiredDuringSchedulingIgnoredDuringExecution).
I implemented some logic for the …
> feat(argo-cd): Add support for topologySpreadConstraints

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/README.md
- charts/argo-rollouts/templates/crds/analysis-run-crd.yaml
- charts/argo-rollouts/templates/crds/analysis-template-crd.yaml
- charts/argo-rollouts/templates/crds/cluster-analysis-template-crd.yaml
- charts/argo-rollouts/templates/crds/experiment-crd.yaml
- charts/argo-rollouts/templates/crds/rollout-crd.yaml
- charts/argo-rollouts/values.yaml
This reduces risk when upgrading the controller by keeping CRD's by default. This will leave Rollouts in a degraded state but at least they will keep serving.
Scenario this avoids:
- Incompatible upgrade needed between major versions requiring 'helm uninstall'
- `helm uninstall` is performed and ALL the rollouts on the cluster get deleted due to CRD deletion
This should be backwards compatible as this keeps the CRD managed (unlike hook annotations).
Feature also provides an opt-out if needed.
Note on DCO:
Checklist:
Changes are automatically published when merged to `master`. They are not …
> feat(argo-rollouts): Default to keeping CRD's on helm uninstall

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/controller/workflow-controller-deployment.yaml
- charts/argo-workflows/values.yaml
Here, we scrape every pod that has a .*-metrics port here
But the helm chart is locked to `metrics` which our Prometheus doesn't see
This PR will make it configurable with a default value of `metrics`
Checklist:
> feat(argo-workflows): Allow setting the metrics port name

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/feature_request.yaml
This helps to enhance the issue quality from the community as the related helm chart is now a required input.
> chore: Require related chart name in issues

- charts/argocd-applicationset/Chart.yaml
- charts/argocd-applicationset/README.md
- charts/argocd-applicationset/templates/deployment.yaml
- charts/argocd-applicationset/values.yaml
To be forward-compatible, I'm not add args.logLevel, instead adding extraArgs to support all arguments out of the box
Note on DCO:
Checklist:
> feat(argocd-applicationset): Add extraArgs

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/ci/default-values.yaml
- charts/argo-rollouts/ci/enable-dashboard-values.yaml
- charts/argo-rollouts/ci/test-values.yaml
These two tests runs independently:
1. Install with default values
2. Install wich dashboard enabled
Note on DCO:
Checklist:
> chore(argo-rollouts): Define two separate tests

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
Signed-off-by: keiSunagawa <keisunagawa.git@icloud.com>
Note on DCO:
Checklist:
> fix(argo-cd): repoServer.extraContainers values variable unused

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/README.md.gotmpl
Details:
just fix typo in the readme in the  `## Installing the Chart` part
Checklist:
> fix(argo-cd): helm3 install does not have flag --name

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
We are running argo with `containerSecurityContext.readOnlyRootFilesystem` set to `true`.
However, a bunch of things are not loading on the ArgoCD Dashboard (logs, events, manifests, ...) when doing so.  When looking at the argocd server logs, we found the following error:
```
[Errno 30] Read-only file system: '/home/argocd/.aws'
{"error":"Get \"https://{REDACTED}.eks.amazonaws.com/api/v1?timeout=32s\": getting credentials: exec: executable aws failed with exit code 255","grpc.code":"Unknown","grpc.method":"DeleteResource","grpc.service":"application.ApplicationService","grpc.start_time":"2021-10-28T20:31:02Z","grpc.time_ms":495.752,"level":"error","msg":"finished unary call with code Unknown","span.kind":"server","system":"grpc","time":"2021-10-28T20:31:02Z"}
```
The reason is that …
> fix(argo-cd): Make argocd-server /home/argocd/.aws writeable when using readOnlyRootFilesystem=false security context

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/README.md
- charts/argo-rollouts/templates/controller/deployment.yaml
- charts/argo-rollouts/values.yaml
Our local metrics setup uses an extra container for the controller
deployment. Adding this in case others have a similar use case.
Signed-off-by: Brian Johnson <b2jrock@gmail.com>
Note on DCO:
Checklist:
> feat(argo-rollouts): Allow additional containers in controller deployment

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/controller/workflow-aggregate-roles.yaml
- charts/argo-workflows/templates/controller/workflow-controller-cluster-roles.yaml
Closes #997 
Signed-off-by: Paul Ayling <paulayling.dev@gmail.com>
Note on DCO:
Checklist:
> fix(argo-workflows): Add missing WorkflowTasksets RBAC to controller

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-application-controller/deployment.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/templates/dex/deployment.yaml
- charts/argo-cd/templates/redis/deployment.yaml
- charts/argo-cd/values.yaml
Signed-off-by: Mark Pim <j.mark.pim@gmail.com>
This adds support for custom initContainers for all pods, not just the repo-server. I think giving users control over initContainers for all deployments adds some handy flexibility at a low cost, hopefully you agree!
My particular use case, for the record, is we have a custom K8s auth provider for our clusters, and so I need to deploy that auth provider binary to the Application Controller and Server pods, so that it's available in the container when ArgoCD attempts to connect to the remote clusters. So far I've been building a custom ArgoCD image containing our binary, but that makes the process of upgrading ArgoCD more work, and so copying it at runtime via an initContainer would simplify that.
---
Checklist:
Changes are automatically …
> feat(argo-cd): support initContainers on all pods

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/crds/crd-extension.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/extensions-rolebinding.yaml
- charts/argo-cd/templates/argocd-server/extensions.yaml
- charts/argo-cd/templates/argocd-server/extentions-role.yaml
- charts/argo-cd/values.yaml
This MR is intended to add support for ArgoCD extension, closes https://github.com/argoproj/argo-helm/issues/971
Note on DCO:
Checklist:
> feat(argo-cd): Add support for extension

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/values.yaml
Added ability to set up the argocd-extensions resources.
Signed-off-by: Yevhen Luhovtsov <yevhen.luhovtsov@intapp.com>
Note on DCO:
Checklist:
> feat(argo-cd): Add support for argocd-extensions resources

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/values.yaml
- charts/argocd-notifications/Chart.yaml
Hello,
The recent version pushed a change that introduced a second `intiContainers` entry in the `deployment.yaml` file.
There should be only one entry in this file. This PR merges them into one section. Otherwise, this file is not valid according to the YAML spec and should not work in setups that already utilize init containers.
https://github.com/argoproj/argo-helm/blob/6d872cb02fff53644546f0dfe3197bbad2fa2f88/charts/argo-cd/templates/argocd-repo-server/deployment.yaml#L37-L47
https://github.com/argoproj/argo-helm/blob/6d872cb02fff53644546f0dfe3197bbad2fa2f88/charts/argo-cd/templates/argocd-repo-server/deployment.yaml#L198-L200
Note on DCO:
If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO …
> fix(argo-cd): Merge duplicate initContainer entries introduced in 3.29.0

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/values.yaml
Revert on parametrising copyUtil iniContainer in #1058 due this is default in upstream Kustomize manifests.
---
Note on DCO:
Checklist:
> fix(argo-cd): Revert initContainers copyUtil param

- charts/argo-cd/Chart.yaml
- charts/argo-cd/crds/crd-extension.yaml
The CRD was removed by mistake in https://github.com/argoproj/argo-helm/pull/1055
---
Note on DCO:
Checklist:
> fix(argo-cd): Add ArgoCDExtension CRD again

- charts/argo-rollouts/Chart.yaml
Argo Rollouts Releasenotes: https://github.com/argoproj/argo-rollouts/releases/tag/v1.1.1
Note on DCO:
Checklist:
> fix(argo-rollouts): bump to v1.1.1

- charts/argocd-image-updater/Chart.yaml
> fix(argocd-image-updater): Update to app version v0.11.2

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/extra-manifests.yaml
- charts/argo-cd/values.yaml
Signed-off-by: Nick Fisher <nxf5025@gmail.com>
By adding a secretProviderClass object to the Argo CD helm chart we are able to mount secrets (such as our oidc config) on the fly by leveraging the Secrets Store CSI Driver.
Documentation can be found here: https://github.com/kubernetes-sigs/secrets-store-csi-driver
Note on DCO:
Checklist:
> feat(argo-cd): Added ability to deploy extra K8s manifests

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
Follow upstream releases and bump Argo-CD to v2.2.3 and Redis to v6.2.6.
Note on DCO:
Checklist:
> feat(argo-cd): Bump argo-cd to v2.2.3 and Redis to v6.2.6

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
Sync with upstream manifests.
Related upstream issues:
- https://github.com/argoproj/argo-cd/pull/7162
- https://github.com/argoproj/argo-cd/issues/7144
---
Note on DCO:
Checklist:
> fix(argo-cd): Add custom volume as Helm working dir

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/templates/controller/workflow-controller-servicemonitor.yaml
- charts/argo-workflows/values.yaml
> feat(argo-workflows): argo workflows chart to allow set the namespace of Prometheus ServiceMonitor.

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-configs/applications.yaml
- charts/argo-cd/templates/argocd-configs/projects.yaml
Convert manifests of `kind: List` to dashes separated documents
Why?
- > Note that kubectl and other tools sometimes output collections of resources as kind: List. Keep in mind that kind: List is not part of the Kubernetes API; it is exposing an implementation detail from client-side code in those tools, used to handle groups of mixed resources.
> Source: https://github.com/chrisnegus/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#types-kinds
- Consistent usage in our repository
Ref:
- https://github.com/bitnami/charts/issues/4559
- https://github.com/kubernetes/kubectl/issues/984
- https://github.com/kubernetes/community/pull/5903
- https://github.com/helm/helm/issues/8615
**Note for the reviewer:** Use "Hide whitespace" when diffing the manifests.
---
Note …
> chore(argo-cd): Convert manifests of 'kind: List'

- charts/argo-cd/Chart.yaml
The updated Argo CD contains the fix for [CVE-2022-24348](https://apiiro.com/blog/malicious-kubernetes-helm-charts-can-be-used-to-steal-sensitive-information-from-argo-cd-deployments/).
* [release notes](https://github.com/argoproj/argo-cd/releases/tag/v2.2.4)
Signed-off-by: Lucas Bickel <lucas.bickel@adfinis.com>
Note on DCO:
Checklist:
> fix(argo-cd): Update to Argo-CD v2.2.4

- charts/argo-cd/Chart.yaml
Fixes a regression wrt resolving symlinked value files.
- [release notes](https://github.com/argoproj/argo-cd/releases/tag/v2.2.5)
- https://github.com/argoproj/argo-cd/pull/8387
Signed-off-by: Lucas Bickel <lucas.bickel@adfinis.com>
Note on DCO:
Checklist:
> fix(argo-cd): Update to Argo CD v2.2.5

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/ingress-grpc.yaml
> fix(argo-cd): Use ingressClassName from ingressGrpc

- charts/argocd-applicationset/Chart.yaml
- charts/argocd-applicationset/README.md
- charts/argocd-applicationset/templates/deployment.yaml
- charts/argocd-applicationset/values.yaml
Adds `extraContainers` similar to the other charts. I use this to inject a sidecar into certain ArgoCD components.
Checklist:
> fix(argo-cd applicationset): add extraContainers to deployment

- charts/argo-cd/Chart.yaml
- charts/argo-cd/values.yaml
Question:
Since it's extra-small PR and only fixes the comment, would I still have to update the chart version or changelog?
---
Note on DCO:
Checklist:
> chore(argo-cd): Fix typo of policy.csv comment in values.yaml

- charts/argo-events/Chart.yaml
- charts/argo-events/README.md
- charts/argo-events/templates/_helpers.tpl
- charts/argo-events/templates/aggregate-roles.yaml
- charts/argo-events/values.yaml
While here,
- The two template functions were not in use until now. Let's align them with the current skeleton of helm 3.x
---
Note on DCO:
Checklist:
> feat(argo-events): Add aggregate-roles (sync with upstream manifests)

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/dex/deployment.yaml
- charts/argo-cd/values.yaml
[argocd-dex rundex can use some options](https://argo-cd.readthedocs.io/en/stable/operator-manual/server-commands/argocd-dex_rundex/). 
----
Signed-off-by: krrrr38 <k.kaizu38@gmail.com>
Note on DCO:
Checklist:
> feat(argo-cd): add dex server extra args

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
Duplicated the securityContext from the repo-server main container
Signed-off-by: Eric Durand <eric_p_durand@yahoo.com>
Note on DCO:
Checklist:
> fix(argo-cd): Adding securityContext to copyutil in repo-server

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/templates/controller/workflow-controller-deployment.yaml
- charts/argo-workflows/values.yaml
Simple feature to add volume and volumeMount features to the Argo Workflows controller.
Not sure if there is a particular reason these parameters are not already in place for controller (unlike the server), but current expected use case is to add CA certs (from AWS RDS) when using persistence with SSL mode set to ```verify-ca```. It is convenient to pass CA certs as configfile volumes to ```/etc/ssl/certs/some-cert.pem```. Server and controller both use the SSL configuration and happily use added CA certs in ```etc/ssl/certs``` but no known existing way to easily pass the CA cert to the controller, so controller will fail to start.
Volumes and volumeMounts default to empty as expected. Minor bump version for new parameters.
---
Note on DCO:
If the DCO action in the integration test fails, …
> feat(argo-workflows): Add volume and volumeMount parameters to controller

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/controller/workflow-rb.yaml
When singleNamespace is true,  empty namespace is generated.
```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
name: hoge-argo-workflows-workflow
namespace:                                  <- here
```
This PR fixes it.
Note on DCO:
Checklist:
> fix(argo-workflows): Avoid "namespace: null" when singleNamespace is true

- .github/ISSUE_TEMPLATE/config.yml
Let's use the same config as upstream Argoproj projects do:
- ArgoCD: https://github.com/argoproj/argo-cd/blob/master/.github/ISSUE_TEMPLATE/config.yml
- Argo Workflows: https://github.com/argoproj/argo-workflows/blob/v3.2.9/.github/ISSUE_TEMPLATE/config.yml
---
Note on DCO:
Checklist:
> chore: Configure issue template chooser to disallow blank issues

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-configs/cluster-secrets.yaml
Signed-off-by: Matthias Lisin <ml@visu.li>
I did not ensure in my previous PR that the value inside `stringData` is quoted
and never templated as a boolean, which ofc is not valid here.
---
Checklist:
> fix(argo-cd): Quote clusterResources value to avoid invalid Secret manifest

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
This PR enables the creation of a service account for repo server by default.
> fix(argo-cd): create service account for repo server by default

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/templates/controller/workflow-controller-cluster-roles.yaml
- charts/argo-workflows/templates/controller/workflow-controller-crb.yaml
- charts/argo-workflows/templates/server/server-cluster-roles.yaml
- charts/argo-workflows/templates/server/server-crb.yaml
- charts/argo-workflows/values.yaml
Our team is managing a controller / server deployment, but the k8s admins are managing clusterroles, so it was useful to be able to install without creating the roles.
My first commit to the repo, please let me know if something is off!
Note on DCO:
Checklist:
> feat(argo-workflows): Add parameter to enable or disable server and controller roles

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-application-controller/deployment.yaml
- charts/argo-cd/values.yaml
Previously, ArgoCD application controller application labels metric was incorrectly templated.
This PR changes `.Values.controller.metrics.applicationLabels.labels` from a map to a list and updates the templating to set the correct arguments as seen [here](https://argo-cd.readthedocs.io/en/stable/operator-manual/metrics/#exposing-application-labels-as-prometheus-metrics).
Note on DCO:
Checklist:
> fix(argo-cd): ArgoCD application controller - metrics application labels

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-notifications/service-metrics.yaml
- charts/argo-cd/templates/argocd-notifications/servicemonitor.yaml
The notifications metrics are currently targeting `app.kubernetes.io/name: argocd-metrics` but the pod and service is labeled with `app.kubernetes.io/name: argocd-notifications-controller`. This updates the Service and ServiceMonitor to match.
Note on DCO:
Checklist:
> fix(argo-cd): proper selectors for notifications metrics

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-notifications/servicemonitor.yaml
- charts/argo-cd/values.yaml
All other ServiceMonitors seem to have the `selector`, this adds it to notifications as well.
Signed-off-by: Lucas Bickel <lucas.bickel@adfinis.com>
Note on DCO:
Checklist:
> feat(argo-cd): add notifications.metrics.serviceMonitor.selector for consistency

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-applicationset/networkpolicy.yaml
- charts/argo-cd/templates/argocd-notifications/networkpolicy.yaml
- charts/argo-cd/templates/argocd-repo-server/networkpolicy.yaml
The network policies for the new components AppSet and Notifications were missing
---
Note on DCO:
Checklist:
> fix(argo-cd): Add missing NetworkPolicy for AppSet and Notifications

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/server/server-cluster-roles.yaml
Note on DCO:
Checklist:
When deploying argo-worflows using chart version 0.13.0, argo-workflows v3.3.x, getting this error, same as #1171 
```
Failed to watch *v1.Secret: failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:argo:argo-server" cannot list resource "secrets" in API group "" at the cluster scope
```
Add list verb to secret
> fix(argo-workflows): Add missing list verb to secret

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-applicationset/service.yaml
- charts/argo-cd/values.yaml
This PR propose a fix for the #1199.
Note on DCO:
Checklist:
> fix(argo-cd): Correct ApplicationSet controller port

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/README.md.gotmpl
- charts/argo-cd/values.yaml
> refactor(argo-cd)!: Remove Argo CD notification default notifier

- charts/argo-cd/Chart.yaml
Ref: https://github.com/argoproj/argo-cd/releases/tag/v2.3.3
> **Bug Fixes**
>
> - fix: prevent excessive repo-server disk usage for large repos (https://github.com/argoproj/argo-cd/issues/8845) (https://github.com/argoproj/argo-cd/pull/8897)
> - fix: Set QPS and burst rate for resource ops client (https://github.com/argoproj/argo-cd/pull/8915)
---
Note on DCO:
Checklist:
> fix(argo-cd): Update to Argo CD v2.3.3

- .github/workflows/lint-and-test.yml
- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/README.md.gotmpl
- charts/argo-cd/ci/external-redis-values.yaml
- charts/argo-cd/templates/_helpers.tpl
- charts/argo-cd/templates/argocd-application-controller/deployment.yaml
- charts/argo-cd/templates/argocd-configs/externalredis-secret.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/values.yaml
Resolves #1045
---
Note on DCO:
Checklist:
> feat(argo-cd): Add ability to use an external redis instance

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-server/certificate.yaml
- charts/argo-cd/values.yaml
Resolves #1096 
---
Note on DCO:
Checklist:
> feat(argo-cd): Add params to override Certificate duration and renewBefore

- charts/argo-cd/Chart.yaml
- charts/argo-cd/crds/crd-applicationset.yaml
The CRD status field prevents certain tools from using the CRD as is. It should be populated by the api-server.
Note on DCO:
Checklist:
> fix(argo-cd): remove unneeded status from CRD

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-notifications/configmap.yaml
- charts/argo-cd/values.yaml
According to [official doc](https://argocd-notifications.readthedocs.io/en/stable/services/overview/), we can set Notification Services on `argocd-notifications-cm` ConfigMap, but there was no configuration against them. So I added them. 🙋 
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
name: argocd-notifications-cm
data:
service.slack: |
token: $slack-token
```
Note on DCO:
If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this. 
Checklist:
> feat(argo-cd): Add ability to set Notification Services

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
Adds ImagePullPolicy for the repo-server init container
Note on DCO:
Checklist:
> feat(argo-cd): add ImagePullPolicy to repo server init container

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
It's already impossible to pull the image off Quay, so it's a hotfix of some sorts.
Signed-off-by: crabique <alexey.korotkov@namecheap.com>
Checklist:
> fix(argo-cd): redis-exporter image was migrated from quay.io to docker hub

- charts/argocd-applicationset/Chart.yaml
- charts/argocd-notifications/Chart.yaml
Resolves #1219
/cc: Initial chart contributor @maruina (https://github.com/argoproj/argo-helm/pull/577), @andyfeller (https://github.com/argoproj/argo-helm/pull/365)
---
Note on DCO:
Checklist:
> chore!: Deprecate argocd-applicationset and argocd-notifications

- CODEOWNERS
I want to move myself from the generic `/charts/` section to the Argo CD chart so I don't miss PRs against Argo CD which I mainly use for personal projects and at work.
I introduced this section (in PR #714) by understanding that approvers from this section get extended with the approvers from the specific chart. But CODEOWNERS only picks the most specific rule and does not extend other rules.
/cc: @oliverbaehler You are the only one left in this section.
---
Note on DCO:
Checklist:
> chore(CODEOWNERS): Move mkilchhofer from generic to argo-cd

- charts/argo-events/Chart.yaml
- charts/argo-events/templates/argo-events-cluster-roles.yaml
- charts/argo-events/templates/argo-events-roles.yaml
This fixes/adds additional RBAC Requirements from https://github.com/argoproj/argo-events/pull/1883
Checklist:
> feat(argo-events): Adding additional RBAC for leader election

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/README.md.gotmpl
Please advise if you want to keep CRD upgrade section generic with current chart tag version or if you want to place it under each section where CRD upgrade happened.
@mbevc1 @mkilchhofer - Do you bump chart version for documentation change?
Resolves:
- https://github.com/argoproj/argo-helm/issues/1195
- https://github.com/argoproj/argo-helm/issues/1180
Checklist:
> chore(argo-cd): Document how to upgrade CRDs

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/dex/deployment.yaml
- charts/argo-cd/values.yaml
Note on DCO:
Resolves:
- https://github.com/argoproj/argo-helm/issues/1226
- https://github.com/argoproj/argo-helm/issues/1225
Checklist:
> fix(argo-cd): Use global imagePullPolicy for Dex

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-notifications/deployment.yaml
> fix(argo-cd): use global imagePullSecret value for notifications deployment

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/values.yaml
Description:
The default `containerRuntimeExecutor` has been [set](https://github.com/argoproj/argo-workflows/commit/b0d1f658388ebd4ab2c1f26a87d66282304fa391#diff-fe44f09c4d5977b5f5eaea29170b6a0748819c9d02271746a20d81a5f3efca17L49) to `emissary` in the latest [v3.3.2](https://github.com/argoproj/argo-workflows/releases/tag/v3.3.2) release. However, we are still explicitly setting this value to `docker` in the helm chart which can cause unexpected failures.
This change is meant to map the default behavior of argo-workflows deployment in the helm chart as well.
Note on DCO:
Checklist:
Changes are …
> fix(argo-workflows): Setting default `ContainerRuntimeExecutor` to emissary

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-application-controller/metrics-service.yaml
- charts/argo-cd/templates/argocd-application-controller/servicemonitor.yaml
- charts/argo-cd/templates/argocd-applicationset/metrics-service.yaml
- charts/argo-cd/templates/argocd-applicationset/servicemonitor.yaml
- charts/argo-cd/templates/argocd-notifications/service-metrics.yaml
- charts/argo-cd/templates/argocd-notifications/servicemonitor.yaml
- charts/argo-cd/templates/argocd-repo-server/metrics-service.yaml
- charts/argo-cd/templates/argocd-repo-server/servicemonitor.yaml
- charts/argo-cd/templates/argocd-server/metrics-service.yaml
- charts/argo-cd/templates/argocd-server/servicemonitor.yaml
- charts/argo-cd/templates/dex/deployment.yaml
- charts/argo-cd/templates/dex/service.yaml
- charts/argo-cd/templates/dex/servicemonitor.yaml
- charts/argo-cd/templates/redis/servicemonitor.yaml
- charts/argo-cd/values.yaml
This PR adds the necessary configuration values to be able to use metrics and servicemonitors on an istio service mesh. 
Note on DCO:
Checklist:
> feat(argo-cd): Make metrics and serviceMonitors usable on an istio service mesh

- .github/workflows/lint-and-test.yml
- scripts/helm-docs.sh
Let's try something hacky:
Related to https://github.com/norwoodj/helm-docs/issues/148
---
Note on DCO:
Checklist:
> fix: Workaround helm-docs v1.10.0 breaking change

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-configs/applications.yaml
- charts/argo-cd/templates/argocd-configs/projects.yaml
In the ArgoCD Helm chart, the applications created using `server.additionalApplications` don't have the correct indenting. That piece is unusable in the current state. This PR just fixes the indenting on that.
Signed-off-by: Alex Sears <me@alexsears.com>
Note on DCO:
Checklist:
> fix(argo-cd): Fix indent on Argo CD applications and projects

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/_helpers.tpl
- charts/argo-workflows/templates/controller/workflow-controller-deployment-pdb.yaml
- charts/argo-workflows/templates/server/server-deployment-pdb.yaml
This resolves https://github.com/argoproj/argo-helm/issues/1281 🙋 
for argo-cd's PR: https://github.com/argoproj/argo-helm/pull/1289
---
Note on DCO:
Checklist:
> fix(argo-workflows): adjust api version of pod disruption budget by referring to k8s version

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/_helpers.tpl
- charts/argo-cd/templates/argocd-application-controller/poddisruptionbudget.yaml
- charts/argo-cd/templates/argocd-repo-server/poddisruptionbudget.yaml
- charts/argo-cd/templates/argocd-server/poddisruptionbudget.yaml
- charts/argo-cd/templates/dex/poddisruptionbudget.yaml
- charts/argo-cd/templates/redis/poddisruptionbudget.yaml
This resolves https://github.com/argoproj/argo-helm/issues/1281 🙋
for argo-workflows' PR: https://github.com/argoproj/argo-helm/pull/1288
---
Note on DCO:
Checklist:
> fix(argo-cd): adjust api version of pod disruption budget by referring to k8s version

- charts/argo-cd/Chart.lock
- charts/argo-cd/Chart.yaml
See - https://github.com/DandyDeveloper/charts/commit/295dc64ff4d7d59ed1dca3c3b447bf909480ee19
argocd chart is using an older `redis-ha` dependency which uses `haproxy:2.0.4` image/
`haproxy:2.0.4` has several critical CVEs.  This PR updates to the latest `redis-ha` which uses a more recent haproxy image.
Note on DCO:
Checklist:
* [X ] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#versioning)
* [X ] I have updated the documentation according to …
> fix(argo-cd): Update redis-ha dependency for haproxy CVEs

- charts/argo-cd/Chart.lock
- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/README.md.gotmpl
- charts/argo-cd/values.yaml
While here, I reworked the README a bit.
Fixes:
- #1203
- #1268
- #1282
- #1069
---
Note on DCO:
Checklist:
> chore(argo-cd): Update redis-ha to 4.16.0

- .github/configs/labeler.yaml
- .github/workflows/pr-sizing.yml
Let's automate some "triage" work here:
-> Tested it in a fork
---
Note on DCO:
Checklist:
> chore: Add labeler action to automate PR labeling

- .github/workflows/lint-and-test.yml
- .github/workflows/pr-sizing.yml
- .github/workflows/publish.yml
- .github/workflows/stale.yml
I updated some tools' version on GitHub Actions. 🙋 
In order to check the CI, I created a PR (https://github.com/argoproj/argo-helm/pull/1313) that contained the usual diffs and CI passed.
- [lint-and-test](https://github.com/argoproj/argo-helm/runs/6709404501?check_suite_focus=true)
- [pr-sizing](https://github.com/argoproj/argo-helm/actions/runs/2428594752)
So I think these versions up will be harmless. :eyes:
---
Note on DCO:
Checklist:
> chore: Update some tools' versions on GitHub Actions

- .github/ISSUE_TEMPLATE/bug_report.yaml
On issues, the report of `helm chart version`  will help us to investigate more efficiently.
So I added the input form for them. 🙋 
---
Note on DCO:
Checklist:
> feat: add chart version input on bug report to help investigation

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/README.md.gotmpl
- charts/argo-cd/crds/crd-application.yaml
- charts/argo-cd/crds/crd-applicationset.yaml
- charts/argo-cd/templates/argocd-applicationset/deployment.yaml
- charts/argo-cd/values.yaml
- Upgrade ArgoCD to v2.4.0.
- Specify logs RBAC enforcement config in server. According to this [docs](https://argo-cd.readthedocs.io/en/latest/operator-manual/upgrading/2.3-2.4/#enable-logs-rbac-enforcement): `2.4 introduced logs as a new RBAC resource. In 2.3, users with applications, get access automatically get logs access. In 2.5, you will have to explicitly grant logs, get access.`. So I think we should put the configuration to values as a reminder to prepare for future releases.
- Remove ksonnet and helm 2 support from Application and ApplicationSet CRDs
Note on DCO:
Checklist:
Changes are …
> feat(argo-cd): Update to Argo CD v2.4.0

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/clusterrole.yaml
- charts/argo-cd/values.yaml
To use the new exec feature, RBAC of argocd-server needs to be extended with:
```yaml
- apiGroups:
- ""
resources:
- pods/exec
verbs:
- create
```
Ref: https://argo-cd.readthedocs.io/en/latest/operator-manual/rbac/#exec-resource
---
Note on DCO:
Checklist:
> fix(argo-cd): Extend K8s RBAC when using UI exec feature

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/_helpers.tpl
> Argo-cd: Add controller statefulset name truncation at 52 chars. Fixes #1328

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-notifications/role.yaml
Currently, the ArgoCD notification controller doesn't have access to the config map and the secret when these are provided externally and not created from within the chart. This is due to the incorrect resources named in the role.
Let me know if there is any feedback or what is missing to move this PR forward.
Checklist:
> fix(argo-cd): fix argo-cd notifications resource names in role

- charts/argo-workflows/Chart.yaml
[Release Notes](https://github.com/argoproj/argo-workflows/releases/tag/v3.3.8)
Includes:
- fix: check for nil, and add logging to expose root cause of panic in Issue 8968 (https://github.com/argoproj/argo-workflows/pull/9010)
Note on DCO:
Checklist:
> feat(argo-workflows): Upgrade argo-workflows to v3.3.8

- charts/argo-cd/Chart.lock
- charts/argo-cd/Chart.yaml
Update redis-ha dependency to use a newer version of haproxy docker container
See - https://github.com/DandyDeveloper/charts/pull/196
_haproxy 2.4.9 has 53 CVEs, 8 of them critical which this will help mitigate_
**Why this is needed for argocd:**
Even though the argocd chart now supports overriding the haproxy image tag it will not work without this change.
In the redis-ha template the haproxy configuration has `option http-use-htx` enabled which is deprecated.  Overriding the image tag will cause haproxy to not start due to a configuration error.  
This PR is required to use newer versions of the haproxy image.  It removes the deprecated (and default) `option http-use-htx` which will allow argocd users to patch their own newer versions of …
> feat(argo-cd): Upgrade argocd redis-ha dependency

- CODEOWNERS
Add new maintainer for Argo Events chart
Signed-off-by: Petr Drastil <petr.drastil@gmail.com>
> chore(github): Add new maintainer for argo-events

- charts/argo-cd/Chart.lock
- charts/argo-cd/Chart.yaml
Upgrade redis-ha to bring additional configuration parameters
---
Note on DCO:
Checklist:
> feat(argo-cd): bump redis-ha dependency to 4.17.1

- CODEOWNERS
I'm already helping with argo-workflows helm chart PRs and would like to help with argo-cd also.  We're actively using it so it'll help us also.
Note on DCO:
Checklist:
> chore(argo-cd): Add jmeridth to argo-cd in CODEOWNERS to help with PRs

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/controller/workflow-aggregate-roles.yaml
- charts/argo-workflows/templates/controller/workflow-controller-cluster-roles.yaml
- charts/argo-workflows/templates/controller/workflow-controller-sa.yaml
- charts/argo-workflows/templates/controller/workflow-rb.yaml
- charts/argo-workflows/templates/controller/workflow-role.yaml
- charts/argo-workflows/templates/controller/workflow-sa.yaml
- charts/argo-workflows/templates/server/server-sa.yaml
Since some resources were not given common labels, I have tried to give them.
Note on DCO:
Checklist:
> feat(argo-workflows): Assign common labels to some resources

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-application-controller/deployment.yaml
- charts/argo-cd/templates/argocd-applicationset/deployment.yaml
- charts/argo-cd/templates/argocd-notifications/deployment.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/templates/dex/deployment.yaml
- charts/argo-cd/templates/redis/deployment.yaml
Allow to use digests.
https://github.com/argoproj/argo-helm/issues/417
Before this PR, a `values.yaml` like [this](https://gitlab.com/kubitus-project/kubitus-installer/-/jobs/2705596962#L8030):
```yaml
argo-cd:
global:
image:
repository:  "quay.io/argoproj/argocd"
tag: "v2.4.4@sha256:9d78128c71e88daf7c6bb45c7c2d58ac293786fea6ae1c5725fe4052681950dc"
dex:
image:
repository:  "ghcr.io/dexidp/dex"
tag: "v2.32.0@sha256:85481bc46e04163ad0f2b6a003aef441ad324ffd48e78e5076c166b308c4f5fe"
redis:
image:
repository:  "redis"
tag: "7.0.2-alpine@sha256"
```
Fails [with](https://gitlab.com/kubitus-project/kubitus-installer/-/jobs/2705596962#L8167):
```
Error: Deployment.apps "argocd-redis" is invalid: [metadata.labels: Invalid value: "7.0.2-alpine@sha256": a valid label must be an empty string or …
```
> feat(argo-cd): Truncate version labels to 63 characters

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/templates/_helpers.tpl
- charts/argo-workflows/templates/controller/workflow-controller-config-map.yaml
- charts/argo-workflows/templates/controller/workflow-controller-deployment.yaml
- charts/argo-workflows/templates/controller/workflow-controller-service.yaml
- charts/argo-workflows/templates/server/server-deployment.yaml
- charts/argo-workflows/templates/server/server-service.yaml
- charts/argo-workflows/values.yaml
I added `.Values.images.tag` 🙋 
---
Note on DCO:
Checklist:
> feat(argo-workflows): Add global tag

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
> fix(argo-cd): redis and redis-exporter image was migrated from docker hub to public ecr for docker hub rate limit

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
I updated redis version as well as https://github.com/argoproj/argo-cd/pull/10059 .🙋 
---
Note on DCO:
Checklist:
> chore(argo-cd): update redis to 7.0.4 for avoiding CVE-2022-30065

- .github/configs/ct-install.yaml
- .github/configs/ct-lint.yaml
- .github/workflows/lint-and-test.yml
- .github/workflows/pr-sizing.yml
- .github/workflows/publish.yml
I always wondered why we have configured the two EOL repos:
- https://charts.helm.sh/stable
- https://charts.helm.sh/incubator
So let's remove all currently unused repos.
---
Note on DCO:
Checklist:
> ci(github): Cleanup unused chart-repos

- charts/argo-workflows/Chart.yaml
[Release Notes](https://github.com/argoproj/argo-workflows/releases/tag/v3.3.9)
Skimming changes I don't see anything that requires updates to values.  Definitely want more 👀 to double check me.
Note on DCO:
Checklist:
> feat(argo-workflows): Upgrade argo-workflows to v3.3.9

- .github/ISSUE_TEMPLATE/config.yml
Let's enable GitHub Discussions and place a link on the "create issue" page.
> chore(github): Enable GitHub Discussions

- charts/argo-cd/Chart.yaml
[Release notes](https://github.com/argoproj/argo-cd/releases/tag/v2.4.10)
[Diff between argo-cd v2.4.9 and v2.4.10](https://github.com/argoproj/argo-cd/compare/v2.4.9...v2.4.10)
- 3 doc changes
- 3 fixes
Note on DCO:
Checklist:
> feat(argo-cd): Upgrade argocd to v2.4.10

- .github/workflows/pr-title.yml
In order to pass CI on https://github.com/argoproj/argo-helm/pull/1356, https://github.com/argoproj/argo-helm/pull/1356#issuecomment-1172845108 , I added `argocd-apps` on pr-title. 🙋 
*It looks that pr-title should be configures before using the new title 👀 
---
Note on DCO:
Checklist:
> chore(github): add argocd-apps on pr-title

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-application-controller/statefulset.yaml
Caused by https://github.com/argoproj/argo-helm/pull/1413
```
Error: YAML parse error on argo-cd/templates/argocd-application-controller/statefulset.yaml: error converting YAML to JSON: yaml: line 100: did not find expected '-' indicator
```
Checklist:
> fix(argo-cd): invalid yaml with topologySpreadConstraints

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/crds/crd-applicationset.yaml
- charts/argo-cd/templates/crds/crd-extension.yaml
Signed-off-by: Jan Fuhrer <janfuhrer@mailbox.org>
**Problem**
If you install argocd with fluxcd, following error occurs:
```bash
Last Helm logs:
Warning  error  8m41s (x8 over 10m)  helm-controller  reconciliation failed: Helm install failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:
line 12: mapping key "annotations" already defined at line 5
```
Tell me If I can correct anything.
---
Note on DCO:
Checklist:
> fix(argo-cd): Removal of duplicate mapping key annotations in crds

- charts/argo-cd/Chart.lock
- charts/argo-cd/Chart.yaml
Resovles: https://github.com/argoproj/argo-helm/issues/1428
Note on DCO:
Checklist:
> chore(argo-cd): Upgrade redis-ha chart

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-application-controller/statefulset.yaml
- charts/argo-cd/values.yaml
Base on this PR upstream https://github.com/argoproj/argo-cd/pull/8928 we can
now provide a hard resync value to the ArgoCD Application Controller
Note on DCO:
Checklist:
> feat(argo-cd): Add appHardResyncPeriod option for controller

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
Adding existing value [`repoServer.serviceAccount.automountServiceAccountToken`](https://github.com/argoproj/argo-helm/blob/71da4e98f26a222e664269fac55dde5c374915d5/charts/argo-cd/values.yaml#L1654) to its [deployment template](https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/templates/argocd-repo-server/deployment.yaml).
E.g. redis already has this key implemented in the deployment:
https://github.com/argoproj/argo-helm/blob/71da4e98f26a222e664269fac55dde5c374915d5/charts/argo-cd/templates/redis/deployment.yaml#L31
This PR will enable the usage of [Kubernetes Authentication](https://github.com/argoproj-labs/argocd-vault-plugin/blob/v1.12.0/docs/backends.md#kubernetes-authentication) within argocd-vault-plugin.
Checklist:
Changes are automatically published when merged to …
> fix(argo-cd): add automountServiceAccountToken to repoServer

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-notifications/deployment.yaml
- charts/argo-cd/values.yaml
Allow to set up a priorityClassName for notifications controller Pods
Note on DCO:
Checklist:
> feat(argo-cd): Add priorityClassName to notifications

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/dex/deployment.yaml
Signed-off-by: bakito <github@bakito.ch>
Note on DCO:
This pull request fixes an issue in the dex deployment if additional init containers are defined in the values.
The current implementation adds a second initContainers section. The fix is to merge them both together.
Checklist:
> fix(argo-cd): Duplicated dex init containers

- charts/argo-cd/Chart.yaml
Diff:
https://github.com/argoproj/argo-cd/compare/v2.4.11...v2.4.12
I don't think there are any other changes needed, but I need this update because of [this bugfix](https://github.com/argoproj/argo-cd/issues/10384)
Note on DCO:
Checklist:
> feat(argo-cd): Upgrade argocd to v2.4.12

- charts/argo-cd/Chart.lock
- charts/argo-cd/Chart.yaml
Resolves https://github.com/argoproj/argo-helm/issues/1461
Note on DCO:
Checklist:
> chore(argo-cd): Update Redis HA to 4.22.2

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-server/certificate.yaml
- charts/argo-cd/values.yaml
> feat(argo-cd): Allow setting the private key algorithm in the Certificate spec

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/values.yaml
There is unsupported value on `.Values.server.sso` , so I removed it. 🙋 
ref: https://github.com/argoproj/argo-helm/pull/1463#issuecomment-1251732944
---
Note on DCO:
Checklist:
> fix(argo-workflows): remove unsupported value from SSO configuration

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-configs/externalredis-secret.yaml
- charts/argo-cd/values.yaml
Rebased https://github.com/argoproj/argo-helm/pull/1445 to latest config section. Environmental variable is already referenced in deployment via
```yaml
env:
- name: REDIS_USERNAME
valueFrom:
secretKeyRef:
name: {{ default (include "argo-cd.redis.fullname" .) .Values.externalRedis.existingSecret }}
key: redis-username
optional: true
```
Note on DCO:
Checklist:
> feat(argo-cd): Add username support for external redis

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
Resolves https://github.com/argoproj/argo-helm/issues/1482
Note on DCO:
Checklist:
> fix(argo-cd): Rendering of node selector for repoServer

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-application-controller/service.yaml
- charts/argo-cd/templates/argocd-applicationset/service.yaml
- charts/argo-cd/templates/argocd-repo-server/service.yaml
> fix(argo-cd): Add missing templating for some service labels

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/values.yaml
This PR resolves https://github.com/argoproj/argo-helm/issues/1450 . 🙋 
---
Note on DCO:
Checklist:
> fix(argo-workflows): change default type of `.mainContainer.env` and `.executor.env` from object to array

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/templates/extra-manifests.yaml
- charts/argo-workflows/values.yaml
Objective of this PR is the same that others have made to other charts.
Ref
- https://github.com/argoproj/argo-helm/pull/1094
- https://github.com/argoproj/argo-helm/pull/1366
This change enables us to use SecretProviderClass, and will be useful when we use SSO and OIDC.
Note on DCO:
Checklist:
> feat(argo-workflows): Add extra manifests to deploy within the chart

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/README.md.gotmpl
Signed-off-by: Hyeonmin Park <hyeonmin.park@kennysoft.kr>
Note on DCO:
Checklist:
> docs(argo-cd): Fix v5.5.0 upgrade guide heading

- charts/argo-workflows/Chart.yaml
[Release Notes](https://github.com/argoproj/argo-workflows/releases/tag/v3.4.1)
Note on DCO:
Checklist:
> chore(argo-workflows): Upgrade argo-workflows to app version 3.4.1

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
Closes https://github.com/argoproj/argo-helm/issues/1506
Note on DCO:
Checklist:
> chore(argo-cd): upgrade Dex to 2.35 to avoid CVE-2022-39222

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-application-controller/serviceaccount.yaml
- charts/argo-cd/templates/argocd-applicationset/serviceaccount.yaml
- charts/argo-cd/templates/argocd-server/serviceaccount.yaml
- charts/argo-cd/values.yaml
Adds support for labels on Service Accounts which is needed for using Federated Workload Identity in Azure as an example.
Checklist:
> feat(argo-cd): Add support for labels on Service Accounts

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
Argocd
See - https://github.com/argoproj/argo-cd/releases/tag/v2.4.14
Dex
See - https://github.com/dexidp/dex/releases/tag/v2.35.1
See - https://hub.docker.com/r/dexidp/dex/tags?page=1&name=2.35.1-distroless
Note on DCO:
Checklist:
* [X ] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [X ] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [X ] I have updated the chart …
> feat(argo-cd): Upgrade argocd to v2.4.14

- charts/argo-cd/Chart.yaml
- charts/argo-cd/values.yaml
> fix(argo-cd): correct example PrometheusRule expression for missing app info

- .github/workflows/lint-and-test.yml
- .github/workflows/pr-title.yml
- .github/workflows/publish.yml
- .github/workflows/stale.yml
The need for minimum permissions was flagged by [CLOMonitor](https://clomonitor.io/projects/cncf/argo#argo-helm_security)
Signed-off-by: Eddie Knight <iv.eddieknight@gmail.com>
Note on DCO:
Checklist:
> chore(github): Added minimum permissions to workflows

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-notifications/deployment.yaml
- charts/argo-cd/values.yaml
> fix(argo-cd): Added missing envFrom for notifications-controller. Fixed env formatting.

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
I updated Redis version as well as https://github.com/argoproj/argo-cd/pull/10702 .🙋 
---
Note on DCO:
Checklist:
> chore(argo-cd): Updated Redis to 7.0.5 for fixing CVE-2022-35951.

- .github/workflows/lint-and-test.yml
- .github/workflows/publish.yml
- .github/workflows/stale.yml
> chore(github): Update actions' versions

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-notifications/serviceaccount.yaml
- charts/argo-cd/templates/argocd-repo-server/serviceaccount.yaml
- charts/argo-cd/values.yaml
#1513 miss 2 components
Note on DCO:
Checklist:
> feat(argo-cd): Make labels for repoServer and notification service accounts configurable

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/NOTES.txt
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/values.yaml
It doesn't make sense to have resource configuration for copyutil container that is using same image as main container. Pod resources are calculated as MAX(MAX(init_containers), SUM(containers)). For this reason requested resources will be always set by repo-server.
Note on DCO:
Checklist:
> chore(argo-cd): Use same resources for repo-server copyutil

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/ingress-grpc.yaml
> fix(argo-cd): Fix missed apiVersion pattern change

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-application-controller/servicemonitor.yaml
- charts/argo-cd/templates/argocd-applicationset/servicemonitor.yaml
- charts/argo-cd/templates/argocd-notifications/servicemonitor.yaml
- charts/argo-cd/templates/argocd-repo-server/servicemonitor.yaml
- charts/argo-cd/templates/argocd-server/servicemonitor.yaml
- charts/argo-cd/templates/dex/servicemonitor.yaml
- charts/argo-cd/templates/redis/servicemonitor.yaml
- charts/argo-cd/values.yaml
There are some cases where annotating the ServiceMonitor resources is useful
---
Note on DCO:
Checklist:
> feat(argo-cd): ServiceMonitor resources are able to be annotated

- .github/workflows/lint-and-test.yml
- .github/workflows/publish.yml
> fix(github): Use hardcoded version for helm

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/NOTES.txt
- charts/argo-cd/templates/_helpers.tpl
- charts/argo-cd/templates/argocd-configs/argocd-cm.yaml
- charts/argo-cd/templates/argocd-configs/argocd-rbac-cm.yaml
- charts/argo-cd/templates/argocd-server/clusterrole.yaml
- charts/argo-cd/values.yaml
Resolves: https://github.com/argoproj/argo-helm/issues/1519
Decouple argocd-cm and argocd-rbac-cm from server component and keep this together with rest of the configs. Backward compatibility ensured with coalesce and deprecation notice.
Note on DCO:
Checklist:
> feat(argo-cd): Move argocd-cm and argocd-rbac-cm to config section

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/_helpers.tpl
- charts/argo-cd/templates/argocd-application-controller/statefulset.yaml
- charts/argo-cd/templates/argocd-configs/argocd-styles-cm.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/clusterrole.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/role.yaml
- charts/argo-cd/templates/crds/crd-application.yaml
- charts/argo-cd/templates/crds/crd-applicationset.yaml
- charts/argo-cd/templates/crds/crd-project.yaml
Resolves:
- https://github.com/argoproj/argo-helm/issues/1567
- https://github.com/argoproj/argo-helm/issues/1537
Note on DCO:
Checklist:
> feat(argo-cd): Upgrade Argo CD to 2.5.0

- .github/workflows/lint-and-test.yml
- .github/workflows/pr-title.yml
- .github/workflows/publish.yml
- scripts/lint.sh
Keeping GitHub actions updated
Testing: https://github.com/argoproj/argo-helm/actions/runs/3323692976/jobs/5494364515
---
Note on DCO:
Checklist:
> chore(github): Bump GitHub actions versions

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/NOTES.txt
When `admin.enabled: "false"`, the notes in the chart contain old config keys which break templating.
```
Error: template: argo-cd/charts/argo-cd/templates/NOTES.txt:67:15: executing "argo-cd/charts/argo-cd/templates/NOTES.txt" at <index .Values.server.config "dex.config">: error calling index: index of untyped nil
```
---
Note on DCO:
Checklist:
> fix(argo-cd): Chart NOTES nil references

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/controller/workflow-controller-config-map.yaml
- charts/argo-workflows/templates/server/server-cluster-roles.yaml
Fixes: #1572 
Removed the sso.rbac map as it breaks the sso integration. Also if the sso block is used we should include serviceaccount in our clusterrole instead of being managed by another setting.
Note on DCO:
Checklist:
> fix(argo-workflows): serviceaccount rbac when sso is enabled

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/redis/deployment.yaml
Whitespace, indentation and DRY cleanup so upcoming changes are more visible for Redis manifest.
---
Note on DCO:
Checklist:
> chore(argo-cd): Cleanup Redis manifest

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/NOTES.txt
- charts/argo-cd/templates/argocd-configs/argocd-cm.yaml
- charts/argo-cd/templates/argocd-configs/argocd-rbac-cm.yaml
Fixes situation when user disabled creation of configs. Coalesce takes `server.configEnabled: false` as empty value and condition will fall through to `cm.create: true`.
---
Note on DCO:
Checklist:
> fix(argo-cd): Fix config migration path

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-application-controller/statefulset.yaml
- charts/argo-cd/templates/dex/deployment.yaml
- charts/argo-cd/values.yaml
- Align application controller based on @mkilchhofer comment
- Use same template pattern for Dex probes
Ref:
- argoproj/argo-cd#9557
---
Note on DCO:
Checklist:
> chore(argo-cd): Remove liveness probe from application controller

- .github/dependabot.yml
Add Dependabot to simplify maintenance of the GitHub workflow dependencies. Requires setup under Settings > Code security and analysis on repository where you allow dependabot to open PRs automatically.
---
Note on DCO:
Checklist:
> chore(github): Add dependabot.yml

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/README.md.gotmpl
- charts/argo-cd/templates/argocd-application-controller/statefulset.yaml
- charts/argo-cd/templates/argocd-applicationset/deployment.yaml
- charts/argo-cd/templates/argocd-notifications/bots/slack/deployment.yaml
- charts/argo-cd/templates/argocd-notifications/deployment.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/templates/dex/deployment.yaml
- charts/argo-cd/templates/redis/deployment.yaml
- charts/argo-cd/values.yaml
Resolves: 
- https://github.com/argoproj/argo-helm/issues/1494
- https://github.com/argoproj/argo-helm/issues/1560
Container security context have been placed into same place across all components
Minimum supported version is 1.22 based on https://argo-cd.readthedocs.io/en/stable/operator-manual/installation/#supported-versions
---
Note on DCO:
Checklist:
> feat(argo-cd): Set container security contexts

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/NOTES.txt
- charts/argo-cd/templates/argocd-configs/argocd-server-tls.yaml
- charts/argo-cd/templates/argocd-server/certificate.yaml
- charts/argo-cd/values.yaml
- Replaces deprecated configuration via configs.secret.argocdServerTlsConfig
- Fixes cert-manager resource so the secret name is always valid
---
Ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/tls/#tls-certificates-used-by-argocd-server
Note on DCO:
Checklist:
> feat(argo-cd): Support manually managed TLS certificate for Server

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/crds/crd-applicationset.yaml
- charts/argo-cd/templates/crds/crd-extension.yaml
Thanks to 
```yaml
annotations:
{{- if .Values.crds.keep }}
"helm.sh/resource-policy": keep
{{- end }}
```
it should not break users configs.
---
Note on DCO:
Checklist:
> fix(argo-cd): Don't install CRDs for disabled components

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-application-controller/networkpolicy.yaml
update networkpolicy port name for argocd-application-controller to fix #1601 
Signed-off-by: Eric Cimino <ecimino@vailsys.com>
Note on DCO:
Checklist:
> fix(argo-cd): update network policy port name

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/_helpers.tpl
- charts/argo-cd/templates/argocd-configs/argocd-cm.yaml
- charts/argo-cd/templates/argocd-configs/argocd-rbac-cm.yaml
Closes: https://github.com/argoproj/argo-helm/issues/1611
As pointed out in the issue `colaesce` do not respect old default values and proper way would be to merge new section with the old one.
---
Note on DCO:
Checklist:
> fix(argo-cd): Replace coalesce with merge for old config values

- charts/argo-cd/Chart.yaml
> chore(argo-cd): Upgrade Argo Image to the latest version 2.5.1

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
Resolves:
#1619
Note on DCO:
Checklist:
> fix(argo-cd): Add /tmp voulmeMount to extensions container

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/clusterrole.yaml
Add missing ClusterRole permissions to argo-cd-server to manage Application in all namespaces
Following [#9755](https://github.com/argoproj/argo-cd/pull/9755), argo-cd server needs permissions to `update` Applications in every namespace
Checklist:
> fix(argo-cd): Add missing ClusterRole permissions to argo-cd-server

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
Dex with distroless image have permission issues that can be solved only by suppling fsGroup or runAsUser security context. 
See: https://github.com/argoproj/argo-cd/pull/11219
---
Note on DCO:
Checklist:
> fix(argo-cd): Use Dex non-distroless image

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/README.md.gotmpl
- charts/argo-workflows/templates/controller/workflow-controller-config-map.yaml
- charts/argo-workflows/values.yaml
Sometimes users need to add some custom type of artifacts repo like self-hosted Artifactory.
> feat(argo-workflows): Allow to add custom artifact repository

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-configs/cluster-secrets.yaml
Closes:
- #1633
- #1117
Use provided cluster config json config as is to enable post-processing by Vault plugin.
---
Note on DCO:
Checklist:
> fix(argo-cd): Use raw json for cluster credentials for Vault compatibility

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-configs/cluster-secrets.yaml
Closes: https://github.com/argoproj/argo-helm/issues/1635
---
Note on DCO:
Checklist:
> fix(argo-cd): Cluster credentials config should be a string

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/controller/workflow-controller-config-map.yaml
This PR resolves https://github.com/argoproj/argo-helm/issues/1638 . 🙋 
*We will discuss the original issue at https://github.com/argoproj/argo-helm/issues/1572 .
---
Note on DCO:
Checklist:
> fix(argo-workflows): Added missing attribute for sso

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-configs/argocd-gpg-keys-cm.yaml
The template removed a little too much whitespace resulting in an invalid ConfigMap.
Error:
```
Error: YAML parse error on argocd/charts/argo-cd/templates/argocd-configs/argocd-gpg-keys-cm.yaml: error converting YAML to JSON: yaml: line 10: mapping values are not allowed in this context
```
Signed-off-by: Allex <allexveldman+github@gmail.com>
Note on DCO:
Checklist:
> fix(argo-cd): Invalid argocd-gpg-keys-cm template

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/templates/controller/workflow-controller-cluster-roles.yaml
- charts/argo-workflows/values.yaml
Allow the controller to get any secrets.
When I was working with argo events, I created the following objects:
- an argo workflow that uses service account A
- service account A using mimagePullSecret `docker-registry`
The argo events sensor get an error when triggering the workflow. The error is `
secrets "docker-registry" is forbidden: User "system:serviceaccount:argo:my-argo-workflows-workflow-controller"
cannot get resource "secrets" in API group "" in the namespace "yolu-ci"'`
The error happens because the service account that the controller is using does not have permission to get secrets. This PR allows users to whitelist secrets. After making this change, the error is gone
Signed-off-by: emmayylu <84873428+yolu-kxs@users.noreply.github.com>
Note on DCO:
If the DCO action in the …
> feat(argo-workflows): Allow controller to whitelist secrets

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/templates/controller/workflow-controller-sa.yaml
- charts/argo-workflows/templates/controller/workflow-sa.yaml
- charts/argo-workflows/templates/server/server-sa.yaml
- charts/argo-workflows/values.yaml
Signed-off-by: Eugene Lugovtsov <lug.zhenia@gmail.com>
Note on DCO:
Checklist:
> feat(argo-workflows): Add labels for ServiceAccounts

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/NOTES.txt
> fix(argo-cd): deprecate server.extraArgs."--insecure"

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/templates/controller/workflow-controller-config-map.yaml
- charts/argo-workflows/values.yaml
This PR resolves https://github.com/argoproj/argo-helm/issues/1667 🙋 
---
Note on DCO:
Checklist:
> chore(argo-workflows): Support workflow retention

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/_helpers.tpl
- charts/argo-cd/templates/argocd-configs/argocd-repo-server-tls.yaml
- charts/argo-cd/values.yaml
This is to allow users to implement the TLS recommendations for Repo Server on [this page](https://argo-cd.readthedocs.io/en/stable/operator-manual/tls/#configuring-inbound-tls-for-argocd-repo-server)
This replicates the logic that was used on the Dex server strict TLS configuration, across to the Repo Server. 
Note on DCO:
If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the Details link next to the DCO action for instructions on how to resolve this.
Checklist:
> feat(argo-cd): Add Repo Server strict TLS cert support

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/controller/workflow-role.yaml
Signed-off-by: danmx <daniel@iziourov.info>
Note on DCO:
Checklist:
> chore(argo-workflows): removed deprecated Role rbac

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/controller/workflow-role.yaml
According to the documentation:
https://argoproj.github.io/argo-workflows/walk-through/artifacts/#artifact-garbage-collection
Signed-off-by: danmx <daniel@iziourov.info>
Note on DCO:
Checklist:
> fix(argo-workflows): missing artifact GC rbac

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/aggregate-roles.yaml
- charts/argo-cd/values.yaml
Signed-off-by: Hyeonmin Park <hyeonmin.park@kennysoft.kr>
Note on DCO:
Checklist:
> feat(argo-cd): Set aggregate roles only for using resources, with argocdextensions also

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/_helpers.tpl
- charts/argo-workflows/templates/controller/workflow-controller-deployment.yaml
- charts/argo-workflows/templates/server/server-deployment.yaml
- charts/argo-workflows/templates/server/server-service.yaml
> fix(argo-workflows): avoid label exceeding maximum length

- charts/argo-events/Chart.yaml
- charts/argo-events/templates/_helpers.tpl
- charts/argo-events/templates/argo-events-controller/deployment.yaml
- charts/argo-events/templates/argo-events-webhook/deployment.yaml
> fix(argo-events): avoid label exceeding maximum length

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
a warning similar to below will be generated if `timeout.hard.reconciliation` is set to 0 explicitly without unit
```
time="2022-12-13T18:02:36Z" level=warning msg="Could not parse '0' as a duration string from environment ARGOCD_HARD_RECONCILIATION_TIMEOUT"
```
minimal code to reproduce the issue
```go
package main
import (
"fmt"
"math"
"os"
"time"
timeutil "github.com/argoproj/pkg/time"
log "github.com/sirupsen/logrus"
)
const (
defaultAppResyncPeriod     = 180
defaultAppHardResyncPeriod = 0
)
// ref. https://github.com/argoproj/argo-cd/blob/v2.5.4/util/env/env.go#L99
func ParseDurationFromEnv(env string, defaultValue, min, max time.Duration) time.Duration {
str := os.Getenv(env)
if str == "" {
return defaultValue
}
durPtr, err := timeutil.ParseDuration(str)
if err != nil { …
```
> fix(argo-cd): Prevent could not parse 0 warning

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
I fixed and added some description in the values file of Argo CD:
- replace `application set` with `ApplicationSet` to match others
- add missing `ApplicationSet` in front of `controller` as already present for other values
- fix PascalCase `applicationset` to `ApplicationSet`
- change wrongly named `Application controller` to `Notifications controller`
- add missing `notifications` in front of `controller` as already present for other values
Checklist:
Marco Lecheler [marco.lecheler@mercedes-benz.com](mailto:marco.lecheler@mercedes-benz.com) Mercedes-Benz Tech Innovation GmbH ([ProviderInformation](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md))
> docs(argo-cd): Fix Argo CD value description typos for AppSet and Notification controllers

- charts/argo-events/Chart.yaml
- charts/argo-events/templates/_helpers.tpl
- charts/argo-events/templates/argo-events-controller/pdb.yaml
- charts/argo-events/templates/argo-events-webhook/pdb.yaml
Signed-off-by: Vadim Grek <vadimprog@gmail.com>
Fixes #1709
Checklist:
> chore(argo-events): use policy/v1 for poddisruptionbudgets, when available

- charts/argo-events/Chart.yaml
- charts/argo-events/README.md
- charts/argo-events/templates/argo-events-webhook/deployment.yaml
- charts/argo-events/values.yaml
> feat(argo-events): Add the ability to change the port for argo-events webhook

- charts/argo-cd/Chart.yaml
Release notes: https://github.com/argoproj/argo-cd/releases/tag/v2.5.5
---
Signed-off-by: Yannay Hammer <yannayha@gmail.com>
Note on DCO:
Checklist:
> chore(argo-cd): Update ArgoCD to v2.5.5

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-configs/argocd-repo-server-tls-secret.yaml
When I added RepoServer TLS Secret, I added the enabled value check to match code on Dex. 
I missed that RepoServer cannot be disabled so there is no enabled flag. Currently to deploy the TLS secret you need to add `.Values.repoServer.enabled: true` just to deploy the secret. This PR is to remove this unnecessary value and only use `.Values.repoServer.certificateSecret.enabled: true` instead.
_Also TLS config using signed certs for Dex, RepoServer and Server have been rolled to production this was the only pain I spotted._
Checklist:
> fix(argo-cd): remove incorrect flag for repoServer TLS secret

- charts/argo-cd/Chart.lock
- charts/argo-cd/Chart.yaml
ref: https://github.com/DandyDeveloper/charts/pull/236
---
Note on DCO:
Checklist:
> chore(argo-cd): Update redis-ha to v4.22.4

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-applicationset/deployment.yaml
- Added hostAliases taken from `.Values.global.hostAliases`
Checklist:
> feat(argo-cd): Add hostAliases to ApplicationSet Deployment

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/_versions.tpl
- charts/argo-cd/templates/argocd-application-controller/pdb.yaml
- charts/argo-cd/templates/argocd-applicationset/pdb.yaml
- charts/argo-cd/templates/argocd-notifications/bots/slack/pdb.yaml
- charts/argo-cd/templates/argocd-notifications/pdb.yaml
- charts/argo-cd/templates/argocd-repo-server/pdb.yaml
- charts/argo-cd/templates/argocd-server/pdb.yaml
- charts/argo-cd/templates/dex/pdb.yaml
- charts/argo-cd/templates/redis/pdb.yaml
- charts/argo-cd/values.yaml
Removed API override for PDBs as K8s 1.22 removed alpha interfaces.
---
Note on DCO:
Checklist:
> chore(argo-cd): Remove legacy API versions for PDBs

- CODEOWNERS
Signed-off-by: Petr Drastil <petr.drastil@gmail.com>
> chore(argo-cd): Add pdrastil as Argo CD codeowner

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/_versions.tpl
- charts/argo-cd/templates/argocd-applicationset/webhook-ingress.yaml
- charts/argo-cd/templates/argocd-server/ingress-grpc.yaml
- charts/argo-cd/templates/argocd-server/ingress.yaml
- charts/argo-cd/values.yaml
- Removed overrides and code for legacy Ingress API versions.
- Simplify code if -> with
---
Note on DCO:
Checklist:
> chore(argo-cd): Remove legacy API versions for Ingresses

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/_helpers.tpl
- charts/argo-workflows/templates/controller/workflow-controller-deployment-pdb.yaml
- charts/argo-workflows/templates/server/server-deployment-pdb.yaml
k8s v1.21 is no more supported, so let's remove old apiVersion.
ref: https://endoflife.date/kubernetes
---
Note on DCO:
Checklist:
> chore(argo-workflows): Remove legacy API versions for PDBs

- charts/argo-events/Chart.yaml
- charts/argo-events/README.md
- charts/argo-events/values.yaml
Discussion about changes to this new PR are contained in the previous closed PR #1725 .
Fixes issue #1724 
Signed-off-by: Ramin Akhbari <ramin@akhbari.us>
Note on DCO:
Checklist:
> fix(argo-events): Added missing NATS version in values.yaml

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
Non-functional change that improves documentation and groups sections for extra containers, volumes and volume mounts so it's easier to spot whole valid config. Sections are intentionally placed near top so user can find and modify all extra images and related volumes.
- Added sample for CMP sidecar plugin
- Added sample for K8s credential plugin
- Removed samples with Helm init container from incorrect controllers such as Dex
---
Note on DCO:
Checklist:
> docs(argo-cd): Improve documentation for extra containers

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/_helpers.tpl
- charts/argo-workflows/templates/controller/workflow-controller-deployment.yaml
- charts/argo-workflows/templates/server/server-deployment.yaml
We have a situation where we want to exclude the registry so that images can be pulled from in-network mirrors. Currently when you exclude the registry, you get stuck with a prefixing forward slash.
Had to keep the tags in the manifest files because helm template requires a colon in the image value.  Otherwise I'd move it into the helper function.
image entries changed: server, controller, executor
<details>
<summary>Example when registry is default `quay.io` like current:</summary>
```
✗ helm template --release-name argo-workflows -f values.yaml --namespace argo . --debug --include-crds | grep "image" -C2                                                14:12:08
install.go:192: [debug] Original chart version: ""
install.go:209: [debug] CHART PATH: …
```
> feat(argo-workflows): Add helper function to determine image value, minus tag

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/NOTES.txt
- charts/argo-cd/templates/argocd-application-controller/clusterrole.yaml
- charts/argo-cd/templates/argocd-application-controller/clusterrolebinding.yaml
- charts/argo-cd/templates/argocd-repo-server/clusterrole.yaml
- charts/argo-cd/templates/argocd-repo-server/clusterrolebinding.yaml
- charts/argo-cd/templates/argocd-server/clusterrole.yaml
- charts/argo-cd/templates/argocd-server/clusterrolebinding.yaml
- charts/argo-cd/values.yaml
Argo CD 2.5.0 introduced feature for managing applications in other namespaces and users are starting to look for a ways to disable cluster roles to have namespaced installation. This PR consolidates cluster-wide RBAC under single configuration key.
Closes: https://github.com/argoproj/argo-helm/issues/1592
---
Note on DCO:
Checklist:
> chore(argo-cd): Consolidate cluster-wide RBAC

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-application-controller/statefulset.yaml
- charts/argo-cd/templates/argocd-applicationset/deployment.yaml
- charts/argo-cd/templates/argocd-notifications/deployment.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/templates/dex/deployment.yaml
- charts/argo-cd/templates/redis/deployment.yaml
- charts/argo-cd/values.yaml
Resolves: https://github.com/argoproj/argo-helm/issues/1490
Allows users to create custom configuration structures for sidecars / init containers that can be templated with Helm values. Mainly intended for use with CMP plugins but is useful also for custom auth plugins that needs to be injected into multiple components.
Example use:
```yaml
busybox:
image:
repository: busybox
tag: latest
repoServer:
extraContainers:
- name: busybox
image: "{{ .Values.busybox.repository }}:{{ .Values.busybox.tag }}"
```
---
Note on DCO:
Checklist:
Changes are automatically published when merged to `main`. They are …
> feat(argo-cd): Allow templated values for init and extra containers

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/README.md.gotmpl
- charts/argo-cd/templates/NOTES.txt
- charts/argo-cd/templates/argocd-configs/argocd-ssh-known-hosts-cm.yaml
- charts/argo-cd/templates/argocd-configs/argocd-tls-certs-cm.yaml
- charts/argo-cd/values.yaml
Cleanup for SSH known hosts and repository TLS certificates
- Users do not need to known implementation details of confgmaps
- Consolidated into grouped sections with annotations
- Improved documentation for usage
---
Note on DCO:
Checklist:
> feat(argo-cd): Consolidate certificate config for repositories

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/NOTES.txt
- charts/argo-cd/templates/argocd-application-controller/statefulset.yaml
- charts/argo-cd/templates/argocd-applicationset/deployment.yaml
- charts/argo-cd/templates/argocd-notifications/deployment.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/aws/service.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/service.yaml
- charts/argo-cd/templates/dex/deployment.yaml
- charts/argo-cd/templates/redis/deployment.yaml
- charts/argo-cd/values.yaml
Container ports are now scattered on multiple places (individual variables, args, sometimes service ports). This PR moves all of them under containerPorts and clearly marks what does the port do. It also provides arguments to pods so the port is actually properly reconfigured.
---
Note on DCO:
Checklist:
> fix(argo-cd): Consolidate and fix container ports

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
> fix(argo-cd): Add missing options for mounting service account tokens

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/redis/service.yaml
Credit to https://github.com/argoproj/argo-helm/pull/1790 . This is opened to expedite this as soon as possible.
---
Note on DCO:
Checklist:
> fix(argo-cd): Redis service have invalid targetPort

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/redis/deployment.yaml
- charts/argo-cd/values.yaml
This PR moves Redis metrics exporter from metrics service to root configuration of redis component. Main reason is usability with other metrics collection mechanisms (service / pod discovery) and consistency with same sidecar in redis-ha component.
---
Note on DCO:
Checklist:
> chore(argo-cd): Decouple Redis exporter from metrics service

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-configs/argocd-ssh-known-hosts-cm.yaml
- charts/argo-cd/templates/argocd-configs/argocd-tls-certs-cm.yaml
Fixed copy & paste errors when adding new annotations options.
---
Note on DCO:
Checklist:
> fix(argo-cd): Fix annotations for ssh and tls configs

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
Upgrade exporter image that is long past due. New image is scanned for Log4Shell and Text4Shell vulnerabilities.
---
Note on DCO:
Checklist:
> chore(argo-cd): Upgrade Redis exporter image

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
Resolves:
- https://github.com/argoproj/argo-helm/issues/1796
After discussion with @mkilchhofer it was decided to disable redis exporter by default to not impact people running on ARM and use Redis image everywhere as it's geared toward enterprise use.
---
Note on DCO:
Checklist:
> fix(argo-cd): Disable Redis exporter by default

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
> chore(argo-cd): Upgrade redis to 7.0.7 to avoid CVE-2022-3996

- charts/argo-events/Chart.yaml
- charts/argo-events/templates/argo-events-controller/rbac.yaml
[Diff between 1.7.4 and 1.7.5](https://github.com/argoproj/argo-events/compare/v1.7.4...v1.7.5)
```
```
from [here](https://github.com/argoproj/argo-events/compare/v1.7.4...v1.7.5#diff-10c209cdb869ddd4c8a374b1db219d2473a6cade1ee8b04c4f80e0447d39563aR62)
Note on DCO:
Checklist:
> chore(argo-events): Upgrade Argo Events to v1.7.5

- CONTRIBUTING.md
relates to  https://github.com/argoproj/argo-helm/issues/1808. 
updated changelog structure worked, so I update doc. 🙋 
https://artifacthub.io/packages/helm/argo/argo-cd/5.19.12?modal=changelog&version=5.19.12
---
Note on DCO:
Checklist:
> fix(github): Align changelog structure to show changelogs on Artifact Hub

- charts/argo-workflows/Chart.yaml
relates https://github.com/argoproj/argo-helm/issues/1808 .
Let's move latest changelog structure. 🙋 
---
Note on DCO:
Checklist:
> fix(argo-workflows): Align changelog structure to show changelogs on Artifact Hub

- charts/argocd-image-updater/Chart.yaml
relates to #1808
Was fixed already for:
Note on DCO:
Checklist:
> fix(argocd-image-updater): Align changelog structure

- charts/argo-events/Chart.yaml
relates to #1808
Was fixed already for [argo-cd](https://github.com/argoproj/argo-helm/pull/1810) and [argo-workflows](https://github.com/argoproj/argo-helm/pull/1812)
Note on DCO:
Checklist:
> fix(argo-events): Align changelog structure

- charts/argo-rollouts/Chart.yaml
relates to #1808
Was fixed already for:
Note on DCO:
Checklist:
> fix(argo-rollouts): Align changelog structure

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/redis/pdb.yaml
Signed-off-by: ArsenyBelorukov <arsenig.n@gmail.com>
Note on DCO:
Checklist:
> fix(argo-cd):  fixed maxUnavailable value in redis-PDB

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-application-controller/statefulset.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/values.yaml
Add the possibility to configure dnsPolicy and hostNetwork on:
- argocd-application-controller
- argocd-repo-server
- argocd-server
On an EKS cluster with a custom CNI, `dnsPolicy` and `hostNetwork` need to be changed for metrics to be pulled.
ref:
- https://github.com/elastic/cloud-on-k8s/issues/1369
Without the possibility to change the `dnsPolicy` and `hostNetwork`, metrics pull can't work properly and returns a scraping error after trying to get metrics.
```
...
Error: There was an error scraping endpoint 10.6.9.5:8084/metrics: No connection adapters were found for '10.6.9.5:8084/metrics'
...
```
Note on DCO:
If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how …
> feat(argo-cd): Configurable `dnsPolicy` / `hostNetwork` 

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/NOTES.txt
- charts/argo-cd/templates/_helpers.tpl
- charts/argo-cd/templates/argocd-applicationset/deployment.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/templates/crds/crd-application.yaml
- charts/argo-cd/templates/crds/crd-applicationset.yaml
- charts/argo-cd/values.yaml
Upgrade to 2.6.0 stable version
Upgrade notes: https://argo-cd.readthedocs.io/en/latest/operator-manual/upgrading/2.5-2.6/
---
Note on DCO:
Checklist:
> feat(argo-cd): Upgrade Argo CD to 2.6.0

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/crds/crd-applicationset.yaml
> fix(argo-cd): Fix ApplicationSet CRD for pathParamPrefix 

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/controller/workflow-controller-cluster-roles.yaml
- charts/argo-workflows/templates/server/server-cluster-roles.yaml
Signed-off-by: Vlad Losev <vlad@losev.com>
This PR removes permissions that are not valid for particular sub-resources. The problem with granting such permissions is that they may be disallowed by various policies, including by Kubernetes's prohibition on escalating permissions by the user running `helm install`, which would cause the entire operation to fail. The `pods/exec` permission for the server is removed altogether as the server is not using this operation, AFAIK.
Closes #1650.
Checklist:
> fix(argo-workflows): clean subresource permissions

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/ingress.yaml
This change fixes a bug that prevents wildcards from being used in Ingress' `host`.
Currently there are no quotes surrounding the host, therefore it cannot begin with a wildcard, which should be possible as per [Ingress specification](https://kubernetes.io/docs/concepts/services-networking/ingress/#hostname-wildcards).
Note that without this quotes, hostnames starting with wildcard make the Helm Chart installation fail as follows:
```
Error: YAML parse error on argo-cd/templates/argocd-server/ingress.yaml: error converting YAML to JSON: yaml: line 26: did not find expected alphabetic or numeric character
helm.go:84: [debug] error converting YAML to JSON: yaml: line 26: did not find expected alphabetic or numeric character
YAML parse error on argo-cd/templates/argocd-server/ingress.yaml …
```
> fix(argo-cd): Add quotes on Ingress Host to allow wildcards

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/_helpers.tpl
Cosmetic change that groups all related component templates together.
---
Note on DCO:
Checklist:
> chore(argo-cd): Group component templates together

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-application-controller/statefulset.yaml
- charts/argo-cd/templates/argocd-applicationset/deployment.yaml
- charts/argo-cd/templates/argocd-notifications/deployment.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/templates/dex/deployment.yaml
- charts/argo-cd/templates/redis/deployment.yaml
- Added missing hostAliases sections
- Global configs grouped together
---
Note on DCO:
Checklist:
> chore(argo-cd): Add missing hostAliases to all components

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/templates/controller/workflow-controller-deployment.yaml
- charts/argo-workflows/templates/server/server-deployment.yaml
- charts/argo-workflows/values.yaml
Currently, the log format is always "text" (default) causing the logs to be marked as error on Stackdriver (https://github.com/argoproj/argo-workflows/issues/5135)
The format can be changed since this commit was merged: https://github.com/argoproj/argo-workflows/pull/5158/files
More specifically this line: https://github.com/argoproj/argo-workflows/pull/5158/files#diff-ac70cda72859a5b0b5cdeee97288452ad053332df4b27e37f9647addc0ef510eR72
The change on this PR adds a helm value to control the startup option --log-format 
Checklist:
> chore(argo-workflows): expose option to control the log format/level

- .github/workflows/lint-and-test.yml
Warning in GitHub Actions:
```
Warning: The `set-output` command is deprecated and will be disabled soon.
Please upgrade to using Environment Files. For more information see:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Warning: The `set-output` command is deprecated and will be disabled soon.
Please upgrade to using Environment Files. For more information see:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
[Live example](https://github.com/argoproj/argo-helm/actions/runs/4261993100/jobs/7419880783#step:6:20)
Note on DCO:
If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO …
> fix(github): Replace deprecated set-output from github-actions

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/role.yaml
As per issue #1866 , attempting to fix this by adding the relevant code to grant the pod/exec create permission to the argo-server Role when exec.enabled is True.
The argocd-server Role requires the pods/exec create permission in order to be able to start the web based terminal as per: https://argo-cd.readthedocs.io/en/stable/operator-manual/web_based_terminal/
This brings the Role in line with the ClusterRole change already made
Note on DCO:
Checklist:
> fix(argo-cd): Added pod exec permission to argo-server Role when exec.enabled is True.

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/role.yaml
Quick follow up with whitespace for https://github.com/argoproj/argo-helm/pull/1867
---
Note on DCO:
Checklist:
> fix(argo-cd): Fix indentation for argocd-server role

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/README.md.gotmpl
- charts/argo-cd/templates/_common.tpl
- charts/argo-cd/templates/argocd-application-controller/statefulset.yaml
- charts/argo-cd/templates/argocd-applicationset/deployment.yaml
- charts/argo-cd/templates/argocd-notifications/deployment.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/templates/dex/deployment.yaml
- charts/argo-cd/templates/redis/deployment.yaml
- charts/argo-cd/values.yaml
Closes: https://github.com/argoproj/argo-helm/issues/1775
Extended version of PR https://github.com/argoproj/argo-helm/pull/1776
- Added global scheduling options (nodeSelector, affinity, spreadTopologyConstraints, priorityClassName)
- Added missing options on component level
- Changed global affinity behaviour so it can be disabled when user prefer spreadTopologyConstraints for hierarchical topologies
---
Note on DCO:
Checklist:
> feat(argo-cd): Add additional global parameters for scheduling

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-applicationset/deployment.yaml
Fixes #1880
Note on DCO:
Checklist:
> fix(argo-cd): ApplicationSet deployment uses global tolerations

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/_helpers.tpl
Avoid rendering empty values to configmap (like `url: ''`) because it makes argo-cd application to be always out of sync.
Note on DCO:
Checklist:
cc @pupapaik
> fix(argo-cd): skip empty configmap params

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/redis/deployment.yaml
- charts/argo-cd/values.yaml
Added env parameter to redis exporter to allow add environment variables like REDIS_USER or REDIS_PASSWORD
Checklist:
> feat(argo-cd): add parameter env to redis exporter

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-configs/argocd-cmp-cm.yaml
- charts/argo-cd/values.yaml
Added ConfigMap creation bits named `argocd-cmp-cm` for Config Management Plugins using sidecar approach.
For an working example, you can run a kind cluster with ArgoCD setup under git repo [NIXKnight/ArgoCD-Demo](https://github.com/NIXKnight/ArgoCD-Demo/tree/NIXKnight/add-argocd-cmp-plugins-configmap) branch `NIXKnight/add-argocd-cmp-plugins-configmap` following the [README.md](https://github.com/NIXKnight/ArgoCD-Demo/blob/NIXKnight/add-argocd-cmp-plugins-configmap/README.md). The vault setup under the repo uses one of the plugins to deploy.
Note on DCO:
Checklist:
Changes are automatically …
> feat(argo-cd): Added Config Management Plugins cm

- .github/workflows/lint-and-test.yml
Resolves #1903 
Proven in with an additional PR:
- #1905
- https://github.com/argoproj/argo-helm/actions/runs/4425743927/jobs/7761180332
> <img width="840" alt="grafik" src="https://user-images.githubusercontent.com/7290987/225295697-16f01822-164e-4886-bee3-3202db836b67.png">
----
Note on DCO:
Checklist:
> ci(github): Fix CI testing

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
Resolves #1910 
Related to:
- https://github.com/argoproj/argo-helm/pull/1788 (mistakenly introduced)
- details https://github.com/argoproj/argo-helm/pull/1788/files#diff-1817bb061b5ceed1dabf4e30ac6445a132baa3884c3278be3e97d166a25e3a3bL294
- https://github.com/argoproj/argo-cd/blob/v2.6.5/common/common.go#L46-L52
---
Note on DCO:
Checklist:
> fix(argo-cd): Use default metrics port for APIServer

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/README.md.gotmpl
resolves https://github.com/argoproj/argo-helm/issues/1902 🙋 
---
Note on DCO:
Checklist:
> chore(argo-workflows): Add install guide on README

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/templates/controller/workflow-controller-cluster-roles.yaml
- charts/argo-workflows/values.yaml
Add `controller.rbac.writeConfigMaps` value that, if set to `true`, allows controller to create and update ConfigMaps (`false` by default). It enables memoization feature.
See: https://argoproj.github.io/argo-workflows/memoization/
Note on DCO:
Checklist:
> feat(argo-workflows): Add ability to use memoization

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/README.md
- charts/argo-rollouts/templates/controller/deployment.yaml
- charts/argo-rollouts/templates/dashboard/deployment.yaml
- charts/argo-rollouts/values.yaml
Hello 👋 
The current "global" `podAnnotations` config adds annotations to all pods, including the Dashboard if it is enabled. This PR gives us the ability to add pod annotations to controller & dashboard deployment separately.
The idea of this PR is similar to the one in ArgoCD's chart, in the future we probably have `global` section to include other configs as well if needed.
Note on DCO:
Checklist:
> feat(argo-rollouts): support setting pod annotations separately on controller and dashboard

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
resolves https://github.com/argoproj/argo-helm/issues/1945
---
Note on DCO:
Checklist:
> fix(argo-cd): Change default value for global.tolerations, from object to array

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/templates/controller/workflow-controller-deployment.yaml
- charts/argo-workflows/templates/server/server-deployment.yaml
- charts/argo-workflows/values.yaml
👋🏾 Hi there! Hoping this is a general-purpose enough change to be sensible to bring in. I'm using `external-secrets` to bring in my postgres TLS certs. Unfortunately, kubernetes has a [long-standing issue](https://github.com/kubernetes/kubernetes/issues/81089) with changing ownership of secrets. So for things like PostreSQL that take file permissions seriously, simply mounting the secret into the controller and server deployment won't work, as it's owned by root.
The simplest workaround I've seen used in the meantime is some sort of init container to chown/copy the secrets from the secret volume to some `emptyDir` or similar.
Note on DCO:
If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO …
> feat(argo-workflows): add the ability to declare initContainers

- charts/argo-workflows/Chart.yaml
release note: https://github.com/argoproj/argo-workflows/releases/tag/v3.4.7
Followed what was done in the last PR: https://github.com/argoproj/argo-helm/pull/1942
Note on DCO:
Checklist:
> chore(argo-workflows): Upgrade Argo Workflows to v3.4.7

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/controller/workflow-controller-cluster-roles.yaml
- charts/argo-workflows/templates/controller/workflow-controller-config-map.yaml
- charts/argo-workflows/templates/controller/workflow-controller-crb.yaml
- charts/argo-workflows/templates/controller/workflow-controller-deployment-pdb.yaml
- charts/argo-workflows/templates/controller/workflow-controller-deployment.yaml
- charts/argo-workflows/templates/controller/workflow-controller-sa.yaml
- charts/argo-workflows/templates/controller/workflow-controller-service.yaml
- charts/argo-workflows/templates/controller/workflow-controller-servicemonitor.yaml
- charts/argo-workflows/templates/server/server-cluster-roles.yaml
- charts/argo-workflows/templates/server/server-crb.yaml
- charts/argo-workflows/templates/server/server-deployment-pdb.yaml
- charts/argo-workflows/templates/server/server-deployment.yaml
- charts/argo-workflows/templates/server/server-ingress.yaml
- charts/argo-workflows/templates/server/server-sa.yaml
- charts/argo-workflows/templates/server/server-service.yaml
Resolves https://github.com/argoproj/argo-helm/issues/1952 .
Same change as https://github.com/argoproj/argo-helm/pull/1937 🙋 
`helm template` does not fulfill namespace field automatically to namespace scoped resources, so it would be trouble when users use Helm Chart via Terraform/Kustomize .
detail: https://github.com/argoproj/argo-helm/pull/1937#issuecomment-1503916625
---
Note on DCO:
Checklist:
> fix(argo-workflows): Add namespace field to all namespace scoped resources because `helm template` doesn't add the namespace filed automatically

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-configs/cluster-secrets.yaml
- charts/argo-cd/templates/argocd-configs/repository-credentials-secret.yaml
- charts/argo-cd/templates/argocd-configs/repository-secret.yaml
This was missed in PR #1937
Fixes:
- #1961
- #1962 
---
Note on DCO:
Checklist:
> fix(argo-cd): Evaluate namespace field via helm root scope

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/templates/controller/workflow-controller-cluster-roles.yaml
- charts/argo-workflows/values.yaml
Fixes #1966
Note on DCO:
Checklist:
I tested with a dummy template just for ease of showing my work.
For a given test template:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
name: test
rules:
{{- with .Values.rbac.secretWhitelist }}
- apiGroups:
- ""
resources:
- secrets
verbs:
- get
- list
- watch
resourceNames: {{- toYaml . | nindent 4 }}
{{- end }}
{{- if and (not .Values.rbac.secretWhitelist) (.Values.rbac.accessAllSecrets) }}
- apiGroups:
- ""
resources:
- secrets …
```
> feat(argo-workflows): Add option for controller to read all secrets

- .github/pull_request_template.md
Comment out two notational sentences in the PR template
- the DCO and publishing sentences are not filled out during PRs and are purely notational
- comment them out with HTML comments, as is common practice - example from a repo I maintain: https://github.com/ezolenko/rollup-plugin-typescript2/blob/f6db59613a66f58c48310aa8fa785951970b5d6d/.github/issue_template.md?plain=1#L2 - I copied that from other repos too
- these comments are still visible to the PR author, just not visible when rendered, keeping the PR more concise
Can see an example of what this looks like below vvv. If a maintainer clicks the edit button, will be able to see that the note is still there, just commented out and invisible when rendered.
I so happened to stumble upon this while writing a different PR #1974, and …
> docs(github): comment out notational pieces of PR template

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/templates/server/server-deployment-hpa.yaml
- charts/argo-workflows/templates/server/server-deployment.yaml
- charts/argo-workflows/values.yaml
Best practice to have an HPA for the Argo Server for HA. Docs on the topic: https://argoproj.github.io/argo-workflows/high-availability/#argo-server
- Similar to the existing HPA for Argo CD, with slight modifications for AWF naming etc
- Based off #240 except updated to latest version of templates
1. Add an optional VPA for the AWF Controller? (as it [can't scale horizontally](https://argoproj.github.io/argo-workflows/scaling/#horizontally-scaling))
* I can add that myself as well if wanted, but I know the Controller requires a bit more precision to scale, e.g. running a [hot-standby](https://argoproj.github.io/argo-workflows/high-availability/#workflow-controller) (`replicas` set to `2`) and swapping between the two while the Pod goes down to scale vertically
* [Example VPA Helm …
> feat(argo-workflows): add optional HPA to Server

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/README.md
- charts/argo-rollouts/templates/controller/servicemonitor.yaml
- charts/argo-rollouts/values.yaml
Adds support for configuring relabelings on the Service Monitor for the controller
Note on DCO:
Checklist:
> feat(argo-rollouts): add service monitor relabeling configs

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/templates/controller/workflow-controller-servicemonitor.yaml
- charts/argo-workflows/values.yaml
> feat(argo-workflows): add Prometheus ServiceMonitor relabelings, metricRelabelings & targetLabels

- charts/argocd-apps/Chart.yaml
- charts/argocd-apps/ci/applicationsets-values.yaml
- charts/argocd-apps/templates/applicationsets.yaml
Fixes #1978
- In ApplicationSet, I see no rational reason why project fields should be templated with the tpl function.
- Raised major version due to possible backward incompatibility.
Checklist:
> fix(argocd-apps): Changed the project field of the applicationset from a tpl to str(#1978)

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/templates/dashboard/clusterrole.yaml
> fix(argo-rollouts): Added missing permissions for argo rollouts dashboard cluster role

- charts/argo-cd/Chart.yaml
- release note: https://github.com/argoproj/argo-cd/releases/tag/v2.7.1
- diff: https://github.com/argoproj/argo-cd/compare/v2.7.0...v2.7.1
argo-helm uses `argocd-cmd-params-cm` CM for getting redis server info, so I think we do not need any actions except for version up. 🙋 
---
Checklist:
> chore(argo-cd): Update Argo CD to v2.7.1

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/_helpers.tpl
Helper fucntion copied from argo-cd helper functions [here](https://github.com/argoproj/argo-helm/blob/bb4d3154e63c89939c732ef89e404f2cba2f03e9/charts/argo-cd/templates/_versions.tpl#L12)
Function used [here](https://github.com/argoproj/argo-helm/blame/bb4d3154e63c89939c732ef89e404f2cba2f03e9/charts/argo-workflows/templates/server/server-deployment-hpa.yaml#L21) but missing.
Issue risen from community member @usulkies in CNCF slack [here](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1683204130449969).
ERROR
```
Error: template: argo-workflows/templates/server/server-deployment-hpa.yaml:21:19: 
executing "argo-workflows/templates/server/server-deployment-hpa.yaml" at 
<include "argo-workflows.apiVersion.autoscaling" $>: error calling include: 
template: no template …
```
> fix(argo-workflows): Add missing argo-workflows.apiVersion.autoscaling helper function for HPA configuration

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/templates/controller/workflow-controller-config-map.yaml
- charts/argo-workflows/values.yaml
> fix(argo-workflows): Drop .Values.useDefaultArtifactRepo flag to simplify usage

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/extra-manifests.yaml
> feat(argo-cd): allow extraObjects to contain string template

- .github/workflows/scorecard.yml
- README.md
Resolves #2008
Action/workflow file is autogenerated using the install docs: https://github.com/marketplace/actions/ossf-scorecard-action#installation
/cc: @eddie-knight 
---
Checklist:
> feat(github): Add OpenSSF Scorecard action

- charts/argo-events/Chart.yaml
- charts/argo-events/templates/extra-manifests.yaml
> feat(argo-events): allow extraObjects to contain string template

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/templates/extra-manifests.yaml
> feat(argo-rollouts): allow extraObjects to contain string template

- CODEOWNERS
- README.md
Error in `CODEOWNERS`
This is a follow-up of #2006.
We cleared out users who have not contributed in the last year and moved them to EMERITUS.md
We also created SECURITY.md
Checklist:
> fix(github): fix error in codeowners file and update README about security

- charts/argo-workflows/Chart.yaml
This will make the charts all look nice when you go to https://artifacthub.io/packages/search?repo=argo&sort=relevance&page=1
Current view on artifacthub:
Before argo-workflows chart image:
After argo-workflows chart image:
Checklist:
> fix(argo-workflows): change chart icon to match other charts

- charts/argo-events/Chart.yaml
This will make the charts all look nice when you go to https://artifacthub.io/packages/search?repo=argo&sort=relevance&page=1
Before argo-events chart icon:
After argo-events chart icon:
Checklist:
> chore(argo-events): Update chart icon to standard image

- charts/argo-events/Chart.yaml
This is to get latest argo-workflows chart version out to artifacthub.
Can't get the previous ones that had incorrect kinds.
argoproj#2030 adds linting so this doesn't happen again. Will merge after argo-workflows and argo-events charts are fixed.
Checklist:
> fix(argo-events): use correct artifacthub annotation kind

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/crds/argoproj.io_clusterworkflowtemplates.yaml
Fix for https://github.com/argoproj/argo-helm/issues/1925
Checklist:
> fix(argo-workflows): fix clusterworkflowtemplates disabled flag

- .github/configs/cr.yaml
- .github/workflows/publish.yml
Resolves #2024
Testing is done in my own fork:
- https://github.com/mkilchhofer/argo-helm/actions/runs/4936959739/jobs/8825497141 (Releasing workflow in action)
- https://github.com/mkilchhofer/argo-helm/commit/0e71a6efab0253db20a61d13eaca7cbb9fd0927c (Commit implementing chart signing)
The newly required secrets are already in place:
---
Checklist:
> feat(github): Introduce chart signing

- CODEOWNERS
At the requets of @jmeridth I have popped my name down on the products I'm most familiiar with to offer my services in reviewing/fixing helm things.
Checklist:
> chore(github): Add tico24 to codeowners

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/controller/workflow-controller-config-map.yaml
- charts/argo-workflows/templates/controller/workflow-controller-deployment.yaml
- charts/argo-workflows/templates/server/server-deployment.yaml
- charts/argo-workflows/values.yaml
Templating is not supported for several variables in the Argo Workflows helm chart.
The `values.yaml` file is hinting at it, but the current charts would not support it...
So I've also updated the `values.yaml` file to indicate the correct usage (which works together with the other changes of this PR)
```
---    # name: <releaseName>-minio
+++ name: "{{ .Release.Name }}-minio"
```
Opened this PR as a replacement for https://github.com/argoproj/argo-helm/pull/2003 which I messed up a bit while rebasing/merging different remote origins.
Checklist:
> fix(argo-workflows): Fix templating in several places

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/extra-manifests.yaml
> feat(argo-workflows): allow extraObjects to contain string template

- artifacthub-repo.yml
Base on converation had [here](https://github.com/artifacthub/hub/issues/3052#issuecomment-1543770355)
This should finalize our getting our argo artifacthub project marked as official
Checklist:
> fix(github): ignore argo-lite package so we can finalize artifacthub official-ness

- .github/workflows/scorecard.yml
Fixes #2055
Only disabled the Scorecard action as all other workflows only consumes the generic GITHUB_TOKEN which should work in forks.
---
Checklist:
> fix(github): Don't run Scorecard analysis on forked repos

- charts/argo-cd/Chart.lock
- charts/argo-cd/Chart.yaml
I take over https://github.com/argoproj/argo-helm/pull/1879 . 🙋 
It seems there is no breaking change... 👀 
ref: https://github.com/DandyDeveloper/charts/commits/master/charts/redis-ha
---
Checklist:
> chore(argo-cd): Update redis-ha to v4.23.0

- charts/argo-cd/Chart.yaml
- charts/argo-cd/values.yaml
> feat(argo-cd): Add new BitbucketCloud ssh keys in values.yaml

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/role.yaml
> fix(argo-cd): don't request applicationsets if its disabled

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/dex/deployment.yaml
relates to https://github.com/argoproj/argo-helm/issues/2019 (, though I think this is not a root cause... 🤔 )
---
Checklist:
> fix(argo-cd): Align with upstream dex initContainers

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-application-controller/statefulset.yaml
- charts/argo-cd/templates/argocd-applicationset/deployment.yaml
- charts/argo-cd/templates/argocd-notifications/deployment.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/templates/dex/deployment.yaml
- charts/argo-cd/templates/redis/deployment.yaml
- charts/argo-cd/values.yaml
Use `with` so (parts of) the securityContext can be `null`ed out. Fixes https://github.com/argoproj/argo-helm/issues/2071
Checklist:
> fix(argo-cd): Allow to disable containerSecurityContext

- charts/argo-workflows/Chart.yaml
https://github.com/argoproj/argo-workflows/releases/tag/v3.4.8
includes this PR upstream
Checklist:
> chore(argo-workflows): upgrade argo workflows to v3.4.8

- charts/argo-cd/Chart.yaml
- charts/argo-cd/values.yaml
release note: https://github.com/argoproj/argo-cd/releases/tag/v2.7.4
diff: https://github.com/argoproj/argo-cd/compare/v2.7.3...v2.7.4
---
Checklist:
> chore(argo-cd): Upgrade Argo CD to v2.7.4

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/README.md.gotmpl
- charts/argo-workflows/templates/controller/workflow-controller-config-map.yaml
- charts/argo-workflows/values.yaml
This adds support for populating the `columns` field in the workflow controller config map. The feature was added to argo workflows in this PR: https://github.com/argoproj/argo-workflows/pull/10693
Checklist:
> feat(argo-workflows): Add support for UI columns configuration

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/redis/deployment.yaml
The current Argo-cd redis deployment does not allow to specify the redis.conf file because the extraEnv variables are appended at the end. 
The `redis-server` command requires the variable of the redis.conf file to be the first argument.
This Pull requests modifies the order of the extraEnvVars to place them before so the redis.conf file can be set in there.
Checklist:
> fix(argo-cd): Allow specify redis config file

- charts/argo-cd/Chart.yaml
Will fail until the image actually exists.  This is me prepping for that. :smile:
Current diff, subject to change:
https://github.com/argoproj/argo-cd/compare/v2.7.4...release-2.7
Includes CVE fixes
Checklist:
> chore(argo-cd): upgrade argo-cd to v2.7.5

- .github/configs/cr.yaml
Checklist:
Fixes #1721 
Enables release note generation via an [option](https://github.com/helm/chart-releaser#create-github-releases-from-helm-chart-packages) provided by `chart-releaser`. `chart-releaser` uses GitHub's feature for automatic release note generation (https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes).
> chore(github): Generate release notes

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/extra-manifests.yaml
`helm lint` fails with `extraObjects` defined.
```
Adding repo argocd https://argoproj.github.io/argo-helm
"argocd" has been added to your repositories
Fetching argocd/argo-cd
Linting release=argocd, chart=/var/folders/6v/cdcp2ltn42j79tbmktqpfbyr0000gq/T/helmfile2380798123/argocd/argocd/argocd/argo-cd/5.34.6/argo-cd
==> Linting /var/folders/6v/cdcp2ltn42j79tbmktqpfbyr0000gq/T/helmfile2380798123/argocd/argocd/argocd/argo-cd/5.34.6/argo-cd
[ERROR] templates/extra-manifests.yaml: unable to parse YAML: invalid Yaml document separator: apiVersion: generators.external-secrets.io/v1alpha1
[ERROR] templates/extra-manifests.yaml: unable to parse YAML: invalid Yaml document separator: apiVersion: external-secrets.io/v1beta1
[ERROR] templates/extra-manifests.yaml: unable to parse YAML: invalid Yaml …
```
> fix(argo-cd): helm lint error when `extraObjects` is defined

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/_common.tpl
resolves https://github.com/argoproj/argo-helm/issues/2118 🙋 
Checklist:
> chore(argo-cd): Add `app.kubernetes.io/version` label

- charts/argo-cd/Chart.yaml
release note: https://github.com/argoproj/argo-cd/releases/tag/v2.7.6
diff: https://github.com/argoproj/argo-cd/compare/v2.7.5...v2.7.6
Checklist:
> chore(argo-cd): Upgrade Argo CD to v2.7.6

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
Change `applicatiosetSet.conteinerPorts.metrics` to 8085 so that it matches `applicationSet.metrics.port`
Checklist:
> fix(argo-cd): Default applicationSet metrics port to 8085

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/server/server-crb.yaml
Currently, because the creation of ServiceAccount is included in the conditions for creating ClusterRoleBinding in argo-workflows-server, it is not possible to create only ClusterRoleBinding in a case where ServiceAccount is not created in helm. 
Modify so that ClusterRoleBinding is created if `rbac: true` is set even in the case where ServiceAccount is not created.
This is my first commit to this repository, so please let me know if I am doing something wrong!
Checklist:
> fix(argo-workflows): Change argo-workflows-server crb creation conditions

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-notifications/deployment.yaml
https://github.com/argoproj/argo-cd/pull/13605 introduced two new environment variables that allow a user to configure the log-level of argo-notifications-controller similar to how other Argo controllers are configured.  This PR adds those environment variables to the notifications _Deployment_ -- similar to how they exist for other controller's _Deployments_.
Checklist:
> feat(argo-cd): Add support for configuring argo-notifications log level and format

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/aws/service.yaml
> fix(argo-cd): fix gRPC service target port

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-server/certificate.yaml
- charts/argo-cd/values.yaml
Issue ref: https://github.com/argoproj/argo-helm/issues/2142
Checklist:
* [V] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [V] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [V] Any new values are backwards compatible and/or have sensible default.
* [V] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
> fix(argo-cd): Add usages to ArgoCD server certificate

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/_common.tpl
- Convert `$preset.type` to string to prevent an "incompatible types for comparison" when no strategy are defined
Checklist:
> fix(argo-cd): Update `argo-cd.strategy` template

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/_helpers.tpl
Remove necessary create entry in `argocd-cmd-params-cm` ConfigMap introduce in #2129
Checklist:
> feat(argo-cd): remove necessary create entry in `argocd-cmd-params-cm` ConfigMap

- charts/argocd-apps/Chart.yaml
- charts/argocd-apps/templates/projects.yaml
- charts/argocd-apps/values.yaml
This flag was added in this PR https://github.com/argoproj/argo-cd/pull/10237/files but is not possible to set it using the argocd-apps chart.
- It adds this flag as a value of the chart for projects in argocd-apps
```
echo "projects:                                                                                                                                                                                                                                                         (⎈ |kind-hnc:hnc-system)
- name: orka-extensibility
namespace: cre-system
description: orka-extensibility
clusterResourceWhitelist:
- group: '*'
kind: '*'
destinations:
- namespace: '*'
server: '*'
orphanedResources:
warn: true
sourceRepos:
- '*'
roles:
- name: read-only
description: Read-only privileges to …
```
> feat(argocd-apps): add permitOnlyProjectScopedClusters flag

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/dex/deployment.yaml
- charts/argo-cd/values.yaml
Motivation:
The dex server, when running, can use as little as 1m CPU and 38Mi of memory:
```
> kubectl -n argocd top pod argo-cd-argocd-dex-server-549f5d748c-q8fmq
NAME                                         CPU(cores)   MEMORY(bytes)   
argo-cd-argocd-dex-server-549f5d748c-q8fmq   1m           38Mi            
```
However, using a low resource spec to match said usage, the init container can crash with an OOMKilled, leading to crashloopbackoffs from Dex:
```
argo-cd-argocd-dex-server-99794466c-d7zvr                   0/1     Init:OOMKilled      0                12s
```
Configuring the resources separately allows us to avoid the OOMKilled but also not overcommit resources to the long-running Dex server. I've made the change backwards compatible: it will fallback to Dex's resources in …
> feat(argo-cd): Allow configuring Dex's init image resources separately

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/_common.tpl
Checklist:
Before:
```console
$ helm template  charts/argo-cd/ | grep /version | head -1
app.kubernetes.io/version: v2.7.7
$   # ^^^ This one is valid
$ helm template --set global.image.tag=v2.7.5@sha256:d93e1c2fa8c806b339d9288a4de59bff293f2f81e8efbcb charts/argo-cd/ | grep /version | head -1
app.kubernetes.io/version: v2.7.5@sha256:d93e1c2fa8c806b339d9288a4de59bff293f2f81e8efbcb
$   # ^^^ This one is invalid!
```
After:
```console
$ helm template  charts/argo-cd/ | grep /version | head -1
app.kubernetes.io/version: "v2.7.7"
$   # ^^^ This one is valid, and unchanged
$ helm template --set global.image.tag=.v2.7.5@sha256:d93e1c2fa8c806b339d9288a4de59bff293f2f81e8efbcb. charts/argo-cd/ | grep /version | head -1
app.kubernetes.io/version: …
```
> fix(argo-cd): Ensure `app.kubernetes.io/version` label is valid

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-repo-server/hpa.yaml
- charts/argo-cd/templates/argocd-server/hpa.yaml
- charts/argo-cd/values.yaml
Fixes #2152 
Accepts a user defined list of HPA metrics for the server and repoServer HPA when autoscaling/HA is enabled. There is no change to current behavior, which defaults to use the Resource metrics for CPU and memory. Because the metrics is block is highly configurable I've opted to just take the entire block as user provided yaml - the user must provide the full and correct syntax.
Checklist:
> feat(argo-cd): allow configurable hpa metrics

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/templates/crds/rollout-crd.yaml
Upgrade Argo Rollouts to v1.5.1
release: https://github.com/argoproj/argo-rollouts/releases/tag/v1.5.1
diff: https://github.com/argoproj/argo-rollouts/compare/v1.5.0...v1.5.1
Checklist:
> feat(argo-rollouts): Upgrade Argo Rollouts to v1.5.1

- EMERITUS.md
Use a table to list all Emeritus names and GH usernames
- matches how [`argoproj` lists Alumni](https://github.com/argoproj/argoproj/blob/6011d3e17300d4b642a1ab5bdb3551c5f6da9021/MAINTAINERS.md?plain=1#L56)
- IMO, this feels a bit more formal/respectful to me as well than just a username with no link etc, but that's just my opinion
- though it has more details including role and affiliation. could do that here too, but I don't know what all those are, so left those columns out
- fortunately everyone's name was listed on their profile, so just copy+paste those! 
- See [Markdown Preview](https://github.com/argoproj/argo-helm/blob/14fdf91e7e3bf6c68b3b2add7c2a3a34f96afea9/EMERITUS.md)
- confirmed that all profile links work
Checklist:
* [n/a] I have bumped the chart version according to …
> chore(github): use table for Emeritus

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/README.md
- charts/argo-rollouts/templates/controller/metrics-service.yaml
- charts/argo-rollouts/values.yaml
https://argoproj.github.io/argo-rollouts/features/controller-metrics/
according to the current documentation annotations are assigned not only to the argo-rollouts-metrics service but to argo-rollouts-dashboard which is not correct.
```
serviceAnnotations:
prometheus.io/scrape: "true"
prometheus.io/path: /metrics
prometheus.io/port: "8090"
```
result:
```
apiVersion: v1
kind: Service
metadata:
name: argo-rollouts-dashboard
namespace: "argo-cd"
labels:
app.kubernetes.io/component: rollouts-dashboard
helm.sh/chart: argo-rollouts-2.30.1
app.kubernetes.io/name: argo-rollouts
app.kubernetes.io/instance: argo-rollouts
app.kubernetes.io/version: "v1.5.0"
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/part-of: argo-rollouts
annotations:
+     prometheus.io/path: /metrics
+ …
```
> fix(argo-rollouts): Use annotation cont metrics

- charts/argo-cd/Chart.yaml
Tag: https://github.com/argoproj/argo-cd/releases/tag/v2.7.9
Diff: https://github.com/argoproj/argo-cd/compare/v2.7.8...v2.7.9
Checklist:
> chore(argo-cd): Upgrade Argo CD to v2.7.9

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-configs/argocd-notifications-secret.yaml
- charts/argo-cd/values.yaml
> feat(argo-cd): add labels to notifications secret (#2191)

- charts/argo-cd/Chart.yaml
release note: https://github.com/argoproj/argo-cd/releases/tag/v2.7.10
diff: https://github.com/argoproj/argo-cd/compare/v2.7.9...v2.7.10
Checklist:
> chore(argo-cd): Upgrade Argo CD to v2.7.10

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/_helpers.tpl
Resolves:
https://github.com/argoproj/argo-helm/issues/2202
Explanation:
Helm treats text value of `repoServer.log.level` and similar keys as a map that will return a false for simple test `{{ hasKey  $presets "repoServer.log.level" }}`. To force correct behaviour items must be stored in the dict before serialization.
Checklist:
> fix(argo-cd): Template configuration keys as a string instead of map

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/templates/controller/clusterrole.yaml
- charts/argo-rollouts/templates/controller/role.yaml
Resolves https://github.com/argoproj/argo-helm/issues/2101 🙋 
Following upstream https://github.com/argoproj/argo-rollouts/pull/2933 . 
Checklist:
> fix(argo-rollouts): Add required ingress permission

- .github/workflows/publish.yml
This PR add support to create OCI helm charts. No new feature is added to the existing Helm charts.
This PR continues #1768
Checklist:
> feat(github): add Helm OCI support

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/clusterrole.yaml
> fix(argo-cd): add missing permissions to run actions

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/server/server-cluster-roles.yaml
As part of my root cause analysis in https://github.com/argoproj/argo-helm/issues/2159#issuecomment-1646988596, discovered that the Server had some no longer needed RBAC for Secrets
- as of https://github.com/argoproj/argo-workflows/pull/8555, the Server no longer needs `list` or `watch` and only uses `get`
- this was released as part of [v3.4.0](https://github.com/argoproj/argo-workflows/blob/master/CHANGELOG.md#v340-rc1-2022-08-09), and the current version of the chart uses [v3.4.9](https://github.com/argoproj/argo-helm/blob/3e35b0c7f7d758d553b17f369cc5940484ef5d89/charts/argo-workflows/Chart.yaml#L2)
- `update` is not needed either for SSO secret
- [manifests RBAC](https://github.com/argoproj/argo-workflows/blob/a68ea0feabc87c09d5e13d12e6f0d1a61adc5b16/manifests/cluster-install/argo-ser …
> fix(argo-workflows): Server only needs `get` Secrets

- charts/argo-cd/Chart.yaml
- charts/argo-cd/values.yaml
I believe this key is deprecated and the comment is misleading
Checklist:
> docs(argo-cd): Rename comment of repositoryCredentials to credentialTemplates

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/README.md
- charts/argo-rollouts/templates/controller/servicemonitor.yaml
- charts/argo-rollouts/values.yaml
> feat(argo-rollouts): update servicemonitor.yaml to allow for namespace to be set

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/crds/argoproj.io_workflowtaskresults.yaml
- charts/argo-workflows/values.yaml
> chore(argo-workflows): update comment for azure artifact repository blobNameFormat

- charts/argo-cd/Chart.yaml
release note: https://github.com/argoproj/argo-cd/releases/tag/v2.8.2
diff: https://github.com/argoproj/argo-cd/compare/v2.8.1...v2.8.2
Checklist:
> chore(argo-cd): Upgrade Argo CD to v2.8.2

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
Resolves: https://github.com/argoproj/argo-helm/issues/2233
We should upgrade this as image is over 6 months old
Checklist:
> chore(argo-cd): Upgrade redis-exporter to 1.53.0

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/NOTES.txt
- charts/argo-cd/templates/_versions.tpl
- charts/argo-cd/templates/argocd-applicationset/certificate.yaml
- charts/argo-cd/templates/argocd-server/certificate.yaml
- charts/argo-cd/values.yaml
It's no longer possible to install older cert-manager as beta version of CRD were removed in K8s 1.22
Checklist:
> chore(argo-cd): Remove support for legacy cert-manager APIs

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/NOTES.txt
- charts/argo-cd/templates/_versions.tpl
- charts/argo-cd/templates/argocd-repo-server/hpa.yaml
- charts/argo-cd/templates/argocd-server/hpa.yaml
- charts/argo-cd/values.yaml
API version autoscaling/v2 is GA since 1.23 which is now minimum K8s version. We can safely remove this backward compatibility feature as no longer needed.
Checklist:
> chore(argo-cd): Remove support for autoscaling/v1

- charts/argo-cd/Chart.yaml
- charts/argo-cd/values.yaml
.nav-bar is no longer the css class name. Found used the inspect tool in firefox:
Last tested in Argo CD v2.8.2+dbdfc71
Update: realized it's already updated in the docs here: https://argo-cd.readthedocs.io/en/stable/operator-manual/custom-styles/
Checklist:
> fix(argo-cd): Update values.yaml - update custom css styles side bar example

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/templates/crds/analysis-run-crd.yaml
- charts/argo-rollouts/templates/crds/analysis-template-crd.yaml
- charts/argo-rollouts/templates/crds/cluster-analysis-template-crd.yaml
- charts/argo-rollouts/templates/crds/experiment-crd.yaml
- charts/argo-rollouts/templates/crds/rollout-crd.yaml
Release: https://github.com/argoproj/argo-rollouts/releases/tag/v1.6.0
Changelog: https://github.com/argoproj/argo-rollouts/blob/master/CHANGELOG.md#v160-2023-09-05
Checklist:
> chore(argo-rollouts): Upgrade Argo Rollouts to v1.6.0

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/ingress.yaml
> fix(argo-cd): Make the PathType configurable when using single ingress resource in AWS

- charts/argo-workflows/Chart.yaml
release note: https://github.com/argoproj/argo-workflows/releases/tag/v3.4.11
diff: https://github.com/argoproj/argo-workflows/compare/v3.4.10...v3.4.11
Checklist:
> chore(argo-workflows): Upgrade Argo Workflows to v3.4.11

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-application-controller/statefulset.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
Resolves part of https://github.com/argoproj/argo-helm/issues/2221 .
*I didn't have confidence about secret, so l only added checksum of argocd-cm to argocd-repo-server and argocd-application-controller.
Checklist:
> fix(argo-cd): Restart Repo Server and Application Controller as following the change of Argo CD CM

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/values.yaml
- Adds a toggle to be able to turn off the helm-working-dir for the repo server deployment. Using a shared helm repo storage directory can cause issues when multiple helm commands are being run in parallel. The repo server also has the ability to rebuild the repos and do updates in the normal flow for checking the status of an application so it won't cause issues if it's disabled.
We've been having issues with collisions happening in the shared helm-working-dir and with the index.yaml file being empty when read by one of the processes. The repo server code is setup to rebuild the repo and do a chart build for each templating run for us so it makes more sense to allow it to utilize the temporary space. I didn't want to remove it for everyone so I made the default to enabled with the option …
> feat(argo-cd): adds toggle for helm-working-dir

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/_helpers.tpl
resolves https://github.com/argoproj/argo-helm/issues/2260
Checklist:
> fix(argo-cd): Migrate leftover of applicationSet.replicaCount to applicationSet.replicas

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/README.md.gotmpl
* clarify 5.19.0 changes
* revise wording
Checklist:
> docs(argo-cd): improve changelog

- CONTRIBUTING.md
> fix(github): Fix changelog spelling of versions

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/clusterrole.yaml
release note: https://github.com/argoproj/argo-cd/releases/tag/v2.8.4
diff: https://github.com/argoproj/argo-cd/compare/v2.8.3...v2.8.4
Checklist:
> chore(argo-cd): Upgrade Argo CD to v2.8.4

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
Resolves https://github.com/argoproj/argo-helm/issues/2265 .
Checklist:
> fix(argo-cd): Align redis-ha's affinity type to upstream due to warnings

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/servicemonitor.yaml
Currently, if no annotations are specified, ArgoCD will want to sync a resource with annotations: null in there, which is automatically removed by the API server. The rest of the services from ArgoCD do not have this issue, since the annotations attribute itself is conditional to annotations being there.
This applies the same change to ArgoCD server.
Prevents this:
Checklist:
> fix(argo-cd): make ServiceMonitor annotations in ArgoCD server conditional

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
This helm chart defines the plugins as ConfigMaps -- according to the docs, when the CM is modified, the repo-server Pod must be restarted to have the sidecars pick up the latest changes:
https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins/#debugging-a-cmp
The changes in this helm chart allow for a checksum to be calculated from the ConfigMap and added as a Pod annotation so whenever the CM values are modified, the Pod is restarted automatically.
Checklist:
> fix(argo-cd): Add checksum for CMP ConfigMap in repo-server Pod annotations

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
> fix(argo-cd): Redis to 7.0.13 to fix CVE-2022-48174

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/controller/workflow-aggregate-roles.yaml
Add in all crds to aggregate roles
Checklist:
> fix(argo-workflows): add all crds to aggregate-roles template

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-application-controller/statefulset.yaml
- charts/argo-cd/templates/argocd-applicationset/deployment.yaml
- charts/argo-cd/templates/argocd-notifications/deployment.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/templates/dex/deployment.yaml
- charts/argo-cd/templates/redis/deployment.yaml
- charts/argo-cd/values.yaml
Signed-off-by: toyamagu-2021 <toyamagu2021@gmail.com>
* Add `terminationGracePeriodSeconds` for each Deployment/StatefulSet
* default is 30 [official document](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination)
* No default value in argo-cd repo except redis-ha 
* For us, set in [redis-ha helm repo](https://github.com/DandyDeveloper/charts/blob/e12198606457c7281cd60bd1ed41bd8b0a34cd53/charts/redis-ha/values.yaml#L246)
* [argo-cd search](https://github.com/search?q=repo%3Aargoproj%2Fargo-cd+terminationGracePeriodSeconds+path%3Amanifests&type=code)
* Can be set `terminationGracePeriodSeconds` by installing
* `helm upgrade -i argocd-termination-graceful-period-seconds . -n argocd --values ./ci/default-values.yaml`
Checklist:
> feat(argo-cd): add terminationGracePeriodSeconds

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-notifications/deployment.yaml
release not: https://github.com/argoproj/argo-cd/releases/tag/v2.8.5
diff: https://github.com/argoproj/argo-cd/compare/v2.8.4...v2.8.5
Checklist:
> chore(argo-cd): Upgrade Argo CD to v2.8.5

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-notifications/clusterrole.yaml
- charts/argo-cd/templates/argocd-notifications/clusterrolebinding.yaml
- charts/argo-cd/values.yaml
Closes #2319
Checklist:
Based on this commit from upstream https://github.com/argoproj/argo-cd/compare/v2.8.4...v2.8.5#diff-9b67c714fa7e685352f63e4cd04d71a150f195f1363d5311de1a2c30dff40c14. after upgrading to 2.8.5, notif controller started to error with:
```
message:E1029 16:48:32.856047 7 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: failed to list applications: applications.argoproj.io is forbidden: User "system:serviceaccount:argocd-prod:argocd-notifications-controller" cannot list resource "applications" in API group "argoproj.io" at the cluster scope
```
> feat(argo-cd): add notification cluster role

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/templates/crds/analysis-run-crd.yaml
Fixes #2316
[Upstream CRD](https://github.com/argoproj/argo-rollouts/blob/master/manifests/crds/analysis-template-crd.yaml)
Checklist:
> fix(argo-rollouts): Update AnalysisRun CRD to match upstream

- .github/workflows/lint-and-test.yml
- scripts/lint.sh
Getting failure when running chart testing action pulling v2.0.0 from sigstore
Updating action to see if this helps
Error [here](https://github.com/argoproj/argo-helm/actions/runs/6709281657/job/18232558679)
Checklist:
> fix(github): update chart testing action due to failure

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-notifications/clusterrole.yaml
- charts/argo-cd/templates/argocd-notifications/clusterrolebinding.yaml
This PR created by following comment https://github.com/argoproj/argo-helm/pull/2315#issuecomment-1790049879
Checklist:
> fix(argo-cd): Create notifications clusterrole and clusterrolebinding when enabled

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/values.yaml
Branch got renamed, this change prevents the redirect.
Checklist:
> fix(argo-workflows): Fix outdated URL in values.yaml comments

- charts/argo-workflows/Chart.yaml
release note: https://github.com/argoproj/argo-workflows/releases/tag/v3.5.1
diff: https://github.com/argoproj/argo-workflows/compare/v3.5.0...v3.5.1
Checklist:
> chore(argo-workflows): Upgrade Argo Workflows to v3.5.1

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-applicationset/deployment.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/clusterrole.yaml
- charts/argo-cd/templates/crds/crd-application.yaml
- charts/argo-cd/templates/crds/crd-applicationset.yaml
Notes:
Please check upstream PR https://github.com/argoproj/argo-cd/commit/cb25382658e9d3aa98e23c2a22a9b3314e27d462 that changes how the sharding works. As this is currently alpha feature with patch to StatefulSet that is changing it back to Deployment with warning this might change again, I'm not sure if / when we want to support this.
Checklist:
> feat(argo-cd): Upgrade Argo CD to 2.9.0

- .clomonitor.yml
- CONTRIBUTING.md
- README.md
- SECURITY-INSIGHTS.yml
> chore(github): Updated security documentation and CLOMonitor exemptions

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/templates/NOTES.txt
- charts/argo-workflows/templates/server/server-deployment.yaml
- charts/argo-workflows/values.yaml
Auth mode is supposed to accept multi values, so I fixed it.
Ref: https://github.com/argoproj/argo-helm/pull/2291#issuecomment-1798864481
Checklist:
> fix(argo-workflows): Accept multi auth mode for server

- .github/CODEOWNERS
yu-cruco is now a maintainer and will be notified on all PRs
Checklist:
> chore(github): Add yu-cruco to * in CODEOWNERS

- charts/argo-rollouts/Chart.yaml
> chore(argo-rollouts): Bump rollouts to 1.6.1

- charts/argo-rollouts/Chart.yaml
> chore(argo-rollouts): Bump rollouts to 1.6.2

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/templates/controller/workflow-controller-deployment.yaml
- charts/argo-workflows/templates/server/server-deployment.yaml
- charts/argo-workflows/values.yaml
> fix(argo-workflows): Add parameters for tuning revisionHistoryLimit and emptyDir volumes

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/controller/workflow-controller-service.yaml
resolves https://github.com/argoproj/argo-helm/issues/2335
Checklist:
> fix(argo-workflows): Align version label

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/ci/enable-ingress-values.yaml
The presence of a xip.io url was confusing to some inexperienced users who thought it a legitimate URL to use to set up Argo Workflows.
To compound matters, xip.io has been offline for a while, so it's evident that the tests don't actually make use of the URL anyway.
This PR changes the url to a placeholder to reduce the confusion.
Checklist:
> chore(argo-workflows): Remove xip url from test to avoid confusion

- charts/argo-cd/Chart.yaml
- charts/argo-cd/values.yaml
While reviewing https://github.com/argoproj/argo-helm/pull/2350 I checked for other occurrences of non-existing example URLs.
---
Checklist:
> chore(argo-cd): Replace non-existing examples with official example domain

- charts/argo-workflows/Chart.yaml
release note: https://github.com/argoproj/argo-workflows/releases/tag/v3.5.2
diff: https://github.com/argoproj/argo-workflows/compare/v3.5.1...v3.5.2
Checklist:
> chore(argo-workflows): Upgrade Argo Workflows to v3.5.2

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/templates/crds/analysis-template-crd.yaml
- charts/argo-rollouts/templates/crds/cluster-analysis-template-crd.yaml
Apparently this PR https://github.com/argoproj/argo-helm/pull/2320/files fixed only `AnalysisRun` spec, but we have more changes in the mainstream.
Checklist:
> fix(argo-rollouts): Update all rollout CRDs to match upstream

- README.md
I think the sentence applies to all Argo projects.
Does this require the checklist items?
Checklist:
> docs(github): remove unnecessary qualifier in README

- charts/argo-cd/Chart.yaml
release note: https://github.com/argoproj/argo-cd/releases/tag/v2.9.3
diff: https://github.com/argoproj/argo-cd/compare/v2.9.2...v2.9.3
Checklist:
> chore(argo-cd): Upgrade Argo CD to v2.9.3

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/controller/workflow-role.yaml
Resolves https://github.com/argoproj/argo-helm/issues/2366 🙋 
Checklist:
> fix(argo-workflows): Add missing permission to workflow role

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/values.yaml
Checklist:
This change deletes explicit configuration of the OAuth redirect URL, which was suppressing [automatic configuration](https://github.com/argoproj/argo-workflows/blob/64ee6ae9b674795c114bd66d5b6bdd45be093e9a/server/auth/sso/sso.go#L380) of the redirect URL in the server. The default URL is incorrect for most installations anyway, which means the users cannot use the default, which is inconvenient.
> fix(argo-workflows): Fix OAuth redirect URL autoconfig.

- .github/workflows/chart-version-bump.yml
- renovate.json
oh boy..
So bad news first. this won't "just work". Someone with repo permissions will need to set up renovate, and probably polish off the final step of the github action (the one that pushes the changes back to the PR).z
Renovate should be available as an app for the repo, it was enabled for all argoproj projects to my knowedge.
When set up, renovate will
- create a PR whenever an upstream project releases something.
- create the PR title in a format friendly to our linter
- bump the chart version by +1 patch version
- update the release notes
it won't:
- Hunt for any changes in the upstream release (eg crd changes). You'll have to check out the branch and add to it.
- automerge the pr into main
- bump the chart version more than once (unless you add and remove labels from the PR, but …
> feat(github): Use renovate to create PRs when upstream releases

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/README.md
- charts/argo-rollouts/templates/controller/clusterrole.yaml
- charts/argo-rollouts/values.yaml
add rules for [contour](https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-contour/blob/main/README.md) plugin
Checklist:
> feat(argo-rollouts): add rollout plugin contour rbac

- .github/workflows/chart-version-bump.yml
@tico24 my digest proposal in PR #2358 was wrong :/
> ![my bad proof](https://github.com/argoproj/argo-helm/assets/7290987/2b7f59b1-1b25-48b7-86db-d464eced4cf2)
Checklist:
> fix(github): Copy-pasta error on Action digest

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/extra-manifests.yaml
Signed-off-by: workwithprashant <60788667+workwithprashant@users.noreply.github.com>
Checklist:
> fix(argo-workflows): fix helm lint error when extraObjects is defined

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/controller/workflow-aggregate-roles.yaml
The `workflowtasksets` and `workflowtasksets/finalizers` resources are duplicated in the aggregated admin ClusterRole. This PR simply removes the duplication.
Checklist:
> fix(argo-workflows): Remove duplication in aggregated admin ClusterRole

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/README.md
- charts/argo-rollouts/templates/dashboard/deployment.yaml
- charts/argo-rollouts/values.yaml
Second part of #2386 - was missing the `dashboard` command as its the default CMD in the docker image so had to debug it until i undestood it was the thing its missing
Checklist:
> feat(argo-rollouts): add args for dashboard logs

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/controller/workflow-controller-config-map.yaml
This PR addresses a formatting issue in the Argo Workflows Helm chart, specifically targeting extra whitespace after the `filterGroupsRegex` and `scopes` fields in the generated controller ConfigMap. By adding hyphens (`-`) to the template directives, this change effectively eliminates unwanted extra spaces, enhancing the clarity and consistency of the YAML output.
Checklist:
> fix(argo-workflows): Prevent extra whitespace in controller ConfigMap

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/_helpers.tpl
- charts/argo-cd/templates/argocd-application-controller/clusterrolebinding.yaml
- charts/argo-cd/templates/argocd-application-controller/rolebinding.yaml
- charts/argo-cd/templates/argocd-application-controller/serviceaccount.yaml
- charts/argo-cd/templates/argocd-application-controller/statefulset.yaml
- charts/argo-cd/templates/argocd-applicationset/deployment.yaml
- charts/argo-cd/templates/argocd-applicationset/rolebinding.yaml
- charts/argo-cd/templates/argocd-applicationset/serviceaccount.yaml
- charts/argo-cd/templates/argocd-notifications/clusterrolebinding.yaml
- charts/argo-cd/templates/argocd-notifications/deployment.yaml
- charts/argo-cd/templates/argocd-notifications/rolebinding.yaml
- charts/argo-cd/templates/argocd-notifications/serviceaccount.yaml
- charts/argo-cd/templates/argocd-repo-server/clusterrolebinding.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-repo-server/rolebinding.yaml
- charts/argo-cd/templates/argocd-repo-server/serviceaccount.yaml
- charts/argo-cd/templates/argocd-server/clusterrolebinding.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/rolebinding.yaml
- charts/argo-cd/templates/argocd-server/serviceaccount.yaml
- charts/argo-cd/templates/dex/deployment.yaml
- charts/argo-cd/templates/dex/rolebinding.yaml
- charts/argo-cd/templates/dex/serviceaccount.yaml
- charts/argo-cd/templates/redis/deployment.yaml
- charts/argo-cd/templates/redis/serviceaccount.yaml
Non-functional cleanup of helper templates and if -> with for ServiceAccounts.
Checklist:
> chore(argo-cd): DRY cleanup of ServiceAccounts

- charts/argo-cd/Chart.yaml
- charts/argo-cd/values.yaml
> docs(argo-cd): Fix policy.csv block

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/values.yaml
On `artifactRepository.gcs` the following 3 keys were in the same level:
- `.serviceAccountKeySecret`
- `.name`
- `.key`
Checklist:
> docs(argo-workflows): fix wrong `artifactRepository` identations on values.yaml

- charts/argocd-image-updater/Chart.yaml
- charts/argocd-image-updater/README.md
- charts/argocd-image-updater/ci/enable-extra-objects-values.yaml
- charts/argocd-image-updater/templates/extra-manifests.yaml
- charts/argocd-image-updater/values.yaml
Resolves https://github.com/argoproj/argo-helm/issues/2428 .
Checklist:
> feat(argocd-image-updater): Support extra K8s manifests

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-configs/argocd-secret.yaml
Fixes https://github.com/argoproj/argo-helm/pull/2439#issuecomment-1903013533
We get the following error because of wrong `with` condition. 
> Error: Failed to render chart: exit status 1: Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [unknown object type "nil" in Secret.data.webhook.azuredevops.password, unknown object type "nil" in Secret.data.webhook.azuredevops.username]
Checklist:
> fix(argo-cd): Fix fail to render `.Values.configs.secret.azureDevops`

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
The other reference to Redis uses public.ecr.aws, strange to have one reference public.ecr.aws and other dockerhub.
Checklist:
> chore(argo-cd): Change redis repository to public.ecr.aws

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
Noticed the documented default didn't match the chart default. As this is just documentation I haven't bumped any versions.
Checklist:
> docs(argo-cd): Update docs with the correct default for application.instanceLabelKey

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/controller/workflow-controller-config-map.yaml
This commit addresses two places where trailing whitespace may be generated in the workflow-controller ConfigMap.
When the value `.resourceRateLimit` is not null, a trailing whitespace is added after "resourceRateLimit:". This commit trims that whitespace.
When the value `.sso.redirectUrl` is left as the default of empty string, a trailing whitespace is left after "redirectUrl:" as this value is not quoted. This commit pipes this value through `quote` to ensure this whitespace is no longer trailing and instead followed by `"` pair.
The main motivation of this commit is to generate a workflow-controller ConfigMap that is properly pretty-printed, which trailing whitespace prevents.
Checklist:
> fix(argo-workflows): Fix trailing whitespace in controller ConfigMap

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/serviceaccount.yaml
Checklist:
The template for [argocd-server/serviceaccount](https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/templates/argocd-server/serviceaccount.yaml#L16) is currently broken and the chart installation is failing when labels are passed via `server.serviceAccount.labels`.
- Error can be reproduced by just passing label values to `server.serviceAccount.labels`
```bash
$ cat labels.yaml ;echo "" ;  helm upgrade --install argocd argo/argo-cd --namespace argocd --create-namespace --values labels.yaml --kube-context  argocd-cluster-aks                  
server:
serviceAccount:
labels:
azure.workload.identity/use: "true"
Error: UPGRADE FAILED: YAML parse error on argo-cd/templates/argocd-server/serviceaccount.yaml: error converting YAML to JSON: yaml: line 16: could not find …
```
> fix(argo-cd): Fix Repo server `serviceaccount` label template

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
> fix(argo-cd): bump dex image version to fix cves

- charts/argocd-apps/Chart.yaml
- charts/argocd-apps/templates/applicationsets.yaml
Move the block up a level, it wasn't rendering correctly
Checklist:
> fix(argocd-apps): move ignoreApplicationDifferences block up a level

- CONTRIBUTING.md
- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/README.md.gotmpl
- charts/argo-workflows/ci/ha-values.yaml
- charts/argo-workflows/values.yaml
argo-workflows docs moved from github pages to readthedocs
Checklist:
> docs(argo-workflows): update documentation links to readthedocs

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/ingress-grpc.yaml
Before:
```
$ helm template argo-cd . --set server.ingressGrpc.enabled=true --set server.ingressGrpc.tls=true > /dev/null; echo $?
Error: YAML parse error on argo-cd/templates/argocd-server/ingress-grpc.yaml: error converting YAML to JSON: yaml: line 31: could not find expected ':'
Use --debug flag to render out invalid YAML
1
```
After:
```
$ helm template argo-cd . --set server.ingressGrpc.enabled=true --set server.ingressGrpc.tls=true > /dev/null; echo $?
0
```
Checklist:
> fix(argo-cd): Fix ingressGrpc extraTls

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-applicationset/networkpolicy.yaml
Resolves: https://github.com/argoproj/argo-helm/issues/2482
Checklist:
> fix(argo-cd): Fix applicationset network policy when webhook is enabled

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/ingress.yaml
> fix(argo-cd): add hostname of extraHost to tls hosts

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-server/ingress-grpc.yaml
- charts/argo-cd/values.yaml
Resolves:
- https://github.com/argoproj/argo-helm/issues/2496
- Based on feedback https://github.com/argoproj/argo-helm/pull/2481 changes TLS secret to argocd-server-grpc-tls
Checklist:
> fix(argo-cd): Fix ports and TLS for dedicated gRPC ingress

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
PR fixes invalid port names used by Istio for protocol selection
Ref: https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/
Checklist:
> fix(argo-cd): Use correct protocols for Istio service discovery

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-repo-server/serviceaccount.yaml
Resolves https://github.com/argoproj/argo-helm/issues/2505 
Checklist:
> fix(argo-cd): Use `with` instead of `range` on reposerver serviceaccount

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-repo-server/clusterrole.yaml
- charts/argo-cd/templates/argocd-repo-server/clusterrolebinding.yaml
Resolves: https://github.com/argoproj/argo-helm/discussions/2420
Checklist:
> chore(argo-cd): Disable argocd-repo-server cluster role by default

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-applicationset/ingress.yaml
- charts/argo-cd/values.yaml
> fix(argo-cd): Fix secret name for applicationset webhook ingress

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/README.md.gotmpl
- charts/argo-cd/templates/_helpers.tpl
- charts/argo-cd/templates/argocd-applicationset/certificate.yaml
- charts/argo-cd/templates/argocd-applicationset/ingress.yaml
- charts/argo-cd/templates/argocd-configs/argocd-notifications-cm.yaml
- charts/argo-cd/templates/argocd-server/certificate.yaml
- charts/argo-cd/templates/argocd-server/ingress-grpc.yaml
- charts/argo-cd/templates/argocd-server/ingress.yaml
- charts/argo-cd/values.yaml
Adds global configuration to provide single domain used by all components
Checklist:
> feat(argo-cd): Add global domain configuration

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/controller/workflow-controller-config-map.yaml
- charts/argo-workflows/values.yaml
Resolves https://github.com/argoproj/argo-helm/issues/2518
Checklist:
> feat(argo-workflows): add caSecret in s3 configuration

- charts/argocd-image-updater/Chart.yaml
- charts/argocd-image-updater/README.md
- charts/argocd-image-updater/templates/serviceaccount.yaml
- charts/argocd-image-updater/values.yaml
Allow defining custom labels to the service account.
This is required when using Azure Workload Identity to authenticate with the Azure Container Registry.
Checklist:
> feat(argocd-image-updater): allow defining additional labels to service account

- charts/argo-cd/Chart.lock
- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
> feat(argo-cd): bump redis chart dep and redis exporter

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/aws/ingress.yaml
Fix path order to evaluate GRPc endpoint first
Checklist:
> fix(argo-cd): Fix path order in AWS Ingress declaration

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/redis/deployment.yaml
To avoid issue with octal value yaml import format redis health check confimap mode in decimal.
> feat(argo-cd): Format redis health check confimap mode in decimal

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/ingress-grpc.yaml
Resolves: https://github.com/argoproj/argo-helm/issues/2540
Checklist:
> fix(argo-cd): Allow to use dedicated gRCP ingress with GKE implementation

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/dex/deployment.yaml
- charts/argo-cd/values.yaml
Allow to change the default http path and port for Dex server.
Fixes: https://github.com/argoproj/argo-cd/issues/9091
Checklist:
> feat(argo-cd): Allow modification of path and port for dex liveness and readiness probes

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/dex/deployment.yaml
Resolves: https://github.com/argoproj/argo-helm/issues/2545
Checklist:
> fix(argo-cd): Fix dex probes

- charts/argocd-image-updater/Chart.yaml
- charts/argocd-image-updater/README.md
- charts/argocd-image-updater/templates/_helpers.tpl
- charts/argocd-image-updater/templates/configmap-authscripts.yaml
- charts/argocd-image-updater/templates/configmap-sshconfig.yaml
- charts/argocd-image-updater/templates/configmap.yaml
- charts/argocd-image-updater/templates/deployment.yaml
- charts/argocd-image-updater/templates/metrics-service.yaml
- charts/argocd-image-updater/templates/rbac.yaml
- charts/argocd-image-updater/templates/secret.yaml
- charts/argocd-image-updater/templates/serviceaccount.yaml
- charts/argocd-image-updater/templates/servicemonitor.yaml
- charts/argocd-image-updater/values.yaml
I use this chart as a dependency but the .Release.Namespace is `bootstrap`, but I need to install argocd-image-updater chart into `argo` namespace.  This allows that and makes everything fall into place for me.
---
Checklist:
> feat(argocd-image-updater): Add ability to set .Values.namespaceOverride

- .github/workflows/publish.yml
- .github/workflows/renovate.yaml
Some of the GH actions fail on forks. They should probably just not run.
This is how the argo-workflows repo seems to operate, and I've not heard complaints.
Checklist:
> chore(github): Disable some GH actions on forks

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/controller/workflow-controller-deployment.yaml
Checklist:
tl;dr - The controller keeps trying to do Leader Election even if it's on its own. This PR turns that off for single-replica controllers. This reduces the load on the controller and k8s api a small amount. Useful for large-scale deployments.
I'm aware that what I've done is very opinionated. I could make it values-controlled if required, but I thought this would confuse users more than help them. I can't think of any situation where you'd want leader election enabled on a single-repl controller.
> feat(argo-workflows): Disable leader election on single repl controllers

- renovate.json
Today we received 3 PRs for renovate updating renovate 😆 :
- https://github.com/argoproj/argo-helm/pull/2560
- https://github.com/argoproj/argo-helm/pull/2563
- https://github.com/argoproj/argo-helm/pull/2567
I think it is enough if we set the schedule to monthly for this exact package.
It is 1:1 copy paste from here:
https://docs.renovatebot.com/configuration-options/#schedule
> To restrict aws-sdk to only monthly updates, you could add this package rule:
> ```json
> {
>   "packageRules": [
>     {
>       "matchPackageNames": ["aws-sdk"],
>       "extends": ["schedule:monthly"]
>     }
>   ]
> }
> ```
---
Checklist:
> chore(github): Update renovate image only monthly

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-applicationset/clusterrole.yaml
- charts/argo-cd/templates/argocd-applicationset/clusterrolebinding.yaml
- charts/argo-cd/values.yaml
Resolves https://github.com/argoproj/argo-helm/issues/2293
I have added ClusterRole/ClusterRoleBinding for applicationset-controller to [support ApplicationSet in any namespace](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Appset-Any-Namespace/).
Checklist:
> feat(argo-cd): support ApplicationSet in any namespace.

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/templates/_helpers.tpl
- charts/argo-workflows/templates/controller/artifact-repository-ref-cm.yaml
- charts/argo-workflows/templates/controller/workflow-controller-cluster-roles.yaml
- charts/argo-workflows/templates/controller/workflow-controller-config-map.yaml
- charts/argo-workflows/templates/controller/workflow-controller-crb.yaml
- charts/argo-workflows/templates/controller/workflow-controller-deployment-pdb.yaml
- charts/argo-workflows/templates/controller/workflow-controller-deployment.yaml
- charts/argo-workflows/templates/controller/workflow-controller-sa.yaml
- charts/argo-workflows/templates/controller/workflow-controller-service.yaml
- charts/argo-workflows/templates/controller/workflow-controller-servicemonitor.yaml
- charts/argo-workflows/templates/controller/workflow-rb.yaml
- charts/argo-workflows/templates/controller/workflow-role.yaml
- charts/argo-workflows/templates/controller/workflow-sa.yaml
- charts/argo-workflows/templates/server/gke/backendconfig.yaml
- charts/argo-workflows/templates/server/gke/frontendconfig.yaml
- charts/argo-workflows/templates/server/gke/managedcertificate.yaml
- charts/argo-workflows/templates/server/server-cluster-roles.yaml
- charts/argo-workflows/templates/server/server-crb.yaml
- charts/argo-workflows/templates/server/server-deployment-hpa.yaml
- charts/argo-workflows/templates/server/server-deployment-pdb.yaml
- charts/argo-workflows/templates/server/server-deployment.yaml
- charts/argo-workflows/templates/server/server-ingress.yaml
- charts/argo-workflows/templates/server/server-sa.yaml
- charts/argo-workflows/templates/server/server-service.yaml
- charts/argo-workflows/values.yaml
Resolves https://github.com/argoproj/argo-helm/issues/2534 .
Related to https://github.com/argoproj/argo-helm/pull/2562
Checklist:
> feat(argo-workflows): Add ability to set .Values.namespaceOverride

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-server/ingress-grpc.yaml
The default tls hosts entry for ingress must match the default ingress rules host - which can be .Values.server.ingressGrpc.hostname or  $hostname  when nothing else was specified.
Example to reproduce this bug:
Create a server with 2 ingresses (for argocd ui and grpc):
```
global:
domain: "argocd.k8s.local"
server:
ingress:
enabled: true
annotations:
cert-manager.io/cluster-issuer: blablabla
tls: true
hostname: "argocd.k8s.local"
ingressGrpc:
enabled: true
annotations:
cert-manager.io/cluster-issuer: blablabla
nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
tls: true
hostname: "argocd-grpc.k8s.local"
```
The Argo CD UI ingress endpoint is correct.
The GRPC ingress endpoint will be rendered with wrong tls hosts path (grpc.argocd.k8s.local
instead of argocd-grpc.k8s.local).
The PR …
> fix(argo-cd): Fixed default tls hosts for grpc ingress endpoint

- charts/argocd-image-updater/Chart.yaml
- charts/argocd-image-updater/templates/configmap-sshconfig.yaml
- charts/argocd-image-updater/templates/configmap.yaml
- charts/argocd-image-updater/templates/rbac.yaml
- charts/argocd-image-updater/values.yaml
fix(argocd-image-updater): Properly quoting the config map values
fix(argocd-image-updater): Only adding a data field to argocd-image-updater-ssh-config when there's data to be added
fix(argocd-image-updater): Only include config.argocd if config.applicationsAPIKind is set to 'argocd'
chore(argocd-image-updater): removing unneeded whitespace in Role and RoleBinding
Checklist:
> fix(argocd-image-updater): Properly quoting the config map values (and other fixes)

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-notifications/clusterrole.yaml
- charts/argo-cd/templates/argocd-server/clusterrole.yaml
> fix(argo-cd): Properly support "application in any namespace" for the argocd-server ClusterRole

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/crds/crd-applicationset.yaml
https://github.com/argoproj/argo-cd/pull/17424
related: https://github.com/argoproj/argo-helm/issues/2613 - this will solve root of problem
Checklist:
> fix(argo-cd): add missing crd change from 2.10.5

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-server/clusterrole.yaml
- charts/argo-cd/values.yaml
Resolves #2605 
---
Checklist:
> feat(argo-cd): enabled server cluster role permissions overriding

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/templates/controller/workflow-controller-service.yaml
- charts/argo-workflows/values.yaml
This PR adds the ability to use a headless service for the workflow controller as recommended in the [docs](https://argo-workflows.readthedocs.io/en/latest/metrics/#metrics-endpoint) to use when running the workflow controller in HA mode.
Related issue: https://github.com/argoproj/argo-helm/issues/2190
Checklist:
> feat(argo-workflows): Add the ability to use headless service for workflow controller

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
Fixes #2621
Details:
```bash
$ argocd admin cluster stats -h
Prints information cluster statistics and inferred shard number
Usage:
argocd admin cluster stats [flags]
Examples:
#Display stats and shards for clusters
argocd admin cluster stats
#Display Cluster Statistics for a Specific Shard
argocd admin cluster stats --shard=1
#In a multi-cluster environment to print stats for a specific cluster say(target-cluster)
argocd admin cluster stats target-cluster
Flags:
-- ...
Global Flags:
...
--redis-haproxy-name string       Name of the Redis HA Proxy; set this or the ARGOCD_REDIS_HAPROXY_NAME environment variable when the HA Proxy's name label differs from the default, for example when installing via the Helm chart (default "argocd-redis-ha-haproxy")
--redis-name string               Name of …
```
> fix(argo-cd): Add required label for CLI on redis-ha-haproxy pod

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-application-controller/deployment.yaml
- charts/argo-cd/templates/argocd-application-controller/statefulset.yaml
- charts/argo-cd/templates/argocd-applicationset/deployment.yaml
- charts/argo-cd/templates/argocd-notifications/deployment.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/templates/dex/deployment.yaml
- charts/argo-cd/templates/redis/deployment.yaml
- charts/argo-cd/values.yaml
Keeps the default behaviour of having automountServiceAccountToken set to true for deployments/statefulsets.
Checklist:
> fix(argo-cd): make automountServiceAccountToken configurable

- charts/argocd-image-updater/Chart.yaml
- charts/argocd-image-updater/README.md
- charts/argocd-image-updater/templates/deployment.yaml
- charts/argocd-image-updater/values.yaml
This PR allows defining envFrom vars for image updater to be used, as it is possible in the argo-cd chart.
Checklist:
> feat(argocd-image-updater): Allow defining extraEnvFrom for the deployment

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/_helpers.tpl
> feat(argo-cd): Pre-set `statusbadge.url` value to `global.domain`

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/_helpers.tpl
- charts/argo-cd/values.yaml
- Pre-set `statusbadge.url` to `global.domain` URL only when `statusbadge.enabled` is `true`
- Fix a minor comment typo
Checklist:
> fix(argo-cd): Pre-set `statusbadge.url` only when statusbadge is enabled

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/templates/controller/workflow-controller-crb.yaml
- charts/argo-workflows/templates/controller/workflow-rb.yaml
- charts/argo-workflows/values.yaml
I added an option to add additional SAs to the RoleBinding and ClusterRoleBinding that is created by default under `controller.clusterWorkflowTemplates` and `workflow.rbac`. This way users can configure other Service Accounts to be bound to that default Role.
Example: by providing a list of ServiceAccounts:
```yaml
serviceAccounts:
- name: my-service-account
namespace: my-namespace
```
I got the following result (`helm template -f values.yaml . --show-only templates/controller/workflow-rb.yaml`):
```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
name: release-name-argo-workflows-workflow
labels:
helm.sh/chart: argo-workflows-0.41.4
app.kubernetes.io/name: argo-workflows-workflow-controller
app.kubernetes.io/instance: release-name
app.kubernetes.io/component: …
```
> feat(argo-workflows): Allow adding additional ServiceAccounts to RoleBinding

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/README.md
- charts/argo-rollouts/templates/controller/deployment.yaml
- charts/argo-rollouts/templates/dashboard/deployment.yaml
- charts/argo-rollouts/values.yaml
This aligns with how podAnnotations works and allows for unique labels for each application at the pod level.
Checklist:
> feat(argo-rollouts): Add podLabels at the controller & dashboard level

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/crds/crd-application.yaml
- charts/argo-cd/templates/crds/crd-applicationset.yaml
> feat(argo-cd): Upgrade argocd to 2.11.0 + crd changes

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/crds/crd-applicationset.yaml
ApplicationSet is required by argocd-server, cannot be "opt-out".
If ApplicationSet CRD is not installed, we see lot of errors:
```
W0507 19:44:33.469804 7 reflector.go:424] pkg/mod/k8s.io/client-go@v0.26.11/tools/cache/reflector.go:169: failed to list *v1alpha1.ApplicationSet: the server could not find the requested resource (get applicationsets.argoproj.io)
E0507 19:44:33.469828 7 reflector.go:140] pkg/mod/k8s.io/client-go@v0.26.11/tools/cache/reflector.go:169: Failed to watch *v1alpha1.ApplicationSet: failed to list *v1alpha1.ApplicationSet: the server could not find the requested resource (get applicationsets.argoproj.io)
```
Relate:
- https://github.com/argoproj/argo-cd/pull/15432
Checklist:
> feat(argo-cd): Always install applicationset crd

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-server/service.yaml
- charts/argo-cd/values.yaml
Resolves: https://github.com/argoproj/argo-helm/issues/2641
Minor fixes:
- Simplified config with defaults in values.yaml
- Added upstream K8s docs for service options
- Keep it DRY
Checklist:
> fix(argo-cd): Fix Service configuration for Argo server

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/dex/deployment.yaml
Minor fix to restart the dex pod if there is a change to the `argocd-cm."dex.config"` config since [`dex.config`](https://github.com/argoproj/argo-helm/blob/39e1322df2b15446796356d9bf027250c5d75c35/charts/argo-cd/values.yaml#L191C7-L191C17) is stored there.
Checklist:
> fix(argo-cd): Adding checksum for argocd-cm to dex pod

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/values.yaml
Resolves https://github.com/argoproj/argo-helm/issues/2701 
Checklist:
> fix(argo-workflows): Correct sample of secondsAfterCompletion

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/server/server-service.yaml
Resolves https://github.com/argoproj/argo-helm/issues/2697
Checklist:
> fix(argo-workflows): Add missing serviceLabels to server service

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/redis-secret-init/job.yaml
- charts/argo-cd/values.yaml
Add nodeselector and tolerations to redis-secret-init job
Checklist:
> chore(argo-cd): add nodeselector and tolerations to redis-secret-init job

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/redis-secret-init/job.yaml
- charts/argo-cd/values.yaml
Add missing priorityClassName to redis-secret-init job
Checklist:
> chore(argo-cd): add priorityClassName to redis-secret-init job

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/redis-secret-init/job.yaml
- charts/argo-cd/templates/redis-secret-init/role.yaml
- charts/argo-cd/templates/redis-secret-init/rolebinding.yaml
- charts/argo-cd/templates/redis-secret-init/serviceaccount.yaml
- charts/argo-cd/values.yaml
This PR makes it possible to disable the redis secret initialization job and manage the secret using alternative means.
Checklist:
> feat(argo-cd): Make redis secret initialization optional

- charts/argo-events/Chart.yaml
- charts/argo-events/templates/_helpers.tpl
> fix(argo-events): support for additional labels

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-configs/cluster-secrets.yaml
- charts/argo-cd/values.yaml
Closes #2592.
Checklist:
~I'll re-generate the docs~ and bump the version if this change request goes forward. This contains non-backwards compatible changes. The rationale for this change is in the issue it closes.
Thanks for considering it.
> feat(argo-cd): represent cluster credentials as a map

- README.md
We recently had a few issues / PR proposals to make the chart more complex with features already provided by Helm (and the surrounding tools).
Let's make a clear statement and add some examples on how customers can use it.
Related PR(s):
- https://github.com/argoproj/argo-helm/pull/2729
---
Checklist:
> docs(github): Charts use Helm "Capabilities"

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/redis/deployment.yaml
> fix(argo-cd): Fixed redis exporter NOAUTH error

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-application-controller/role.yaml
Resolves https://github.com/argoproj/argo-helm/issues/2743
Checklist:
> fix(argo-cd): Add missing permission for Dynamic Cluster Distribution

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/server/server-deployment.yaml
`BASE_HREF` is redundant and will be removed in a future release (see https://github.com/argoproj/argo-workflows/pull/12653), so move to the existing `ARGO_BASE_HREF` for forward compat
- Change env var in Server Deployment to `ARGO_BASE_HREF`
- Was pointed to this line by https://github.com/argoproj/argo-workflows/pull/12653#issuecomment-1968808565
Checklist:
* [n/a] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [n/a] Any new values are backwards compatible and/or have sensible default.
> fix(argo-workflows): `BASE_HREF` -> `ARGO_BASE_HREF` for forward compat

- charts/argocd-image-updater/Chart.yaml
- charts/argocd-image-updater/values.yaml
fix referenced URL to command line reference page in the comment in values.yaml.
Checklist:
> chore(argocd-image-updater): fix referenced URL to command line reference page

- .github/dependabot.yml
Groups minor and patch updates via dependabot to reduce PRs
Leave major updates separate for visibility and testing
Checklist:
* [n/a] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [n/a] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [n/a] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [n/a] Any new values are backwards compatible and/or have sensible default.
> chore(github): group dependabot updates for minor and patch

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/server/server-deployment.yaml
Reverts my own #2756
Fixes https://github.com/argoproj/argo-workflows/issues/13199#issuecomment-2173304100
Sorry, I screwed this up and caused a regression. Didn't re-read my own release notes from https://github.com/argoproj/argo-workflows/pull/12653 (I wrote them 4 months ago to be fair) where `ARGO_BASE_HREF` would not work previously as it was inconsistently `ARGO_BASEHREF` (missing an underscore as the flag was missing a dash `--basehref`).
So there is actually no forward compatible change possible, and as such, just revert #2756.
I probably realized this when I wrote https://github.com/argoproj/argo-workflows/pull/12653#issuecomment-1969104216 and didn't make a PR upstream at the time (or earlier, when I first wrote the PR) and then forgot about that 4 months later (once I had …
> fix(argo-workflows): revert `BASE_HREF` change

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-server/service.yaml
- charts/argo-cd/values.yaml
Most users of ArgoCD may use `Ingress` (and soon `HTTPRoute`), but for those who may want to use `Service` of type `LoadBalancer`, this would be useful. The `loadBalancerClass` field would allow for a `CloudProvider` agnostic way of offloading the reconciliation for Kubernetes Service resources of type `LoadBalancer` to an external controller.
Checklist:
> feat(argo-cd): add loadBalancerClass field for Service resource

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
This is a small fix to address diff of deployed manifest vs desired manifest.
Kubernetes will inject default `resources: {}` when it is not set, which appears as a diff in argocd and other tools.
This resolves the diff as it will properly set the resources to the default value of `{}` and there will be no diff.
Additionally, resources for init container should be defined the same way as normal container, for consistency.
`helm template --values=values.yaml .`
Before:
After:
Checklist:
> fix(argo-cd): Default repo-server init container resources to empty

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/README.md
- charts/argo-rollouts/templates/controller/notifications-secret.yaml
- charts/argo-rollouts/values.yaml
Most users of Argo-rollouts may store secrets on vault which allows to auto inject secrets directly to secrets object using annotations.
Checklist:
> feat(argo-rollouts): add annotations for notifications secret

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-configs/cluster-secrets.yaml
- charts/argo-cd/values.yaml
Adding `shard` option to `clusterCredentials` map, according to https://argo-cd.readthedocs.io/en/stable/operator-manual/high_availability/#scaling-up (search for `shard`)
Checklist:
> chore(argo-cd): add shard option for clusterCredentials

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/README.md
- charts/argo-rollouts/templates/controller/notifcations-configmap.yaml
- charts/argo-rollouts/values.yaml
Resolves https://github.com/argoproj/argo-helm/issues/2792 
Add subscriptions into notification-configmap.
https://argo-cd.readthedocs.io/en/stable/operator-manual/notifications/subscriptions/#default-subscriptions
Checklist:
> fix(argo-rollouts): Add subscriptions into notifcations-configmap

- charts/argo-events/Chart.yaml
- charts/argo-events/README.md
- charts/argo-events/templates/argo-events-controller/config.yaml
- charts/argo-events/values.yaml
Resolves https://github.com/argoproj/argo-helm/issues/2787
Checklist:
> fix(argo-events): Update Jetstream versions as following upstream

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-application-controller/statefulset.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
> fix(argo-cd): Make REDIS_PASSWORD environment variables optional always

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/NOTES.txt
- charts/argo-cd/templates/argocd-application-controller/prometheusrule.yaml
- charts/argo-cd/templates/argocd-application-controller/servicemonitor.yaml
- charts/argo-cd/templates/argocd-applicationset/servicemonitor.yaml
- charts/argo-cd/templates/argocd-configs/cluster-secrets.yaml
- charts/argo-cd/templates/argocd-configs/repository-credentials-secret.yaml
- charts/argo-cd/templates/argocd-configs/repository-secret.yaml
- charts/argo-cd/templates/argocd-notifications/servicemonitor.yaml
- charts/argo-cd/templates/argocd-repo-server/servicemonitor.yaml
- charts/argo-cd/templates/argocd-server/servicemonitor.yaml
- charts/argo-cd/templates/dex/servicemonitor.yaml
- charts/argo-cd/templates/redis-secret-init/job.yaml
- charts/argo-cd/templates/redis-secret-init/role.yaml
- charts/argo-cd/templates/redis-secret-init/rolebinding.yaml
- charts/argo-cd/templates/redis-secret-init/serviceaccount.yaml
- charts/argo-cd/templates/redis/servicemonitor.yaml
Fixes #2817
This is a regression of:
- https://github.com/argoproj/argo-helm/pull/2679
---
Checklist:
> fix(argo-cd): Address oversights of feature `namespaceOverride`

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/_helpers.tpl
- charts/argo-cd/templates/redis-secret-init/serviceaccount.yaml
> fix(argo-cd): Address inconsistent redis-secret-init SA handling

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-application-controller/deployment.yaml
- charts/argo-cd/templates/argocd-application-controller/statefulset.yaml
Adds missing Redis sentinel variables to Application Controller deployment. Was missed in https://github.com/argoproj/argo-helm/pull/2492
Sync optional attribute to deployment following the STS fix in https://github.com/argoproj/argo-helm/pull/2800
Checklist:
> fix(argo-cd): Missing Redis sentinel variables in app controller deployment

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/README.md
- charts/argo-rollouts/templates/controller/notifications-configmap.yaml
- charts/argo-rollouts/values.yaml
This allows for using the upstream notifications configmap from https://github.com/argoproj/argo-rollouts/blob/master/manifests/notifications-install.yaml
Checklist:
> chore(argo-rollouts): add option to disable creation of notifications configmap

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/controller/workflow-rb.yaml
When singleNamespace is true, the namespace field for service account subject of the workflow role binding will be empty. The PR fixes this behavior similar to https://github.com/argoproj/argo-helm/commit/d30d85060e31b2bacc26afa01a00787950ed25b0.
Before the change:
````
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
name: wf-argo-workflows-workflow
labels:
helm.sh/chart: argo-workflows-0.41.13
app.kubernetes.io/name: argo-workflows-workflow-controller
app.kubernetes.io/instance: wf
app.kubernetes.io/component: workflow-controller
app: workflow-controller
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/part-of: argo-workflows
roleRef:
apiGroup: rbac.authorization.k8s.io
kind: Role
name: wf-argo-workflows-workflow
subjects:
- kind: ServiceAccount
name: …
```
> fix(argo-workflows): avoid empty namespace in role binding when singleNamespace is true

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/redis-secret-init/job.yaml
set `ttlSecondsAfterFinished` to prevent stuck during sync when managed by argocd
should fix https://github.com/argoproj/argo-cd/issues/6880#issuecomment-2263802072
---
Checklist:
> fix(argo-cd): Set TTL on redis-secret-init Job

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-application-controller/statefulset.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
Resolves https://github.com/argoproj/argo-helm/issues/2836
Checklist:
> fix(argo-cd): Fix Redis race condition due to optional REDIS_PASSWORD

- artifacthub-repo.yml
We don't need to expose any of our owners any longer. This is only required for ownership transfer.
Since this is gh-pages branch I don't think we need to version bump anything.
Checklist:
> chore(github): remove owner section of artifacthub-repo yaml

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-notifications/deployment.yaml
- charts/argo-cd/values.yaml
Since the Notification controller doesn't have a health checker, I added TCP socket probes.
Resolves #2781
Checklist:
> feat(argo-cd): Update Notification Liveness/Readiness Probes

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/templates/controller/workflow-controller-config-map.yaml
- charts/argo-workflows/values.yaml
Closes #2888 
Added support for setting annotations on argo workflows controller configmap
Checklist:
> feat(argo-workflows): Added support for setting annotations on argo workflows controller configmap

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/_helpers.tpl
Resolves https://github.com/argoproj/argo-helm/issues/2869
[`.Values.configs.cm."exec.enabled"`](https://github.com/yu-croco/argo-helm/blob/3019415efe744109fd1e96a98e52d1ab802ce227/charts/argo-cd/templates/argocd-server/clusterrole.yaml#L36) supports string of `true`, though the official type in agro-helm is bool. So I think it's kind for users to align the behavior of `.Values.configs.cm."statusbadge.enabled"` as well.
If I set `statusbadge.enabled` as `"true"`, helm template fails as below.
*argo-helm provides the type of parameters (e.g. [Argo CD Configs](https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd#argo-cd-configs)) and the type of `statusbadge.enabled` is bool, so it's not a bug.
```
$ helm template . > foo.yaml
Error: template: …
```
> chore(argo-cd): Support string type of "true" for `statusbadge.enabled`

- charts/argo-cd/Chart.lock
- charts/argo-cd/Chart.yaml
> chore(argo-cd): bump redis-ha

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/README.md.gotmpl
I take over https://github.com/argoproj/argo-helm/pull/2757 .
Checklist:
> chore(argo-cd): Fix typo on README

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/certificate.yaml
> fix(argo-cd): Fix certificate template secretTemplateAnnotations null

- charts/argocd-apps/Chart.yaml
- charts/argocd-apps/templates/projects.yaml
Rendering empty description leads to failed validation when using kubeconform.
Signed-off-by: Zoltán Reegn <zoltan.reegn@gmail.com>
Checklist:
> fix(argocd-apps): don't render empty app description

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/templates/controller/workflow-controller-servicemonitor.yaml
- charts/argo-workflows/values.yaml
> feat(argo-workflows): Add honorLabels parameter to Argo Workflows ServiceMonitor

- charts/argo-events/Chart.yaml
- charts/argo-events/templates/argo-events-webhook/service.yaml
> fix(argo-events): Fix events-webhook Service using non-default port

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-applicationset/clusterrolebinding.yaml
- charts/argo-cd/values.yaml
> feat(argo-cd): add multi-namespace support for ApplicationSet controller RBAC

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/redis-secret-init/job.yaml
Correction of the imagepullsecret for redis
Checklist:
> fix(argo-cd): Align imagePullSecrets for redis-secret-init Job

- .github/configs/renovate-config.js
- renovate.json
This should fix comments from renovate like this
> ![Renvate comment](https://github.com/user-attachments/assets/b624d841-f3dd-4b17-9129-672133543852)
> 
> Source: https://github.com/argoproj/argo-helm/pull/2937#issuecomment-2374987187
---
Checklist:
> chore(github): Use correct email of the Renovate bot

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/templates/controller/workflow-controller-servicemonitor.yaml
- charts/argo-workflows/values.yaml
> feat(argo-workflows): add configurable scrape interval for metrics and telemetry

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
Checklist:
The parameter `server.enable.proxy.extension` is already used in the original `charts/argo-cd/templates/argocd-server/deployment.yaml`.
> chore(argo-cd): Add Proxy Extensions config

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/controller/workflow-controller-cluster-roles.yaml
- charts/argo-workflows/templates/server/server-cluster-roles.yaml
Resolves https://github.com/argoproj/argo-helm/issues/2939
Checklist:
> fix(argo-workflows): Avoid to create ClusterRole for cluster template when singleNamespace

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/redis-secret-init/job.yaml
- charts/argo-cd/values.yaml
> feat(argo-cd): Add affinity to redisSecretInit Job

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/clusterrole.yaml
> fix(argo-cd): add missing event permissions for run actions

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-configs/cluster-secrets.yaml
Quotes `shard` value in clusterCredential Secret object otherwise it is parsed as number and throws
`json: cannot unmarshal number into Go struct field Secret.stringData of type string`
Checklist:
> fix(argo-cd): fixed shard value in clusterCredentials Secret

- charts/argocd-image-updater/Chart.yaml
- charts/argocd-image-updater/README.md
- charts/argocd-image-updater/templates/rbac.yaml
- charts/argocd-image-updater/values.yaml
original PR: https://github.com/argoproj/argo-helm/pull/2988
Checklist:
> feat(argocd-image-updater): Update dependency argoproj-labs/argocd-image-updater to v0.15.0

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-application-controller/deployment.yaml
- charts/argo-cd/templates/argocd-application-controller/statefulset.yaml
- charts/argo-cd/templates/argocd-applicationset/deployment.yaml
- charts/argo-cd/templates/argocd-notifications/deployment.yaml
- charts/argo-cd/templates/argocd-server/clusterrole.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/templates/crds/crd-application.yaml
- charts/argo-cd/templates/crds/crd-applicationset.yaml
- charts/argo-cd/templates/crds/crd-project.yaml
- charts/argo-cd/templates/dex/deployment.yaml
- charts/argo-cd/values.yaml
According to release schedule, Argo CD 2.13 should be release next monday:
https://argo-cd.readthedocs.io/en/latest/developer-guide/release-process-and-cadence/#release-cycle
> ![image](https://github.com/user-attachments/assets/0cff63d7-6e61-41bb-af44-269285f62920)
Since we at Swiss Post tested a use case with 2.13, I already went through all the changes available upstream and added them to the chart.
Purpose of this PR is to validate it already against our CI and against the eyes of argo-helm maintainers 😉 .
---
Checklist:
> feat(argo-cd): Update to Argo CD 2.13

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/templates/controller/configmap.yaml
Resolves https://github.com/argoproj/argo-helm/issues/2957
Checklist:
the config map was getting rendered as 
```
data:
- location: https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi/releases/download/v0.4.0/gatewayapi-plugin-linux-arm64
name: argoproj-labs/gatewayAPI
```
this changes it to 
```
data:
trafficRouterPlugins: |-
- location: https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi/releases/download/v0.4.0/gatewayapi-plugin-linux-arm64
name: argoproj-labs/gatewayAPI
```
as shown in [metricPlugin](https://argoproj.github.io/argo-rollouts/analysis/plugins/#mounting-the-plugin-executable-into-the-rollouts-controller-container) and [trafficPlugin](https://argo-rollouts.readthedocs.io/en/stable/features/traffic-management/plugins/#mounting-the …
> fix(argo-rollouts): plugin block rendering was incorrect

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-application-controller/servicemonitor.yaml
- charts/argo-cd/templates/argocd-applicationset/servicemonitor.yaml
- charts/argo-cd/templates/argocd-notifications/servicemonitor.yaml
- charts/argo-cd/templates/argocd-repo-server/servicemonitor.yaml
- charts/argo-cd/templates/argocd-server/servicemonitor.yaml
- charts/argo-cd/templates/dex/servicemonitor.yaml
- charts/argo-cd/templates/redis/servicemonitor.yaml
- charts/argo-cd/values.yaml
Checklist:
Add helm variables to configure honorLabels for each serviceMonitor
> feat(argo-cd): Add honorLabels config for ServiceMonitor resources

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
> chore(argo-cd): Update Redis image to 7.4.1

- charts/argo-cd/Chart.lock
- charts/argo-cd/Chart.yaml
diff: https://github.com/DandyDeveloper/charts/compare/redis-ha-4.27.6...redis-ha-4.29.4
Checklist:
> chore(argo-cd): Upgrade redis-ha

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/README.md
- charts/argo-rollouts/values.yaml
The change I made here https://github.com/argoproj/argo-helm/pull/3014 broken the examples. 
This works w/ my original change:
```
controller:
trafficRouterPlugins:
- name: "argoproj-labs/gatewayAPI"
location: "https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi/releases/download/v0.4.0/gatewayapi-plugin-linux-arm64"
sha256: "07e2fe515c900899c96777aac0ab490437a3d62c8adb94512ccb8b859325eb11"
```
But the example shows stringification is needed.
I feel having it "look like a real thing instead of a string" is more user friendly.
Checklist:
> fix(argo-rollouts): Change type of trafficRouterPlugins and trafficRouterPlugins as list

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/templates/controller/agent-rb.yaml
- charts/argo-workflows/templates/controller/agent-role.yaml
- charts/argo-workflows/templates/controller/artifact-gc-rb.yaml
- charts/argo-workflows/templates/controller/artifact-gc-role.yaml
- charts/argo-workflows/templates/controller/workflow-role.yaml
- charts/argo-workflows/values.yaml
This changes the permissions on the workflows Service Account.
Previously we gave permissions for the Argo Agent and Artifact GC to every workflow SA, this was overly permissive. Now with this PR, these things are disabled by default but can be enabled by the user if those features are used.
Checklist:
> fix(argo-workflows): Make Argo Agent and Artifact GC permissions optional for workflows SA

- charts/argo-events/Chart.yaml
- charts/argo-events/README.md
- charts/argo-events/templates/argo-events-controller/config.yaml
- charts/argo-events/values.yaml
Original: https://github.com/argoproj/argo-helm/pull/3054
Checklist:
> feat(argo-events): Upgrade Argo Events to v1.9.3

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-application-controller/statefulset.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
Should fix this [Issue](https://github.com/argoproj/argo-helm/issues/3057)
Checklist:
> fix(argo-cd): Fix REDIS_PASSWORD optional flag

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/ingress.yaml
Allows the use of templates in the `server.ingress.extraTls` field by running the `tpl` method on the Yaml
Checklist:
> feat(argo-cd): Template server ingress extraTls arguments

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-repo-server/servicemonitor.yaml
This fixes a bug introduced in https://github.com/argoproj/argo-helm/commit/0061e14563571f1cd0447fcac0e90407a600bbc4#diff-ef4a32480a793da4e68fa5b4e320523c5a1acf86064769abfc1d97a1462143eeR38 where the honorLabels config for the repo-server was put inside the `with` statement. In that case, if `.Values.repoServer.metrics.serviceMonitor.scheme` is set, the honorLabels value can't be found because the `.Values` object is not accessible from within the `with` block.
Checklist:
> fix(argo-cd): Fix repo-server honorLabels config template

- charts/argocd-image-updater/Chart.yaml
- charts/argocd-image-updater/templates/rbac.yaml
This PR add permissions for the image-updater `Role` when `createClusterRole` is set to false.
It is useful for namespaced deployments, where image-updater need to be able to read and update `Applications` in the same namespace.
Checklist:
> fix(argocd-image-updater): update RBAC namespaced role

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/values.yaml
I couldn’t access the link because it returned a 404 Not Found error. 
Therefore, I updated the link to an existing URL.
Checklist:
> fix(argo-workflows): a link in values.yaml for Kubernetes Ingress docs

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-configs/argocd-ssh-known-hosts-cm.yaml
- charts/argo-cd/values.yaml
Checklist:
Closes argoproj/argo-helm#3082
> fix(argo-cd): add functionality to en/disable argocd-ssh-known-hosts-cm

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/values.yaml
Aligned to https://github.com/argoproj/argo-helm/pull/3079
Checklist:
> fix(argo-rollouts): Correct outdated URL for ingress

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/README.md
- charts/argo-rollouts/templates/controller/deployment.yaml
- charts/argo-rollouts/values.yaml
Adding a configurable option for lifecycle and terminationGracePeriodSeconds in argo-rollouts chart. 
This is my first contribution so please let me know if I am missing anything.
Checklist:
> feat(argo-rollouts): Add lifecyle and terminationGracePeriodSeconds settings for controller

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/controller/workflow-controller-config-map.yaml
- charts/argo-workflows/values.yaml
In https://github.com/argoproj/argo-workflows/pull/12467, support for ephemeral S3 credentials was added. These are used when using AWS S3 Grants or AWS IAM Roles. This PR adds support for the `sessionTokenSecret` field to the argo-workflows helm chart.
Checklist:
> feat(argo-workflows): Support ephemeral credentials for s3

- renovate.json
Related to https://github.com/argoproj/argo-helm/pull/3104 .
In order to bump version and changelog for `public.ecr.aws/bitnami/redis-exporter`, I adjusted renovate.json.
Checklist:
> chore(github): Support redis-exporter to Renovate

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/ingress.yaml
> feat(argo-cd): Add DRY support for Ingress

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/README.md.gotmpl
resolves https://github.com/argoproj/argo-helm/issues/3116
Checklist:
> fix(argo-cd): Correct ingress listen-ports example on README

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/templates/controller/workflow-controller-config-map.yaml
- charts/argo-workflows/values.yaml
> feat(argo-workflows): Support workflowEvent configuration to Argo Workflow Controller

- charts/argocd-image-updater/Chart.yaml
- charts/argocd-image-updater/README.md
- charts/argocd-image-updater/templates/configmap-authscripts.yaml
- charts/argocd-image-updater/templates/configmap-sshconfig.yaml
- charts/argocd-image-updater/templates/configmap.yaml
- charts/argocd-image-updater/templates/deployment.yaml
- charts/argocd-image-updater/templates/secret.yaml
- charts/argocd-image-updater/values.yaml
Signed-off-by: AvivGuiser <avivguiser@gmail.com>
Checklist:
> feat(argocd-image-updater): Make cm and secret names configurable

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
> feat(argo-cd): Add an extra feature toggle to the argocd configmap that allows sync impersonation

- .github/workflows/renovate.yaml
- renovate.json
- scripts/renovate-bump-version.sh
This is an alternative approach of:
- #3106
> In order to pass https://github.com/argoproj/argo-helm/pull/3104 , I modified scripts.
> Related to https://github.com/argoproj/argo-helm/pull/3072
I tested the changes on my personal fork:
[full job-logs.txt](https://github.com/user-attachments/files/18565697/tested_on_fork_job-logs_2.txt)
Here you can see the script invokes by Renovate
```log
2025-01-27T23:03:36.9964962Z        "command": "./scripts/renovate-bump-version.sh -c argo-cd -d public.ecr.aws/docker/library/redis -v 7.4.2"
2025-01-27T23:03:37.0199099Z        "command": "./scripts/helm-docs.sh"
2025-01-27T23:03:38.2032791Z        "command": "./scripts/renovate-bump-version.sh -c argo-cd -d public.ecr.aws/docker/library/redis -v 7.4.2"
2025-01-27T23:03:38.2247721Z        "command": …
```
> feat(github): Support redis and extension-installer in Renovate - alternative

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/dex/servicemonitor.yaml
Currently the conditional creation of the `ServiceMonitor` for dex is not respecting `.Values.dex.enabled`.
Checklist:
> fix(argo-cd): only create dex-servicemonitor if dex is enabled

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
Add support for https://github.com/argoproj/argo-cd/pull/20816
Making this explicit in `values.yaml` so people wont miss it.
> feat(argo-cd): Add support for controller.sync.timeout.seconds

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/README.md.gotmpl
- charts/argo-cd/values.yaml
We cannot describe all of values for argocd-cm ConfigMap in values.yaml, so I added a comment how to set values.
Checklist:
> docs(argo-cd): Added a comment how to pass values into argocd-cm ConfigMap

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/ci/enable-server-liveness-probe-values.yaml
- charts/argo-workflows/ci/enable-server-readiness-probe-values.yaml
- charts/argo-workflows/templates/server/server-deployment.yaml
- charts/argo-workflows/values.yaml
Resolves https://github.com/argoproj/argo-helm/issues/3174
Checklist:
> feat(argo-workflows): Support livenessProbe to server

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-commit-server/deployment.yaml
Checklist:
following values causing template error
```yaml
global:
topologySpreadConstraints:
- maxSkew: 1
topologyKey: kubernetes.io/hostname
whenUnsatisfiable: DoNotSchedule
commitServer:
enabled: true
```
`Error: template: argo-cd/templates/argocd-commit-server/deployment.yaml:226:81: executing "argo-cd/templates/argocd-commit-server/deployment.yaml" at <.Values.commitServer.name>: nil pointer evaluating interface {}.commitServer`
> fix(argo-cd): Fixed broken topologySpreadConstraints template in commitServer component

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/templates/controller/workflow-role.yaml
- charts/argo-workflows/values.yaml
- feat(argo-workflows): allow additional rules for the service account that runs the workflows
resolve https://github.com/argoproj/argo-helm/issues/3148
Checklist:
> feat(argo-workflows): allow additional rules for service account that runs the workflows

- .github/workflows/scorecard.yml
It seems that we don't need to pass a PAT (personal access token) to our ossf/scorecard workflow.
https://github.com/ossf/scorecard/blob/aaa7df86e0c583f36e4918f888bf762009430a61/.github/workflows/scorecard-analysis.yml#L29-L39
https://cloud-native.slack.com/archives/C0574J7GR5Z/p1741107976097669
Checklist:
> chore(github): Make GH action secret SCORECARD_TOKEN obsolete

- charts/argo-cd/README.md
- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/README.md
- charts/argo-rollouts/templates/controller/configmap.yaml
- charts/argo-rollouts/values.yaml
We just built a custom stepPlugin but realized there's no support in the chart to add it into the configmap. Here's a quick fix for that.
Checklist:
> feat(argo-rollouts): add support for stepPlugins

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/NOTES.txt
- charts/argo-cd/templates/_helpers.tpl
- charts/argo-cd/templates/argocd-notifications/deployment.yaml
- charts/argo-cd/templates/dex/deployment.yaml
- charts/argo-cd/values.yaml
Fixes https://github.com/argoproj/argo-helm/issues/3010
According to the official documentation page, all ArgoCD components' log level and log format settings are supposed to be configured via `argocd-cmd-params-cm` ConfigMap (managed via `config.params.*` values in this Helm chart):
https://argo-cd.readthedocs.io/en/stable/operator-manual/argocd-cmd-params-cm-yaml/
It was done for all core components in 2 steps earlier:
- Deprecation of old params: https://github.com/argoproj/argo-helm/pull/1267
- Removal of old params: https://github.com/argoproj/argo-helm/pull/2407
However, `dex` and `notificationscontroller` were left behind and their log level & format are still overridden via CLI arguments. That causes a confusion, as described in https://github.com/argoproj/argo-helm/issues/3010 …
> fix(argo-cd): Deprecate logLevel and logFormat values for dex and notifications controller

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
Resolves https://github.com/argoproj/argo-helm/issues/3207 
Checklist:
> fix(argo-cd): Moved to oliver006/redis_exporter to support mutli-arch images

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-notifications/deployment.yaml
- charts/argo-cd/templates/dex/deployment.yaml
When using the deprecated `notifications.{logLevel,logFormat}` and `dex.{logLevel,logFormat}` values, changes introduced by https://github.com/argoproj/argo-helm/pull/3209 set the CLI arguments to a format like `--loglevel="debug"`, which isn't recognized by ArgoCD and causes a crash, e.g. here for the notifications controller:
```
Error: failed to parse log level: not a valid logrus Level: "\"debug\""
```
We remove `quote` from the CLI arguments templating to fix this.
Checklist:
> fix(argo-cd): set loglevel and logformat cli args without quotes

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
- renovate.json
Related to:
- #3207
- #3221
Checklist:
> fix(argo-cd): Also use oliver006/redis_exporter for non-HA redis

- charts/argo-cd/Chart.yaml
- charts/argo-cd/values.yaml
This is a non-functional change that improves the documentation related to the use of `kubelogin` in the `initContainer`.
The latest version of `kubelogin` is now referenced. Since the `initContainer` runs with the default setting `readOnlyRootFilesystem: true`, the zip file cannot be downloaded to the user's `$HOME` directory. To address this, the file is downloaded to an `emptyDir` volume instead.
Checklist:
> docs(argo-cd): Update kubelogin documentation for extra containers

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/_helpers.tpl
Fixes #3293 
Appears in:
- https://github.com/argoproj/argo-helm/pull/3238#issuecomment-2862002024
Xref:
- https://github.com/argoproj/argo-helm/issues/2705
Can you please give feedback @varkey since you raised this regression?
Checklist:
> fix(argo-cd): Use correct Secret name for optional (external-)Redis auth

- charts/argo-cd/Chart.lock
- charts/argo-cd/Chart.yaml
The redis-ha dependent chart has a few upgrades available: https://github.com/DandyDeveloper/charts/compare/redis-ha-4.33.2...redis-ha-4.33.7
I believe this fixes  #3315, but I'm actually looking for https://github.com/DandyDeveloper/charts/issues/307
Just as a reference, the last update was: #3216
Checklist:
> chore(argo-cd): Upgrade redis-ha dependency (4.33.7)

- .github/workflows/lint-and-test.yml
- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
- renovate.json
Improve ipv6 readiness, for https://github.com/argoproj/argo-helm/issues/3326
This shows the same image is available on both endpoints:
```
$ podman pull public.ecr.aws/docker/library/redis
Trying to pull public.ecr.aws/docker/library/redis:latest...
Getting image source signatures
Copying blob 61320b01ae5e done   | 
Copying blob 4f4fb700ef54 done   | 
Copying blob b8f8315b617a done   | 
Copying blob f8f9e5369fdd done   | 
Copying blob eb61abf5b105 done   | 
Copying blob 03bc4ee78aa8 done   | 
Copying blob 93cd3c5153ab done   | 
Copying config 90b270fb6d done   | 
Writing manifest to image destination
90b270fb6df331ff456014744f4fd3de812584386de75e762dc73add32533311
$ podman pull ecr-public.aws.com/docker/library/redis
Trying to pull ecr-public.aws.com/docker/library/redis:latest... …
```
> feat(argo-cd): use dual-stack AWS ECR registry for redis

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
**Description**
Resolves https://github.com/argoproj/argo-helm/issues/3329
This PR adds support for the hydrator feature in Argo CD by adding the `hydrator.enabled` parameter to the **argocd-cmd-params-cm** ConfigMap.
Checklist:
> feat(argo-cd): Add hydrator.enabled parameter

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
This PR updates the comment for `externalRedis.username` to clarify its behavior when `externalRedis.existingSecret` is set. Specifically, when `externalRedis.existingSecret` is configured, both `externalRedis.username` and `externalRedis.password` are ignored. This change aims to prevent misconfiguration, such as omitting the `redis-username` key in the specified `existingSecret` when the Redis username is not `default`.
**Behavior Examples:**
1. When `externalRedis.existingSecret` is set:
```
helm template my-argo-cd oci://ghcr.io/argoproj/argo-helm/argo-cd --version 8.0.14 \
--set externalRedis.host="redis.example.com" \
--set externalRedis.username="myuser" \
--set externalRedis.existingSecret="redis-credentials" | grep REDIS_USERNAME -A 11
```
Output:
```
- name: REDIS_USERNAME …
```
> chore(argo-cd): Update comment about Redis username if existingSecret is set

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/_helpers.tpl
- charts/argo-cd/templates/argocd-application-controller/deployment.yaml
- charts/argo-cd/templates/argocd-application-controller/statefulset.yaml
- charts/argo-cd/templates/argocd-commit-server/service.yaml
- charts/argo-cd/values.yaml
> fix(argo-cd): do not use hardcoded commit server URL

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/README.md.gotmpl
Closes #785
Document that argocdServerAdminPassword must be set via helm.values (not helm.parameters) in an Argo CD Application CR.
Checklist:
> docs(argo-cd): document admin password via helm.values in Application CR

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/NOTES.txt
Fixes #3406
This PR updates the NOTES.txt template in the Argo CD Helm chart to properly reflect the configs.params.server.rootpath value (if set).
When server.rootpath is configured, the access URL shown after port-forwarding now correctly includes the root path.
While testing with a custom server.rootpath (e.g., argocd), the output of helm install or helm upgrade still displayed the default URL:
`http://localhost:8080`
This could mislead users and result in confusion, especially when reverse proxies or base path routing are involved.
- Conditionally renders the access URL in `NOTES.txt`
- If configs.params.server.rootpath is not defined or empty, the default behavior is unchanged.
Checklist:
> docs(argo-cd): update NOTES.txt for conditional rootpath

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
I aligned to the redis_exporter version as `.Values.redis.exporter.image.tag` .
Checklist:
> chore(argo-cd): Update redis_exporter for redis-ha

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/templates/controller/workflow-controller-config-map.yaml
- charts/argo-workflows/values.yaml
Adding configuration options to enable the configuration of database synchronization to the argo-workflows helm chart. I took inspiration from how the `persistence` section is configured.
closes: https://github.com/argoproj/argo-helm/issues/3448
Checklist:
> feat(argo-workflows): add configuration for database synchronization

- charts/argo-cd/Chart.yaml
- charts/argo-cd/values.yaml
I spent a bunch of time trying to figure out why authentication was failed because I didn't look at the argocd docs (I was looking at helm).
This should help improve visibility into how to fix the issue related to `Failed to verify token: token verification failed for all audiences` 
I should note that I had to add the cliClientID and clientID to the allowedAudiences because it was giving me the above error despite the docs saying that it should allow the clientIDs by default (if allowedAudiences isn't specified) this possibly could be a bug, I'm happy to open an issue for that if wanted.
Checklist:
> fix(argo-cd): add allowed audiences parameter to values.yaml

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/controller/workflow-controller-cluster-roles.yaml
Adds missing RBAC permission for `workflowtasksets/status` to fix controller unable to patch status error.
The Argo Workflows controller was failing to patch `workflowtasksets/status` due to missing RBAC permission, preventing workflows from progressing to next steps.
- Add `workflowtasksets/status` to controller RBAC permissions in cluster role
- Bump chart version from 0.45.25 to 0.45.26  
- Update artifacthub.io/changes annotation
Fixes #3480
Checklist:
> fix(argo-workflows): add workflowtasksets/status RBAC permission

- .github/configs/external-redis.yaml
- .github/workflows/lint-and-test.yml
- charts/argo-cd/Chart.yaml
- charts/argo-cd/ci/external-redis-values.yaml
> ci(argo-cd): Replace Bitnami redis with simple YAML file

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-application-controller/role.yaml
- charts/argo-cd/values.yaml
Fixes #3414 - Add possibility to customize Role rules for application-controller when running in namespace-scoped environments with security constraints. This follows the same pattern as the existing `clusterRoleRules` feature and addresses the need for custom RBAC rules in namespace-scoped deployments.
- Add `controller.roleRules` array for custom RBAC rules
- Update Role template to use `with` pattern for conditional rules
- Maintain backward compatibility with existing default rules
- Follow same pattern as existing `clusterRoleRules` feature
```yaml
controller:
roleRules:
- apiGroups:
- ""
resources:
- pods
verbs:
- get
- list
- watch
- apiGroups:
- apps
resources:
- replicasets
verbs:
- get
- list
```
---
**Checklist:**
> feat(argo-cd): add custom roleRules support for application-controller

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-applicationset/networkpolicy.yaml
- charts/argo-cd/templates/argocd-repo-server/networkpolicy.yaml
- charts/argo-cd/templates/dex/networkpolicy.yaml
- charts/argo-cd/templates/redis/networkpolicy.yaml
Fixes #3431
This PR resolves the inconsistent NetworkPolicy behavior for metrics port access across ArgoCD components.
The repo-server NetworkPolicy was inconsistent with other components:
- **application-controller**: always allows metrics port access (no conditions)
- **repo-server**: only allows when `repoServer.metrics.enabled=true` (conditional)
This caused monitoring tools like Datadog to fail scraping repo-server metrics (port 8084) when NetworkPolicies were enabled, even though the metrics endpoint was available by default.
- Remove conditional check `{{- if .Values.repoServer.metrics.enabled }}` 
- Always allow metrics port access like application-controller
- Maintains consistency across all ArgoCD components
- Updated `charts/argo-cd/templates/argocd-repo-server/networkpolicy.ya …
> fix(argo-cd): Fix repo-server NetworkPolicy to allow metrics port access without requiring separate metrics service

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/values.yaml
This PR adds the ability to configure separate resource requests and limits for the `copyutil` initContainer in the repo-server pod, addressing issue #3504.
- Added `repoServer.initContainers.copyutil.resources` configuration option in values.yaml
- Updated deployment template to use separate resources for copyutil initContainer
- Maintains backward compatibility by falling back to `repoServer.resources` if not specified
- Bumped chart version from 8.5.6 to 8.5.7
- Updated changelog in Chart.yaml
```bash
helm template argocd charts/argo-cd \
--set repoServer.initContainers.copyutil.resources.requests.memory=64Mi \
--set repoServer.initContainers.copyutil.resources.requests.cpu=50m \
--set repoServer.initContainers.copyutil.resources.limits.memory=128Mi \
--set …
```
> feat(argo-cd): Allow configuring resource requests/limits for copyutil initContainer in repo-server pod

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/templates/dashboard/service.yaml
Signed-off-by: drfaust92 <ilia.lazebnik@gmail.com>
Checklist:
> chore(argo-rollouts): use named port for service
