argoproj/argo-helm

- charts/argo-events/.helmignore
- charts/argo-events/Chart.yaml
- charts/argo-events/README.md
- charts/argo-events/templates/_helpers.tpl
- charts/argo-events/templates/_sensor-crd.tpl
- charts/argo-events/templates/apply-sensor-crd-job.yaml
- charts/argo-events/templates/sensor-controller-clusterrole.yaml
- charts/argo-events/templates/sensor-controller-configmap.yaml
- charts/argo-events/templates/sensor-controller-crb.yaml
- charts/argo-events/templates/sensor-controller-deployment.yaml
- charts/argo-events/templates/sensor-controller-sa.yaml
- charts/argo-events/templates/signals-clusterrole.yaml
- charts/argo-events/templates/signals-crb.yaml
- charts/argo-events/templates/signals-sa.yaml
- charts/argo-events/values.yaml
closes #8 
I've included deployments for the sensor-controller but I haven't included any deployments yet for the signal services.. TBD on those.
> adding argo-events-chart

- charts/argo/templates/ui-cluster-role.yaml
- charts/argo/templates/ui-crb.yaml
- charts/argo/templates/workflow-controller-clusterrole.yaml
- charts/argo/templates/workflow-controller-crb.yaml
Release name reference only works with capital N when referencing the Name property. Changed "{{ Release.name }}"  to "{{ Release.Name }}" in all the files I found it.
> fixes capitalization error for release name reference

- charts/argo-events/templates/_helpers.tpl
- charts/argo-events/templates/_sensor-crd.tpl
> Invalid json syntax (#11)

- charts/argo-events/templates/_sensor-crd.tpl
- charts/argo-events/templates/apply-sensor-crd-job.yaml
- charts/argo-events/values.yaml
- charts/argo/Chart.yaml
- charts/argo/templates/ui-crb.yaml
- charts/argo/templates/ui-ingress.yaml
- charts/argo/templates/ui-service.yaml
- charts/argo/values.yaml
- Bump chart version to 0.2.1
- Change argo-ui service to ClusterIP (standard for most charts)
- Add ingress for argo-ui
- Also include fix for ui clusterrolebinding (same as https://github.com/argoproj/argo-helm/pull/17)
> Add ingress for argo-ui

- charts/argo/Chart.yaml
- charts/argo/templates/ui-deployment.yaml
- charts/argo/templates/ui-ingress.yaml
- charts/argo/templates/ui-sa.yaml
- charts/argo/templates/ui-service.yaml
- charts/argo/templates/workflow-controller-config-map.yaml
- charts/argo/templates/workflow-controller-deployment.yaml
- charts/argo/templates/workflow-controller-sa.yaml
Closes https://github.com/argoproj/argo-helm/issues/25
> Remove misspelled field from argo chart

- charts/argo-cd/templates/argocd-cm.yaml
- charts/argo-cd/values.yaml
> Adding oidcConfig option to argo-cd helm chart

- charts/argo-cd/templates/argocd-metrics-service.yaml
- charts/argo-cd/values.yaml
> Updating argocd-metrics service to target application-controller

- charts/argo-cd/templates/argocd-server-service.yaml
I'm sorry for my mistake.. (#53)
fix #56 by adding as follow
```
{{- if .Values.server.serviceAnnotations }}
annotations:
{{ toYaml .Values.server.serviceAnnotations | indent 4}}{{- end }}
```
> Argo-CD Service Annotation Syntax Error

- charts/argo/Chart.yaml
add argo appVersion
* Chart.yaml
```
appVersion: "v2.2.1"
```
> add argo appVersion

- charts/argo-cd/templates/argocd-cm.yaml
- charts/argo-cd/values.yaml
> Adding option for resource customizations in ArgoCD

- charts/argo/Chart.yaml
- charts/argo/templates/workflow-aggregate-roles.yaml
- charts/argo/values.yaml
> [argo] Create aggregate roles as pre-install hook

- charts/argo/Chart.yaml
- Update from v2.2.1 to v2.3.0
> [Argo] Fix appVersion in argo chart

- charts/argo-cd/templates/argocd-rbac-cm.yaml
- charts/argo-cd/values.yaml
Adding rbac scopes support for argo-cd helm chart
> Add rbac scopes support

- charts/argo/templates/ui-deployment.yaml
- charts/argo/templates/workflow-controller-deployment.yaml
- charts/argo/values.yaml
This allows the use of digests for the controller/ui/executor.
> argo: add support for individual image tags.

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server-deployment.yaml
- charts/argo-cd/values.yaml
We would like to specify annotations for the server component. This PR adds that functionality.
> Adds annotations to argocd server

- charts/argo/Chart.yaml
- charts/argo/templates/ui-deployment.yaml
- charts/argo/templates/workflow-controller-deployment.yaml
- charts/argo/values.yaml
> [argo] Add resources values to ui and controller

- charts/argo-cd/templates/argocd-secret.yaml
Fix syntax in new helm chart as mentioned in issue #104
> Fix syntax in argocd-secret template

- charts/argo-cd/templates/argocd-server-ingress.yaml
- charts/argo-cd/values.yaml
This avoids configuration duplication.
> Use Argo CD URL as first ingress host

- charts/argo-cd/templates/argocd-repo-server-deployment.yaml
- charts/argo-cd/templates/argocd-server-deployment.yaml
- charts/argo-cd/templates/argocd-ssh-known-hosts-cm.yaml
- charts/argo-cd/templates/argocd-tls-certs-cm.yaml
> Add ssh-known-hosts and tls cert cms and vols

- charts/argo-cd/templates/argocd-ssh-known-hosts-cm.yaml
- charts/argo-cd/templates/argocd-tls-certs-cm.yaml
Follow [this PR thread](https://github.com/argoproj/argo-helm/pull/112#issuecomment-533346542).
> Fix ConfigMap labels so ArgoCD picks it up

- .github/pull_request_template.md
- CONTRIBUTING.md
- OWNERS
- README.md
- charts/argo-cd/README.md
- charts/argo-ci/README.md
- charts/argo-events/README.md
- charts/argo/README.md
E.g. for Argo Workflows:
```
helm install charts/argo
argo version
```
E.g. for Argo CD:
```
helm install charts/argo-cd --namespace argocd
kubectl port-forward svc/argocd-server -n argocd 8080:443 &
argocd version
```
> Contributing

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-cm.yaml
- charts/argo-cd/values.yaml
Checklist:
* [ ✅ ] I have update the chart version in `Chart.yaml` following Semantic Versioning.
* [ ✅  ] Any new values are backwards compatible and/or have sensible default.
* [ ✅ ] I have followed the testing instructions in the [contributing guide](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md).
> Argocd - Add capabiility to set resource.exclustions from values.yaml

- charts/argo-events/Chart.yaml
- charts/argo-events/README.md
- charts/argo-events/templates/gateway-crd.yaml
- charts/argo-events/templates/sensor-crd.yaml
- charts/argo-events/values.yaml
Notable Changes:
* Updated to 0.10
* Made CRD install optional to match behavior in argo workflows chart
Checklist:
> Update argo events to 0.10

- charts/argo/Chart.yaml
- charts/argo/templates/workflow-controller-config-map.yaml
- charts/argo/values.yaml
> [argo] Add workflow persistence configuration

- .github/pull_request_template.md
- scripts/publish.sh
> changes on master to scripts/publish.sh,

- charts/argo/Chart.yaml
- charts/argo/templates/workflow-crd.yaml
- charts/argo/templates/workflow-template-crd.yaml
**Checklist:**
**Improvements**
- Update if-clause of workflow-crd.yaml
- Update if-clause of workflow-template-crd.yaml
> Fix argo CRD deployment

- .circleci/config.yml
- .github/pull_request_template.md
- scripts/publish.sh
> Fix bugs in CI set-up.

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-configs/argocd-rbac-cm.yaml
- charts/argo-cd/values.yaml
> remove default values from the argocd rbac configmap

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-server/route.yaml
- charts/argo-cd/values.yaml
> OpenShift Route

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/dex/deployment.yaml
Checklist:
Found a typo in the dex imagePullPolicy.
> Dex imagepull

- CONTRIBUTING.md
- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/NOTES.txt
> Better Helm NOTES.txt templating

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-server/ingress.yaml
- charts/argo-cd/values.yaml
> Minor fixes 11 11

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-configs/argocd-secret.yaml
- charts/argo-cd/values.yaml
Checklist:
Fixes https://github.com/argoproj/argo-cd/pull/2777/commits/7fdca084d94c0139a4bb967e1d019df04557b5aa the Chart
> Fix webhook secret properties

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/certificate.yaml
> [charts/argo-cd] Fix reference to cert config

- charts/argo-cd/Chart.yaml
- charts/argo-cd/values.yaml
> [charts/argo-cd] Bump version to 1.3.4

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
Checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/argoproj/argo-helm/186)
> chore: Upgrade to v1.3.6

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
> docs: Minor tweaks for ArgoCD

- charts/argo/Chart.yaml
- charts/argo/values.yaml
- Change argo image tag and app version to v2.4.3
Checklist:
> feat: Update argo chart for version v2.4.3

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/crds/crd-application.yaml
- charts/argo-cd/crds/crd-project.yaml
Fixes #169
Adds CRDs and information to README.md.
Checklist:
> fix: Add Helm3 CRDs directory

- charts/argo-cd/Chart.yaml
- charts/argo-cd/values.yaml
> fix: Updates values.yaml to have proper map syntax for extraArgs

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-configs/argocd-secret.yaml
- charts/argo-cd/values.yaml
> feat: allow custom secrets to be added to argocd-secret

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-application-controller/deployment.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
> fix: Fix breaking change in 1.6.1 chart

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
> Upgrade Argo-CD to v1.4.0

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
Signed-off-by: David J. M. Karlsen <david@davidkarlsen.com>
Checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/argoproj/argo-helm/214)
> feat: Bump to version 1.4.1

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/certificate.yaml
> fix: update certificate apiVersion

- charts/argo-events/Chart.yaml
- charts/argo-events/crds/event-source-crd.yml
- charts/argo-events/crds/gateway-crd.yml
- charts/argo-events/crds/sensor-crd.yml
- charts/argo-events/templates/argo-events-cluster-roles.yaml
- charts/argo-events/templates/eventsource-crd.yaml
- charts/argo-events/templates/gateway-controller-deployment.yaml
- charts/argo-events/templates/gateway-crd.yaml
- charts/argo-events/templates/sensor-controller-deployment.yaml
- charts/argo-events/templates/sensor-crd.yaml
- charts/argo-events/values.yaml
> feat: Update events chart

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
Signed-off-by: David Karlsen <david@davidkarlsen.com>
Checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/argoproj/argo-helm/221)
> chore: Upgrade to 1.4.2

- CODEOWNERS
> docs: Make Cabrinha an argo rollouts CODEOWNERS

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/README.md
> Adding a readme to the rollouts chart

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/dex/deployment.yaml
Signed-off-by: David Karlsen <david@davidkarlsen.com>
Se https://github.com/argoproj/argo-helm/issues/96 - and also comment: https://github.com/argoproj/argo-helm/pull/185#discussion_r381162955
Checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/argoproj/argo-helm/248)
> feat: use globalsecuritycontext for dex too, trim whitespace

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
> fix: Fixing podLabels in deployment templates

- charts/argo-cd/Chart.yaml
- charts/argo-cd/values.yaml
Checklist:
* [/] I have update the chart version in `Chart.yaml` following Semantic Versioning.
* [/] Any new values are backwards compatible and/or have sensible default.
* [/] I have followed the testing instructions in the [contributing guide](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md).
* [/] I have signed the CLA and the build is green.
* [/] I will test my changes again once merged to master and published.
> fix: indentation typo on example

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
> fix: volumes indention for argocd-server

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/README.md
- charts/argo-rollouts/templates/argo-rollouts-clusterrole.yaml
- charts/argo-rollouts/templates/argo-rollouts-deployment.yaml
- charts/argo-rollouts/templates/crds/analysis-run-crd.yaml
- charts/argo-rollouts/templates/crds/analysis-template-crd.yaml
- charts/argo-rollouts/templates/crds/experiment-crd.yaml
- charts/argo-rollouts/templates/crds/rollout-crd.yaml
- charts/argo-rollouts/values.yaml
> feat: add imagePullSecrets, labels, annotations and update CRDs

- charts/argo-events/Chart.yaml
- charts/argo-events/values.yaml
> chore: update chart and app version

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-application-controller/deployment.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/values.yaml
> feat: Helm Chart: add hostAliases to deployments #272

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
> chore: bump Argo CD Docker image tag to v1.5.1

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/certificate.yaml
> chore: update certificate apiVersion

- charts/argo-events/Chart.yaml
- charts/argo-events/README.md
- charts/argo-events/values.yaml
> chore: bump image version to v0.14.0

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/service.yaml
- charts/argo-cd/values.yaml
> feat: Add a load balancer IP to server's service

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-configs/argocd-secret.yaml
- charts/argo-cd/values.yaml
Add annotations customization for argocd-secret
Checklist:
> feat: [argo-cd] Add annotations for secret

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/projects.yaml
> fix: Additional Annotations in ArgoCD projects

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
Signed-off-by: Carlos Juan Gómez Peñalver <carlosjuangp@gmail.com>
fixes #212
Addressed some lintern issues, wrong references
due to some copy paste and fix the Chart
paramter tables adding some links to Kubernetes
documentation
Checklist:
> docs: Amend ArgoCD Readme.md file

- charts/argo-rollouts/.helmignore
- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/README.md
- charts/argo-rollouts/templates/argo-rollouts-role.yaml
- charts/argo-rollouts/templates/crds/rollout-crd.yaml
- charts/argo-rollouts/values.yaml
> feat: upgrade Argo Rollouts to v0.8.0

- CODEOWNERS
Checklist:
As discussed with @alexec adding myself to the CODEOWNERS for Argo Workflows charts.
> chore: Updating CODEOWNERS for Argo Workflows

- CODEOWNERS
> docs: Add paguos to argo workflows codeowners

- charts/argo-cd/Chart.yaml
- charts/argo-cd/values.yaml
> chore: update argocd version to 1.5.4

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/projects.yaml
- charts/argo-cd/values.yaml
> feat: Add namespaceResourceWhilelist to Projects

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/projects.yaml
- charts/argo-cd/values.yaml
> fix: Fix typo in namespaceResourceWhitelist

- charts/argo-cd/Chart.yaml
- charts/argo-cd/crds/crd-application.yaml
- charts/argo-cd/crds/crd-project.yaml
Argo CD has been updated without updating the CRDs. This PR fixes it.
Checklist:
> fix: update CRDs

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-application-controller/serviceaccount.yaml
- charts/argo-cd/templates/argocd-server/serviceaccount.yaml
- charts/argo-cd/templates/dex/serviceaccount.yaml
> fix: take argocd serviceaccount flags into account

- charts/argo/Chart.yaml
- charts/argo/templates/workflow-controller-deployment.yaml
- charts/argo/values.yaml
> fix: add pod and workflow workers to argo helm values

- charts/argocd-notifications/Chart.yaml
> docs: Adding argocd-notifications maintainer

- charts/argo/Chart.yaml
- charts/argo/templates/workflow-controller-config-map.yaml
> fix: Indent error

- charts/argo/Chart.yaml
- charts/argo/templates/server-deployment.yaml
- charts/argo/templates/workflow-controller-config-map.yaml
- charts/argo/values.yaml
> fix: Add support for SSO in Argo

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/crds/crd-application.yaml
- charts/argo-cd/values.yaml
Signed-off-by: Alin Balutoiu <alinbalutoiu@gmail.com>
Checklist:
> chore: Update argocd version to 1.6.1

- charts/argocd-notifications/Chart.yaml
- charts/argocd-notifications/templates/secret.yaml
> fix: Escape :icon: yaml

- charts/argocd-notifications/Chart.yaml
- charts/argocd-notifications/templates/secret.yaml
- charts/argocd-notifications/values.yaml
> fix: add email notifier to argocd-notifier

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-application-controller/deployment.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/templates/dex/deployment.yaml
- charts/argo-cd/templates/redis/deployment.yaml
Fixes #374
Signed-off-by: Ashwin Chandrasekar <ashwin.chandrasekar@lexisnexis.com>
Checklist:
> fix: add priorityClassName to argo-cd deployments pod specs

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-application-controller/deployment.yaml
- charts/argo-cd/values.yaml
Signed-off-by: darshanime <deathbullet@gmail.com>
closes https://github.com/argoproj/argo-cd/issues/2989
Checklist:
> chore(argo-cd): add app-resync as a template variable

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/README.md
- charts/argo-rollouts/templates/argo-rollouts-deployment.yaml
- charts/argo-rollouts/values.yaml
> Added tolerations, nodeSelectors and affinity to argo-rollouts

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/redis/deployment.yaml
- charts/argo-cd/values.yaml
Checklist:
* [x ] I have update the chart version in `Chart.yaml` following Semantic Versioning.
* [x ] Any new values are backwards compatible and/or have sensible default.
* [x ] I have signed the CLA and the build is green.
> fix: #404 - Change Redis image to run as non-root user

- charts/argo-events/templates/argo-events-cluster-roles.yaml
- charts/argo-events/templates/argo-events-roles.yaml
> fix(argo-events): fix rabc for argo-events-sa

- charts/argo-cd/Chart.yaml
- charts/argo-cd/values.yaml
> argo-cd: appVersion 1.6.2

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/values.yaml
> chore: argo-rollouts bump to 0.3.4 (v0.8.3)

- charts/argo-cd/Chart.yaml
- charts/argo-cd/crds/crd-application.yaml
- charts/argo-cd/crds/crd-project.yaml
Signed-off-by: Johnathan Falk <johnathan.falk@gmail.com>
Checklist:
> feat(argo-cd): Update CRD's to match upstream version.

- .gitignore
- charts/argo-ci/Chart.yaml
- charts/argo-ci/templates/ci-deployment.yaml
- charts/argo-ci/values.yaml
- charts/argo-events/Chart.yaml
- charts/argo-events/templates/eventbus-controller-deployment.yaml
- charts/argo-events/templates/eventbus-crd.yaml
- charts/argo-events/templates/eventsource-controller-deployment.yaml
- charts/argo-events/templates/eventsource-crd.yaml
- charts/argo-events/templates/sensor-controller-deployment.yaml
- charts/argo-events/templates/sensor-crd.yaml
- charts/argo-events/values.yaml
- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/values.yaml
- charts/argo/Chart.yaml
- charts/argo/templates/server-deployment.yaml
- charts/argo/templates/workflow-controller-deployment.yaml
- charts/argo/values.yaml
* Added imagePullSecrets
* Added annotations to argo-events CRDs to deploy with Helm 3 to allow testing
* Added dependent charts to gitignore
Checklist:
* [ x ] I have update the chart version in `Chart.yaml` following Semantic Versioning.
* [ x ] Any new values are backwards compatible and/or have sensible default.
* [ x ] I have followed the testing instructions in the [contributing guide](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md).
* [ x ] I have signed the CLA and the build is green.
* [ x ] I will test my changes again once merged to master and published.
> feat: imagePullSecrets for servers and controllers

- charts/argo-events/Chart.yaml
- charts/argo-events/values.yaml
> chore: bump to latest

- charts/argo-cd/Chart.yaml
- charts/argo-cd/values.yaml
Signed-off-by: Simon Rüegg <simon@rueggs.ch>
Checklist:
> chore(argocd): Upgrade to v1.7.4

- charts/argo-cd/Chart.yaml
- charts/argo-cd/values.yaml
> chore(argocd): Bump argo-cd version to v1.7.5

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-application-controller/deployment.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/values.yaml
> feat: Allow setting the log format to json for Argo CD

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/README.md
- charts/argo-rollouts/templates/argo-rollouts-clusterrole.yaml
- charts/argo-rollouts/templates/argo-rollouts-role.yaml
- charts/argo-rollouts/templates/crds/analysis-template-crd.yaml
- charts/argo-rollouts/templates/crds/cluster-analysis-template-crd.yaml
- charts/argo-rollouts/templates/crds/experiment-crd.yaml
- charts/argo-rollouts/templates/crds/rollout-crd.yaml
- charts/argo-rollouts/values.yaml
Bump argo-rollouts to version 0.9.1
Checklist:
> bump to v0.9.1

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/values.yaml
> feat: add extraContainers argument to deployment

- charts/argo/Chart.yaml
- charts/argo/values.yaml
> docs: Fixed typo in values comment

- charts/argo-cd/Chart.yaml
- charts/argo-cd/crds/crd-application.yaml
- charts/argo-cd/crds/crd-project.yaml
> chore: Sync upstream CRDs

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/README.md
- charts/argo-rollouts/templates/argo-rollouts-service-monitor.yaml
- charts/argo-rollouts/values.yaml
> feat(argo-rollouts): Add service monitor

- charts/argo/Chart.yaml
- charts/argo/templates/server-deployment.yaml
> fix(argo): Volume indents.

- charts/argo/Chart.yaml
- charts/argo/templates/workflow-controller-config-map.yaml
- charts/argo/values.yaml
> feat: Add support for Argo links

- charts/argo/Chart.yaml
- charts/argo/templates/workflow-controller-config-map.yaml
- charts/argo/values.yaml
https://github.com/argoproj/argo-helm/issues/476
Checklist:
> feat: Add parallelism to argo-helm chart

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-application-controller/deployment.yaml
- charts/argo-cd/values.yaml
> feat: Allow replicas to be set for application-controller

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/templates/argo-rollouts-deployment.yaml
fix to https://github.com/argoproj/argo-helm/issues/487
Checklist:
> fix: apply podannotations to the controller pod template

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-application-controller/deployment.yaml
- charts/argo-cd/templates/argocd-application-controller/statefulset.yaml
- charts/argo-cd/values.yaml
> feat(argo-cd): change application-controller to StatefulSet

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/README.md
- charts/argo-rollouts/templates/argo-rollouts-aggregate-roles.yaml
- charts/argo-rollouts/templates/argo-rollouts-clusterrole.yaml
- charts/argo-rollouts/templates/argo-rollouts-deployment.yaml
- charts/argo-rollouts/templates/argo-rollouts-role.yaml
- charts/argo-rollouts/templates/crds/analysis-run-crd.yaml
- charts/argo-rollouts/templates/crds/analysis-template-crd.yaml
- charts/argo-rollouts/templates/crds/cluster-analysis-template-crd.yaml
- charts/argo-rollouts/templates/crds/experiment-crd.yaml
- charts/argo-rollouts/templates/crds/rollout-crd.yaml
- charts/argo-rollouts/values.yaml
> Feat(argo-rollouts): Update argo-rollouts to v0.10.2

- CODEOWNERS
@vladlosev @yann-soubeyrand  @davidkarlsen @mr-sour @VaibhavPage
You're all submitting >= 3 PRs that have been accepted into the argo-helm repo. Would you be interested in becoming code-owners and PR approvers?
@benjaminws @stefansedich @paguos @seanson @spencergilbert @jbehling @cabrinha
Thoughts? Are you all able to review the occasional PR? It might be best if people who will never have time to do this are not in the CODEOWNERS file as it might give community members false expectations. You can still remain on the approver's list.
> chore: Add/invite new code-owners

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/dex/deployment.yaml
- charts/argo-cd/templates/redis/deployment.yaml
> fix(argo-cd): quote version annotation

- charts/argo/Chart.yaml
- charts/argo/values.yaml
See - https://github.com/argoproj/argo/releases
Checklist:
> chore(argo): update argo to 2.12.5

- CODEOWNERS
I'm unable to find the time to help with this project and I don't want to continue to be a blocker. Thanks so much for understanding!
Checklist:
> chore(charts/argo): Remove Benjamin Smith from CODEOWNERS

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/values.yaml
Signed-off-by: Leonardo Murillo <leonardo@murillodigital.com>
Checklist:
> feat(argo-cd): Enable support for lifecycle hooks on ArgoCD Server 

- charts/argocd-notifications/Chart.yaml
- charts/argocd-notifications/templates/bots/slack/deployment.yaml
- charts/argocd-notifications/templates/configmap.yaml
- charts/argocd-notifications/templates/deployment.yaml
- charts/argocd-notifications/templates/secret.yaml
- charts/argocd-notifications/values.yaml
> feat(argocd-notifications): update to support argocd-notification v1.0.1

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-configs/argocd-rbac-cm.yaml
- charts/argo-cd/values.yaml
Solves https://github.com/argoproj/argo-helm/issues/568. If needed, I can do this for other configmaps that are used as well
Checklist:
> feat(argo-cd): Conditionally create the RBAC configmap

- charts/argo-cd/Chart.yaml
- charts/argo-cd/values.yaml
> feat(argo-cd): updated ArgoCD to v1.8.4

- .github/pull_request_template.md
- charts/argocd-notifications/Chart.yaml
- charts/argocd-notifications/templates/secret.yaml
Signed-off-by: Vitaliy Fuks <vitaliyf@users.noreply.github.com>
Checklist:
> fix(argocd-notifications): Fixed #570: YAML parse error in argocd-notifications/templates/secret.yaml

- charts/argocd-notifications/Chart.yaml
- charts/argocd-notifications/templates/deployment.yaml
- charts/argocd-notifications/values.yaml
> feat(argocd-notifications): Add support for setting env vars.

- charts/argo/Chart.yaml
- charts/argo/templates/workflow-controller-config-map.yaml
> fix(argo): Use quote for keyFormat

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-application-controller/serviceaccount.yaml
- charts/argo-cd/templates/argocd-repo-server/serviceaccount.yaml
- charts/argo-cd/templates/argocd-server/serviceaccount.yaml
- charts/argo-cd/templates/dex/serviceaccount.yaml
- charts/argo-cd/values.yaml
> feat(argo-cd): add the ability to specify automountServiceAccountToken for argo-cd

- README.md
- charts/argocd-notifications/Chart.yaml
- charts/argocd-notifications/values.yaml
Related to: https://github.com/argoproj-labs/argocd-notifications/issues/202#issuecomment-799606671
Checklist:
> feat(argocd-notifications): Bump argo notifications

- CODEOWNERS
Regarding the issue #612 I would like to become an approver for the project. We recently started using argo within our enterprise and we absolute love it. Therefor I want to give something back to the community. I am rather new around here, so if that's a reason not being considered that's fine :).
Checklist:
> chore!: Nominate oliverbaehler as codeowner

- charts/argocd-notifications/Chart.yaml
- charts/argocd-notifications/values.yaml
Signed-off-by: Ryota Sakamoto <sakamo.ryota+github@gmail.com>
Note on DCO:
Checklist:
> chore(argocd-notifications): update argocd-notifications to 1.1.0

- charts/argocd-notifications/Chart.yaml
- charts/argocd-notifications/values.yaml
Signed-off-by: Ryota Sakamoto <sakamo.ryota+github@gmail.com>
Note on DCO:
Checklist:
> chore(argocd-notifications): update argocd-notifications to 1.1.1

- charts/argo-events/Chart.yaml
- charts/argo-events/templates/argo-events-roles.yaml
Signed-off-by: shortmann <kahllund@mac.com>
Note on DCO:
Checklist:
Fix for #666
> fix(argo-events): add missing status resources in rbac role

- charts/argocd-notifications/Chart.yaml
- charts/argocd-notifications/templates/deployment.yaml
- charts/argocd-notifications/values.yaml
Solution of the request https://github.com/argoproj/argo-helm/issues/634
Signed-off-by: 1Psy <41047934+1Psy@users.noreply.github.com>
Checklist:
> feat(argocd-notifications): Add securityContext

- charts/argocd-notifications/Chart.yaml
- charts/argocd-notifications/templates/bots/slack/role.yaml
- charts/argocd-notifications/templates/role.yaml
Added 
https://github.com/argoproj-labs/argocd-notifications/pull/244
https://github.com/argoproj-labs/argocd-notifications/pull/199
Signed-off-by: 1Psy <41047934+1Psy@users.noreply.github.com>
Note on DCO:
Checklist:
> fix(argocd-notifications): Changes to rules RBAC role.

- CODEOWNERS
I saw the pinned issue #612 and thought that this would be a chance to contribute back to this community. In our company we use ArgoCD on all clusters. Feel free to accept, reject this PR :-). Also you could limit my approver rights to the argo-cd chart if you want.
Note on DCO:
Checklist:
> chore: Nominate mkilchhofer as an approver

- charts/argo-cd/Chart.yaml
- charts/argo-cd/values.yaml
> chore(argo-cd): Bumped argo-cd to 2.0.1

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
Note on DCO:
Checklist:
> fix(argo-cd): fixed typos in chart's README.md file

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/service.yaml
- charts/argo-cd/values.yaml
> feat(argocd): Added externalTrafficPolicy to server service

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/README.md
- charts/argo-rollouts/templates/crds/analysis-run-crd.yaml
- charts/argo-rollouts/templates/crds/analysis-template-crd.yaml
- charts/argo-rollouts/templates/crds/cluster-analysis-template-crd.yaml
- charts/argo-rollouts/templates/crds/experiment-crd.yaml
- charts/argo-rollouts/templates/crds/rollout-crd.yaml
Signed-off-by: Hui Kang <hui.kang@salesforce.com>
Note on DCO:
Checklist:
> feat(argo-rollouts): add labels to crd to identify the rollout crds

- charts/argo-events/Chart.yaml
- charts/argo-events/templates/eventbus-controller-deployment.yaml
- charts/argo-events/templates/eventsource-controller-deployment.yaml
- charts/argo-events/templates/sensor-controller-deployment.yaml
- charts/argo-events/values.yaml
> feat(argo-events): add support for resource requests/limits

- CODEOWNERS
- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/NOTES.txt
- charts/argo-workflows/templates/_helpers.tpl
- charts/argo-workflows/templates/controller/workflow-aggregate-roles.yaml
- charts/argo-workflows/templates/controller/workflow-controller-cluster-roles.yaml
- charts/argo-workflows/values.yaml
/cc: @chgl 
This should resolve #521. It also resolves #762
Note on DCO:
Checklist:
> fix(argo-workflows): use template for all resource names

- charts/argo-workflows/.helmignore
- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/controller/workflow-controller-sa.yaml
This resolves #786 
Note on DCO:
Checklist:
> fix(argo-workflows): Observe 'controller.serviceAccount.create'

- charts/argocd-applicationset/Chart.yaml
- charts/argocd-applicationset/templates/deployment.yaml
- charts/argocd-applicationset/values.yaml
Signed-off-by: Josh Hudson <382062+itmustbejj@users.noreply.github.com>
Note on DCO:
Checklist:
> feat(argocd-applicationset): Add priorityClassName

- .github/semantic.yml
As this repo only allows "Squash and merge" we can simplify the settings of the 'Semantic Pull Requests' check.
Note on DCO:
Checklist:
> chore: Relax 'Semantic Pull Requests' check

- charts/argocd-applicationset/.helmignore
- charts/argocd-applicationset/Chart.yaml
- charts/argocd-applicationset/README.md
- charts/argocd-applicationset/ci/default-values.yaml
- charts/argocd-applicationset/ci/leader-election-values.yaml
- charts/argocd-applicationset/templates/crds.yaml
- charts/argocd-applicationset/values.yaml
Resolves #825 
/cc @maruina 
Note on DCO:
Checklist:
> fix(argocd-applicationset): Cleanup old CRD installation method

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-application-controller/networkpolicy.yaml
- charts/argo-cd/templates/argocd-repo-server/networkpolicy.yaml
- charts/argo-cd/templates/argocd-server/networkpolicy.yaml
- charts/argo-cd/templates/dex/networkpolicy.yaml
- charts/argo-cd/templates/networkpolicy-default-deny.yaml
- charts/argo-cd/templates/redis/deployment.yaml
- charts/argo-cd/templates/redis/networkpolicy.yaml
- charts/argo-cd/values.yaml
This resolves #799 
Note on DCO:
Checklist:
> feat(argo-cd): Add ability to create network policies

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-server/alb-grpc-service.yaml
- charts/argo-cd/templates/argocd-server/ingress-grpc.yaml
- charts/argo-cd/templates/argocd-server/ingress.yaml
- charts/argo-cd/values.yaml
Signed-off-by: Thomas O'Neill <toneill818@gmail.com>
Fixes Issue #803 
Note on DCO:
Checklist:
> feat(argo-cd): Support AWS ALB Ingress with gRPC

- charts/argo-cd/Chart.lock
- charts/argo-cd/Chart.yaml
- charts/argo-cd/values.yaml
> feat(argo-cd): Bump misc dependencies

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/service.yaml
- charts/argo-cd/values.yaml
> feat(argo-cd): Add sessionAffinity to server service

- charts/argocd-applicationset/Chart.yaml
- charts/argocd-applicationset/README.md
- charts/argocd-applicationset/templates/deployment.yaml
- charts/argocd-applicationset/values.yaml
Resolves #863
Note on DCO:
Checklist:
> feat(argocd-applicationset): Mount emptDir for /tmp and add extraVolumes support

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-aggregate-roles.yaml
- charts/argo-cd/values.yaml
* feat: Add support for aggregation clusterroles
Signed-off-by: Christian Strack <github@abyth.de>
Note on DCO:
Checklist:
> feat(argo-cd): Add support for aggregation clusterroles

- charts/argocd-image-updater/.helmignore
- charts/argocd-image-updater/Chart.yaml
- charts/argocd-image-updater/README.md
- charts/argocd-image-updater/README.md.gotmpl
- charts/argocd-image-updater/templates/_helpers.tpl
- charts/argocd-image-updater/templates/configmap.yaml
- charts/argocd-image-updater/templates/deployment.yaml
- charts/argocd-image-updater/templates/rbac.yaml
- charts/argocd-image-updater/templates/serviceaccount.yaml
- charts/argocd-image-updater/values.yaml
> feat(argo-cd): Add argocd image updater

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/controller/workflow-rb.yaml
- charts/argo-workflows/templates/controller/workflow-role.yaml
- charts/argo-workflows/templates/controller/workflow-sa.yaml
> fix(argo-workflows): Fix typo reported in #876

- charts/argocd-applicationset/Chart.yaml
Signed-off-by: Edward Nys <edward@linkurio.us>
Note on DCO:
Checklist:
> feat(argocd-applicationset): Bump appVersion to 0.2.0

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
This PR seeks to fix a README omission I made in #886 
Note on DCO:
Checklist:
> fix(argo-cd): Update README.md for ArgoCD

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/dex/deployment.yaml
- charts/argo-cd/values.yaml
Re-opened after latest changes
Checklist:
> feat(argo-cd): Add probes for Dex server >= 2.28.0

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-application-controller/deployment.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/templates/dex/deployment.yaml
- charts/argo-cd/templates/redis/deployment.yaml
- charts/argo-cd/values.yaml
Resolves https://github.com/argoproj/argo-helm/issues/852
Checklist:
> feat(argo-cd): Allow global configuration for pod annotations and labels

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/templates/argo-rollouts-service-monitor.yaml
> fix(argo-rollouts): Also use 'controller.component' parameter in ServiceMonitor

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
See - https://github.com/argoproj/argo-cd/releases/tag/v2.1.2
Note on DCO:
Checklist:
> feat(argo-cd): Upgrade argocd to v2.1.2

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/controller/workflow-controller-config-map.yaml
- charts/argo-workflows/values.yaml
> feat(argo-workflows): Adding initialDelay param to controller configmap

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-application-controller/deployment.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/templates/dex/deployment.yaml
- charts/argo-cd/templates/redis/deployment.yaml
- charts/argo-cd/values.yaml
Signed-off-by: mikutas <23391543+mikutas@users.noreply.github.com>
Similar to #465 
Note on DCO:
Checklist:
> feat(argo-cd): add extraContainers to pods besides server

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/redis/deployment.yaml
- charts/argo-cd/templates/redis/metrics-service.yaml
- charts/argo-cd/templates/redis/networkpolicy.yaml
- charts/argo-cd/templates/redis/servicemonitor.yaml
- charts/argo-cd/values.yaml
Resolves #891 
Note on DCO:
Checklist:
> feat(argo-cd): Add ability to scrape redis metrics

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-application-controller/deployment.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/templates/dex/deployment.yaml
> fix(argo-cd): Also add hostAliases to dex deployment

- .github/workflows/stale.yml
Intent: keep actions up-to-date.
Best feature of the new version IMHO: Structured and coloured log output.
> chore: Update to stale action v4

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/ci/default-values.yaml
> chore(argo-workflows): Also test with default values

- charts/argocd-notifications/Chart.yaml
- charts/argocd-notifications/templates/secret.yaml
- charts/argocd-notifications/values.yaml
> feat(argocd-notifications): support annotations on secret object

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/redis/service.yaml
- charts/argo-cd/values.yaml
> feat(argo-cd): Create optional annotations and labels for redis service

- charts/argo-cd/Chart.yaml
See - https://github.com/argoproj/argo-cd/releases/tag/v2.1.6
Note on DCO:
Checklist:
> feat(argo-cd): Upgrade argocd to v2.1.6

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/templates/controller/workflow-controller-crb.yaml
- charts/argo-workflows/templates/controller/workflow-rb.yaml
- charts/argo-workflows/templates/controller/workflow-role.yaml
- charts/argo-workflows/templates/controller/workflow-sa.yaml
- charts/argo-workflows/values.yaml
Note on DCO:
Checklist:
This change reverts #962 which made the changes that are do not match the documentation. The change also adds comments to clarify the meaning of various namespace related settings.
> fix(argo-workflows): Restore RBAC permission and clarify namespace settings.

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
See - https://github.com/argoproj/argo-cd/releases/tag/v2.1.7
Note on DCO:
Checklist:
> feat(argo-cd): Upgrade argocd to v2.1.7

- charts/argo-workflows/Chart.yaml
Signed-off-by: zhongzhouli 66lizhongzhou@gmail.com
Note on DCO:
Checklist:
> feat(argo-workflows): Upgrade argo-workflows to v3.2.4

- CODEOWNERS
I am no longer active on this repository as I have moved on from a previous position where I used ArgoCD frequently.
> chore(argocd): remove myself from CODEOWNERS

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-application-controller/deployment.yaml
- charts/argo-cd/values.yaml
Enable --metrics-application-labels
https://argo-cd.readthedocs.io/en/latest/operator-manual/metrics/
> feat(argo-cd): add flag and labels for application labels

- charts/argocd-image-updater/Chart.yaml
> feat(argocd-image-updater): Update to app version v0.11.0

- charts/argocd-notifications/Chart.yaml
> feat(argocd-notifications): Update to app version v1.2.0 

- charts/argocd-notifications/Chart.yaml
> feat(argocd-notifications): Update to app version v1.2.1

- charts/argo-cd/Chart.yaml
See - https://github.com/argoproj/argo-cd/releases/tag/v2.2.1
Note on DCO:
Checklist:
* [X ] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#versioning)
* [X ] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#changelog).
* [X ] Any new values are backwards compatible and/or have sensible default.
* [X ] I have signed off all my commits as …
> feat(argo-cd): Upgrade argocd to v2.2.1

- charts/argo-workflows/Chart.yaml
Signed-off-by: zhongzhouli 66lizhongzhou@gmail.com
Note on DCO:
Checklist:
> feat(argo-workflows): Upgrade argo-workflows to v3.2.6

- charts/argocd-notifications/Chart.yaml
- charts/argocd-notifications/README.md
- charts/argocd-notifications/templates/_helpers.tpl
- charts/argocd-notifications/templates/configmap.yaml
- charts/argocd-notifications/templates/deployment.yaml
- charts/argocd-notifications/templates/secret.yaml
- charts/argocd-notifications/values.yaml
Implement support for https://github.com/argoproj-labs/argocd-notifications/issues/77 in the chart.
Note on DCO:
Checklist:
> feat(argocd-notifications): Support new notification controller features from argoproj-labs/argocd-notifications#77

- charts/argo-cd/Chart.yaml
See - https://github.com/argoproj/argo-cd/releases/tag/v2.2.2
Note on DCO:
Checklist:
> feat(argo-cd): Upgrade argocd to v2.2.2

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/README.md
- charts/argo-rollouts/templates/dashboard/service.yaml
- charts/argo-rollouts/values.yaml
> feat(argo-rollouts): Support LoadBalancer settings for dashboard Service

- charts/argo-events/Chart.yaml
- charts/argo-events/templates/eventbus-controller-deployment.yaml
- charts/argo-events/templates/eventsource-controller-deployment.yaml
- charts/argo-events/templates/sensor-controller-deployment.yaml
- charts/argo-events/values.yaml
Signed-off-by: Muhammad Hamza Zaib <hamzazaib3202@gmail.com>
Note on DCO:
Checklist:
> feat(argo-events): Allow specifying container security context for controllers

- CODEOWNERS
Might have some time now to help maintain the charts.
Note on DCO:
Checklist:
> chore(argocd): Add my self as maintainer

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/templates/dashboard/ingress.yaml
> fix(argo-rollouts): Fix service name for ingress rollouts dashboard

- charts/argo-events/Chart.yaml
> feat(argo-events): Bump argo-events to the latest release

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/values.yaml
Resolves #1087
---
Note on DCO:
Checklist:
>  feat(argo-cd): Add resources to copyutil initContainer

- .helmdocsignore
- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/README.md
- charts/argo-rollouts/README.md.gotmpl
- charts/argo-rollouts/values.yaml
Implement helm-docs for the last chart "argo-rollouts".
Resolves #696
---
Note on DCO:
Checklist:
> feat(argo-rollouts): Use helm-docs to generate README.md

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-application-controller/poddisruptionbudget.yaml
- charts/argo-cd/templates/argocd-repo-server/poddisruptionbudget.yaml
- charts/argo-cd/templates/argocd-server/poddisruptionbudget.yaml
- charts/argo-cd/templates/dex/poddisruptionbudget.yaml
- charts/argo-cd/templates/redis/poddisruptionbudget.yaml
- charts/argo-cd/values.yaml
Signed-off-by: mugioka <okamugi0722@gmail.com>
Note on DCO:
Checklist:
> feat(argo-cd): add poddisruptionbudget template.

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-application-controller/deployment.yaml
- charts/argo-cd/templates/argocd-configs/cluster-secrets.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/route.yaml
- charts/argo-cd/templates/dex/deployment.yaml
- charts/argo-cd/templates/redis/deployment.yaml
- charts/argo-cd/templates/redis/metrics-service.yaml
- charts/argo-cd/templates/redis/service.yaml
* Quote annotation values in redis
* Update chart version
Resolves #1106
---
Note on DCO:
Checklist:
> fix(argo-cd): Quote annotation values

- charts/argocd-notifications/Chart.yaml
- charts/argocd-notifications/README.md
- charts/argocd-notifications/templates/bots/slack/deployment.yaml
- charts/argocd-notifications/values.yaml
Resolves #1042
/cc: @stephencoe Does that work for you?
---
Note on DCO:
Checklist:
> feat(argocd-notifications): Add ability to define bot security context

- charts/argo-workflows/Chart.yaml
Signed-off-by: Muhammad Hamza Zaib <hamzazaib3202@gmail.com>
Note on DCO:
Checklist:
> feat(argo-workflows): Update argo workflows to v3.2.7

- charts/argocd-applicationset/Chart.yaml
- charts/argocd-applicationset/README.md
- charts/argocd-applicationset/templates/deployment.yaml
- charts/argocd-applicationset/values.yaml
- charts/argocd-notifications/Chart.yaml
> feat(argocd-applicationset): add env variable in values

- charts/argocd-image-updater/Chart.yaml
> fix(argocd-image-updater): Update to app version v0.11.3

- charts/argo-events/Chart.yaml
Signed-off-by: Muhammad Hamza Zaib <hamzazaib3202@gmail.com>
Note on DCO:
Checklist:
> feat(argo-events): Bump argo-events to v1.6.0

- charts/argo-workflows/Chart.yaml
Signed-off-by: darklore <zodiac.brave.story@gmail.com>
Note on DCO:
Checklist:
> fix(argo-workflows): Update argo workflows to v3.2.9

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
Signed-off-by: Jan-Otto Kröpke <mail@jkroepke.de>
Note on DCO:
Checklist:
> fix(argo-cd): Use upstream entrypoint.sh

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-applicationset/deployment.yaml
- charts/argo-cd/templates/argocd-applicationset/metrics-service.yaml
- charts/argo-cd/templates/argocd-applicationset/role.yaml
- charts/argo-cd/templates/argocd-applicationset/rolebinding.yaml
- charts/argo-cd/templates/argocd-applicationset/service.yaml
- charts/argo-cd/templates/argocd-applicationset/serviceaccount.yaml
- charts/argo-cd/templates/argocd-applicationset/servicemonitor.yaml
- charts/argo-cd/templates/argocd-applicationset/webhook-ingress.yaml
- charts/argo-cd/templates/argocd-notifications/configmap.yaml
- charts/argo-cd/templates/argocd-notifications/deployment.yaml
- charts/argo-cd/templates/argocd-notifications/role.yaml
- charts/argo-cd/templates/argocd-notifications/rolebinding.yaml
- charts/argo-cd/templates/argocd-notifications/secret.yaml
- charts/argo-cd/templates/argocd-notifications/service-metrics.yaml
- charts/argo-cd/templates/argocd-notifications/serviceaccount.yaml
- charts/argo-cd/templates/argocd-notifications/servicemonitor.yaml
- charts/argo-cd/values.yaml
to allow to disable them
Signed-off-by: Eric Durand <eric_p_durand@yahoo.com>
Note on DCO:
Checklist:
> feat(argo-cd): Adding applicationSet.enable and notifications.enable 

- charts/argo-cd/Chart.yaml
> feat(argo-cd): Update to v2.3.2 release

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
Signed-off-by: Yixing Yan <yixingyan@gmail.com>
Note on DCO:
Checklist:
> fix(argo-cd): fix subscriptions default value

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-notifications/bots/slack/deployment.yaml
- charts/argo-cd/templates/argocd-notifications/bots/slack/role.yaml
- charts/argo-cd/templates/argocd-notifications/bots/slack/rolebinding.yaml
- charts/argo-cd/templates/argocd-notifications/bots/slack/service.yaml
- charts/argo-cd/templates/argocd-notifications/bots/slack/serviceaccount.yaml
- charts/argo-cd/values.yaml
Fixes:
- #1207 
- #1169
- #1178
---
Note on DCO:
Checklist:
> fix(argo-cd): Fix server.config.url and slack service account

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-notifications/configmap.yaml
- charts/argo-cd/values.yaml
This PR is revert of https://github.com/argoproj/argo-helm/pull/1220 ( because the configuration already existed 🙇 ) and is to improve comment.
Note on DCO:
Checklist:
> chore(argocd): update notification notifiers' comment

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/README.md.gotmpl
Note on DCO:
Closes #1257
Checklist:
> docs(argo-cd): Update README and remove template deps

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-applicationset/deployment.yaml
- charts/argo-cd/templates/argocd-notifications/bots/slack/deployment.yaml
- charts/argo-cd/templates/argocd-notifications/deployment.yaml
> fix(argo-cd): global.securityContext merging

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/README.md.gotmpl
No real content changes, just textual improvements.
Signed-off-by: Lieven Govaerts <lgo@mobsol.be>
> docs(argo-workflows): Fix typos and add missing words in README

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
> fix(argo-cd): Update to Argo CD v2.3.4

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-server/certificate.yaml
- charts/argo-cd/values.yaml
Signed-off-by: Greg Sidelinger <sidelig@nationwide.com>
Note on DCO:
Checklist:
> feat(argo-cd): Add support for external issuers in server Certificate resource

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/server/server-cluster-roles.yaml
I added missing verbs 🙋 
Resolves #1275
---
Note on DCO:
Checklist:
> fix(argo-workflows): Add missing verbs on argo-workflows-server

- charts/argo-workflows/Chart.yaml
[Release Notes](https://github.com/argoproj/argo-workflows/releases/tag/v3.3.6)
Includes 1 fix:
- eat: Handle omitted nodes in DAG enhanced depends logic. Fixes [#8654](https://github.com/argoproj/argo-workflows/issues/8654)
Note on DCO:
Checklist:
> feat(argo-workflows): Upgrade argo-workflows to v3.3.6

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-notifications/deployment.yaml
- charts/argo-cd/values.yaml
> Specify logformat for Argo-CD notifications component

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-application-controller/deployment.yaml
- charts/argo-cd/templates/argocd-applicationset/deployment.yaml
- charts/argo-cd/templates/argocd-notifications/bots/slack/deployment.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/templates/dex/deployment.yaml
- charts/argo-cd/templates/redis/deployment.yaml
- charts/argo-cd/values.yaml
This PR resolves https://github.com/argoproj/argo-helm/issues/1306 🙋 
---
Note on DCO:
Checklist:
> feat(argo-cd): support separate imagePullSecrets

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-configs/externalredis-secret.yaml
- charts/argo-cd/templates/argocd-configs/repository-credentials-secret.yaml
- charts/argo-cd/templates/argocd-configs/repository-secret.yaml
- charts/argo-cd/values.yaml
This PR resolves https://github.com/argoproj/argo-helm/issues/1280 🙋 
---
Note on DCO:
Checklist:
> feat(argo-cd): Support annotations in argocd-configs secrets

- CODEOWNERS
I saw this issue https://github.com/argoproj/argo-helm/issues/612 and thought it was an honor to keep getting involved in this project. In our company, we use ArgoCD and ArgoWorkflows in production environments and I am willing to contribute more to this community. 😄 
Please feel free to accept/reject this PR and limit the target chart. 🙏 
---
Note on DCO:
Checklist:
> chore(CODEOWNERS): Add yu-croco as approver

- .github/pull_request_template.md
> chore: update old URLs on pull_request_template.md

- charts/argo-cd/Chart.yaml
> feat(argo-cd): Upgrade image to v2.4.2

- charts/argo-workflows/Chart.yaml
[Release Notes](https://github.com/argoproj/argo-workflows/releases/tag/v3.3.7)
Note on DCO:
Checklist:
> fix(argo-workflows): Upgrade argo-workflows to v3.3.7

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/README.md.gotmpl
This PR resolves https://github.com/argoproj/argo-helm/issues/1259 as referring https://github.com/argoproj/argo-cd/tree/master/manifests#normal-installation 🙋
It worked well like below.
```
$ kubectl apply -k https://github.com/argoproj/argo-cd/manifests/crds\?ref\=v2.3.3
customresourcedefinition.apiextensions.k8s.io/applications.argoproj.io created
customresourcedefinition.apiextensions.k8s.io/appprojects.argoproj.io created
$ kubectl apply -k https://github.com/argoproj/argo-cd/manifests/crds\?ref\=v2.4.2
customresourcedefinition.apiextensions.k8s.io/applications.argoproj.io configured
customresourcedefinition.apiextensions.k8s.io/applicationsets.argoproj.io created
customresourcedefinition.apiextensions.k8s.io/appprojects.argoproj.io unchanged
```
---
Signed-off-by: yu-croco …
> fix(argo-cd): fix doc of how to upgrade CRD

- charts/argo-cd/Chart.yaml
See - https://github.com/argoproj/argo-cd/releases/tag/v2.4.3
Note on DCO:
Checklist:
> feat(argo-cd): Upgrade argocd to v2.4.3

- charts/argo-events/Chart.yaml
- charts/argo-events/templates/argo-events-controller/config.yaml
- charts/argo-events/values.yaml
> feat(argo-events): Upgrade controller to v1.7.1

- README.md
- charts/argo-cd/Chart.yaml
update link to a documentation
Note on DCO:
Checklist:
> fix(github): update link to the project page in README.md

- charts/argo-cd/Chart.yaml
Signed-off-by: Pawel Kalinowski <pawel@kalinowski.io>
Note on DCO:
Checklist:
> feat(argo-cd): Upgrade argocd to v2.4.6

- charts/argo-cd/Chart.yaml
Signed-off-by: Philipp Born <mail@philipp-born.eu>
Note on DCO:
Checklist:
> feat(argo-cd): Upgrade argocd to v2.4.7

- charts/argo-cd/Chart.yaml
See - https://github.com/argoproj/argo-cd/releases/tag/v2.4.8
Note on DCO:
Checklist:
> feat(argo-cd): Upgrade argocd to v2.4.8

- charts/argo-cd/Chart.yaml
[Release Notes](https://github.com/argoproj/argo-cd/releases/tag/v2.4.9)
[Diff between v2.4.8 and v2.4.9 of argo-cd](https://github.com/argoproj/argo-cd/compare/v2.4.8...v2.4.9)
- 9 doc changes
- 3 fixes
Note on DCO:
Checklist:
> feat(argo-cd): Upgrade argocd to v2.4.9

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/values.yaml
This PR resolves https://github.com/argoproj/argo-helm/issues/1394 . 🙋 
---
Note on DCO:
Checklist:
> fix(argo-workflows): Changed default .Values.artifactRepository.s3.insecure to false for security

- charts/argo-cd/Chart.yaml
See - https://github.com/argoproj/argo-cd/releases/tag/v2.4.11
Note on DCO:
Checklist:
* [X ] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [X ] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [X ] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTI …
> feat(argo-cd): Upgrade argocd to v2.4.11

- charts/argo-cd/Chart.lock
- charts/argo-cd/Chart.yaml
This resolves https://github.com/argoproj/argo-helm/issues/1418 🙋 
---
Note on DCO:
Checklist:
> feat(argo-cd): update redis-ha to v4.20.0

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
> chore(argo-cd): Update Dex image

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/README.md.gotmpl
- charts/argo-cd/ci/ha-autoscaling-values.yaml
- charts/argo-cd/ci/ha-static-values.yaml
- charts/argo-cd/templates/NOTES.txt
- charts/argo-cd/templates/_helpers.tpl
- charts/argo-cd/templates/argocd-application-controller/statefulset.yaml
- charts/argo-cd/templates/argocd-configs/argocd-cmd-params-cm.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/templates/dex/deployment.yaml
- charts/argo-cd/values.yaml
This PR should start discussion regarding https://github.com/argoproj/argo-helm/issues/1210
Changes:
- Added argocd-cmd-params-cm configmap
- Exposed all known config options via environment variables
- Rewire internal parameters for Redis / Dex
- Added deprecation notice for arguments that were superseded by new config
Resolves:
- https://github.com/argoproj/argo-helm/issues/1210
Checklist:
> feat(argo-cd): Add argocd-cmd-params-cm

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
Resolves https://github.com/argoproj/argo-helm/issues/1479
Note on DCO:
Checklist:
> fix(argo-cd): Fix UI error caused by new config

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/README.md.gotmpl
> docs(argo-cd): minor clarification around CRDs for Argo-CD

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/controller/workflow-controller-config-map.yaml
- charts/argo-workflows/values.yaml
I fixed this https://github.com/argoproj/argo-helm/pull/1473/files#r976930509 . 🙇 
---
Note on DCO:
Checklist:
> fix(argo-workflows): Set only used values on SSO configuration

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/templates/controller/workflow-controller-config-map.yaml
- charts/argo-workflows/values.yaml
This PR resolves https://github.com/argoproj/argo-helm/issues/1444 . 🙋 
---
Note on DCO:
Checklist:
> feat(argo-workflows): Support Azure Blob Storage for artifact

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/controller/workflow-controller-config-map.yaml
This PR resolves https://github.com/argoproj/argo-helm/issues/1491.
---
Note on DCO:
Checklist:
> fix(argo-workflows): failed SSO configuration

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/controller/workflow-controller-config-map.yaml
> fix(argo-workflows): Helm syntax on SSO configuration

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/NOTES.txt
- charts/argo-cd/values.yaml
Resolves https://github.com/argoproj/argo-helm/issues/1503
Note on DCO:
Checklist:
> fix(argo-cd): Move incorrectly placed timeout configs

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-notifications/deployment.yaml
- charts/argo-cd/values.yaml
> chore(argo-cd): Remove invalid options from notification controller

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/README.md.gotmpl
- charts/argo-cd/templates/_helpers.tpl
- charts/argo-cd/templates/_versions.tpl
- charts/argo-cd/templates/argocd-application-controller/pdb.yaml
- charts/argo-cd/templates/argocd-applicationset/webhook-ingress.yaml
- charts/argo-cd/templates/argocd-repo-server/hpa.yaml
- charts/argo-cd/templates/argocd-repo-server/pdb.yaml
- charts/argo-cd/templates/argocd-server/certificate.yaml
- charts/argo-cd/templates/argocd-server/gke/backendconfig.yaml
- charts/argo-cd/templates/argocd-server/hpa.yaml
- charts/argo-cd/templates/argocd-server/ingress-grpc.yaml
- charts/argo-cd/templates/argocd-server/ingress.yaml
- charts/argo-cd/templates/argocd-server/pdb.yaml
- charts/argo-cd/templates/dex/pdb.yaml
- charts/argo-cd/templates/redis/pdb.yaml
- charts/argo-cd/values.yaml
> feat(argo-cd): Add API version overrides for PDB and GKE

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-applicationset/role.yaml
Resolves: https://github.com/argoproj/argo-helm/issues/1552
Note on DCO:
Checklist:
> fix(argo-cd): Leader election for ApplicationSet controller

- charts/argocd-apps/Chart.yaml
- charts/argocd-apps/README.md
- charts/argocd-apps/ci/extensions-values.yaml
- charts/argocd-apps/templates/extensions.yaml
- charts/argocd-apps/values.yaml
Resolves: https://github.com/argoproj/argo-helm/issues/1501
Note on DCO:
Checklist:
> feat(argocd-apps): Add Argo UI extensions

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
Signed-off-by: Jan Christoph Beyer <janchristoph.beyer@googlemail.com>
Note on DCO:
Checklist:
> feat(argo-cd): Upgrade argocd to v2.4.15

- charts/argo-workflows/Chart.yaml
release note: https://github.com/argoproj/argo-workflows/releases/tag/v3.4.2
---
Note on DCO:
Checklist:
> chore(argo-workflows): Update ArgoWorkflows to v3.4.2

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-applicationset/metrics.yaml
- charts/argo-cd/templates/argocd-notifications/metrics.yaml
- charts/argo-cd/templates/argocd-repo-server/metrics.yaml
- charts/argo-cd/templates/argocd-server/metrics.yaml
- charts/argo-cd/templates/redis/metrics.yaml
> chore(argo-cd): Metrics DRY cleaning

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
Resolves: https://github.com/argoproj/argo-helm/issues/1443
---
Note on DCO:
Checklist:
> docs(argo-cd): Improve documentation

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
Closes: https://github.com/argoproj/argo-helm/issues/1589
---
Note on DCO:
Checklist:
> fix(argo-cd): Remove AWS volume from server

- charts/argo-workflows/Chart.yaml
release note: https://github.com/argoproj/argo-workflows/releases/tag/v3.4.3
---
Note on DCO:
Checklist:
> chore(argo-workflows): Update ArgoWorkflows to v3.4.3

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-application-controller/statefulset.yaml
- charts/argo-cd/templates/argocd-applicationset/deployment.yaml
- charts/argo-cd/templates/argocd-notifications/bots/slack/deployment.yaml
- charts/argo-cd/templates/argocd-notifications/deployment.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/templates/dex/deployment.yaml
- charts/argo-cd/templates/redis/deployment.yaml
- charts/argo-cd/values.yaml
Closes: https://github.com/argoproj/argo-helm/issues/1578
---
Note on DCO:
Checklist:
> feat(argo-cd): Add revisionHistoryLimit

- charts/argo-cd/Chart.lock
- charts/argo-cd/Chart.yaml
redis-ha PR: https://github.com/DandyDeveloper/charts/pull/232
---
Note on DCO:
Checklist:
> chore(argo-cd): Update redis-ha

- charts/argo-cd/Chart.yaml
See - https://github.com/argoproj/argo-cd/releases/tag/v2.5.3
Note on DCO:
Checklist:
* [X ] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [X ] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [X ] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTIN …
> feat(argo-cd): Upgrade argocd to v2.5.3

- charts/argo-workflows/Chart.yaml
change log: https://github.com/argoproj/argo-workflows/blob/master/CHANGELOG.md#v344-2022-11-28
---
Note on DCO:
Checklist:
> chore(argo-workflows): Update Argo Workflows to v3.4.4

- .github/workflows/lint-and-test.yml
- charts/argocd-apps/Chart.yaml
- charts/argocd-apps/templates/projects.yaml
add with statements around project templates for source/destinations
Note on DCO:
Checklist:
> feat(argocd-apps): Update project templates

- charts/argo-cd/Chart.yaml
release note: https://github.com/argoproj/argo-cd/releases/tag/v2.5.4
---
Note on DCO:
Checklist:
> chore(argo-cd): Update ArgoCD to v2.5.4

- charts/argocd-apps/Chart.yaml
- charts/argocd-apps/templates/projects.yaml
- charts/argocd-apps/values.yaml
This PR resolves https://github.com/argoproj/argo-helm/issues/1696. 🙋 
---
Note on DCO:
Checklist:
> feat(argocd-apps): Support sourceNamespaces for AppProject

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-application-controller/prometheusrule.yaml
- charts/argo-cd/values.yaml
Signed-off-by: Jellyfrog <Jellyfrog@users.noreply.github.com>
Note on DCO:
Checklist:
> feat(argo-cd): Add annotations to PrometheusRule

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/templates/controller/workflow-controller-config-map.yaml
- charts/argo-workflows/values.yaml
This PR resolves https://github.com/argoproj/argo-helm/issues/1707. 🙋 
---
Note on DCO:
Checklist:
> feat(argo-workflows): Support images property to workflow-controller-configmap for emissary executor

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/templates/controller/workflow-controller-config-map.yaml
- charts/argo-workflows/values.yaml
> chore(argo-workflows): Support missing configurations to workflow controller cm

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-notifications/servicemonitor.yaml
- charts/argo-cd/values.yaml
This PR resolves https://github.com/argoproj/argo-helm/issues/1718 . 🙋 
---
Note on DCO:
Checklist:
> chore(argo-cd): Support relabelings and metricRelabelings to Notification's ServiceMonitor

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/README.md.gotmpl
> chore(argo-workflows): Add changelog link on README

- charts/argo-events/Chart.yaml
Signed-off-by: Aleksandr Lossenko <aleksandr.lossenko@gmail.com>
Note on DCO:
Checklist:
> chore(argo-events): upgrade argo-events to app version 1.7.4

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/templates/controller/workflow-controller-config-map.yaml
- charts/argo-workflows/values.yaml
Signed-off-by: huiwq1990 <huiwq1990@163.com>
Note on DCO:
Checklist:
> feat(argo-workflows): add envFrom for main container

- charts/argo-cd/Chart.yaml
release note: https://github.com/argoproj/argo-cd/releases/tag/v2.5.6
---
Note on DCO:
Checklist:
> chore(argo-cd): Update Argo CD to v2.5.6

- charts/argo-cd/Chart.yaml
release note: https://github.com/argoproj/argo-cd/releases/tag/v2.5.7
---
Note on DCO:
Checklist:
> chore(argo-cd): Update Argo CD to v2.5.7

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
> chore(argo-cd): Update Argo CD extensions to v0.2.1

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/templates/controller/clusterrole.yaml
- charts/argo-rollouts/templates/controller/role.yaml
- charts/argo-rollouts/templates/crds/analysis-run-crd.yaml
- charts/argo-rollouts/templates/crds/analysis-template-crd.yaml
- charts/argo-rollouts/templates/crds/cluster-analysis-template-crd.yaml
- charts/argo-rollouts/templates/crds/rollout-crd.yaml
- charts/argo-rollouts/templates/dashboard/clusterrole.yaml
Fixes #1763
Note on DCO:
Checklist:
> chore(argo-rollouts): Upgrade argo-rollouts to 1.4.0

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-configs/argocd-secret.yaml
- charts/argo-cd/values.yaml
Resolves #1778
---
Note on DCO:
Checklist:
> feat(argo-cd): Add labels for argocd-secret

- charts/argo-events/Chart.yaml
- charts/argo-events/README.md
- charts/argo-events/templates/extra-manifests.yaml
- charts/argo-events/values.yaml
> feat(argo-events): Added support for extra k8s manifests

- charts/argo-cd/Chart.yaml
release note: https://github.com/argoproj/argo-cd/releases/tag/v2.5.8
---
Note on DCO:
Checklist:
> chore(argo-cd): Update Argo CD to v2.5.8

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-notifications/bots/slack/deployment.yaml
- charts/argo-cd/values.yaml
> feat(argo-cd): Add log settings and extraArgs to Slack bot

- charts/argo-cd/Chart.yaml
release note: https://github.com/argoproj/argo-cd/releases/tag/v2.5.9
---
Note on DCO:
Checklist:
> chore(argo-cd): Update Argo CD to v2.5.9

- charts/argo-cd/Chart.yaml
relates to https://github.com/argoproj/argo-helm/issues/1808 .
Let's try new structure.... 🙏 
If this works well, I will update other projects' changelog structure and [here](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
---
Note on DCO:
Checklist:
> fix(argo-cd): Align changelog structure to show changelogs on Artifact Hub

- charts/argocd-apps/Chart.yaml
relates to #1808
Was fixed already for:
Note on DCO:
Checklist:
> fix(argocd-apps): Align changelog structure

- charts/argocd-image-updater/Chart.yaml
> chore(argocd-image-updater): Update Argo CD Image Updater to v0.12.2

- charts/argo-cd/Chart.yaml
Signed-off-by: Marcel Hoyer <mhoyer@pixelplastic.de>
Note on DCO:
Checklist:
> chore(argo-cd): Update Argo CD to v2.5.10

- charts/argo-cd/Chart.yaml
> feat(argo-cd): Upgrade Argo CD to 2.6.1

- charts/argocd-apps/Chart.yaml
- charts/argocd-apps/ci/applications-multiple-sources-values.yaml
- charts/argocd-apps/ci/applications-values.yaml
- charts/argocd-apps/ci/applicationsets-multiple-sources-values.yaml
- charts/argocd-apps/ci/applicationsets-values.yaml
- charts/argocd-apps/templates/applications.yaml
- charts/argocd-apps/templates/applicationsets.yaml
- charts/argocd-apps/values.yaml
* Add `spec.sources` for application and applicationsets.
* Single source Application
*  `helm upgrade -i argocd-apps-applications charts/argocd-apps -n argocd --values charts/argocd-apps/ci/applications-values.yaml`
* Multiple sources Application
*  `helm upgrade -i argocd-apps-applications-ms charts/argocd-apps -n argocd --values charts/argocd-apps/ci/applications-multiple-sources-values.yaml`
* Single source ApplicationSets
*  `helm upgrade -i argocd-apps-applicationsets charts/argocd-apps -n argocd --values charts/argocd-apps/ci/applicationsets-values.yaml`
* Multiple sources ApplicationSets
*  `helm upgrade -i argocd-apps-applicationsets-ms charts/argocd-apps -n argocd --values charts/argocd-apps/ci/applicationsets-multiple-sources-values.yaml`
Signed-off-by: toyamagu …
> feat(argocd-apps): multiple sources for Application and ApplicationSet

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-applicationset/deployment.yaml
Resolves https://github.com/argoproj/argo-helm/issues/1838
Note on DCO:
Checklist:
> fix(argo-cd): Fix invalid progressive sync parameter

- charts/argo-cd/Chart.yaml
release note https://github.com/argoproj/argo-cd/releases/tag/v2.6.2
---
Note on DCO:
Checklist:
> chore(argo-cd): Upgrade Argo CD to v2.6.2

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/README.md.gotmpl
- charts/argo-cd/templates/_common.tpl
- charts/argo-cd/templates/argocd-application-controller/statefulset.yaml
- charts/argo-cd/templates/argocd-applicationset/deployment.yaml
- charts/argo-cd/templates/argocd-notifications/bots/slack/deployment.yaml
- charts/argo-cd/templates/argocd-notifications/deployment.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/templates/dex/deployment.yaml
- charts/argo-cd/templates/redis/deployment.yaml
- charts/argo-cd/values.yaml
Resolves: 
Part of:
---
Note on DCO:
Checklist:
> feat(argo-cd): Add global affinity configuration

- charts/argo-events/Chart.yaml
> chore(argo-events): Upgrade Argo Events to v1.7.6

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
Fixes #1863
Note on DCO:
Checklist:
> fix(argo-cd): Fix typo in values.yaml

- charts/argo-cd/Chart.yaml
release note: https://github.com/argoproj/argo-cd/releases/tag/v2.6.3
---
Note on DCO:
Checklist:
> chore(argo-cd): Upgrade Argo CD to v2.6.3

- charts/argocd-apps/Chart.yaml
- charts/argocd-apps/ci/applications-values.yaml
- charts/argocd-apps/templates/applications.yaml
- charts/argocd-apps/values.yaml
> fix(argocd-apps): Add revisionHistoryLimit option to apps

- README.md
> chore(github): Add slack button to README

- charts/argo-cd/Chart.yaml
release note: https://github.com/argoproj/argo-cd/releases/tag/v2.6.4
---
Note on DCO:
Checklist:
> chore(argo-cd): Upgrade Argo CD v2.6.4

- charts/argo-cd/Chart.yaml
release note: https://github.com/argoproj/argo-cd/releases/tag/v2.6.5
---
Note on DCO:
Checklist:
> chore(argo-cd): Upgrade Argo CD v2.6.5

- charts/argo-events/Chart.yaml
- charts/argo-events/README.md
- charts/argo-events/README.md.gotmpl
resolves https://github.com/argoproj/argo-helm/issues/1902 🙋
---
Note on DCO:
Checklist:
> chore(argo-events): Add install guide on README

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-configs/cluster-secrets.yaml
- charts/argo-cd/values.yaml
Implements #1753
---
Note on DCO:
Checklist:
> feat(argo-cd): Add ability to add project scoped cluster(s)

- charts/argo-cd/Chart.yaml
release note: https://github.com/argoproj/argo-cd/releases/tag/v2.6.6 
---
Note on DCO:
Checklist:
> chore(argo-cd): Upgrade Argo CD to v2.6.6

- charts/argo-events/Chart.yaml
- charts/argo-events/templates/argo-events-controller/deployment.yaml
- charts/argo-events/templates/argo-events-webhook/deployment.yaml
> fix(argo-events): wire up priorityClassName

- charts/argo-workflows/Chart.yaml
release note: https://github.com/argoproj/argo-workflows/releases/tag/v3.4.6
---
Note on DCO:
Checklist:
> chore(argo-workflows): Upgrade Argo Workflows to v3.4.6

- charts/argocd-image-updater/Chart.yaml
- charts/argocd-image-updater/README.md
- charts/argocd-image-updater/templates/deployment.yaml
- charts/argocd-image-updater/values.yaml
> feat(argocd-image-updater): Add support for pod labels

- charts/argo-events/Chart.yaml
- charts/argo-events/templates/argo-events-controller/deployment.yaml
Signed-off-by: shawqi.alazzawi@optimumpartners.co
Note on DCO:
Checklist:
> fix(argo-events): missing argument for toYaml function in deployment template

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/README.md.gotmpl
resolves https://github.com/argoproj/argo-helm/issues/1943 .
---
Note on DCO:
Checklist:
> fix(argo-workflows): Update outdated content on README

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/templates/controller/clusterrolebinding.yaml
- charts/argo-rollouts/templates/controller/deployment.yaml
- charts/argo-rollouts/templates/controller/metrics-service.yaml
- charts/argo-rollouts/templates/controller/notifcations-configmap.yaml
- charts/argo-rollouts/templates/controller/notifications-secret.yaml
- charts/argo-rollouts/templates/controller/poddisruptionbudget.yaml
- charts/argo-rollouts/templates/controller/role.yaml
- charts/argo-rollouts/templates/controller/rolebinding.yaml
- charts/argo-rollouts/templates/controller/serviceaccount.yaml
- charts/argo-rollouts/templates/controller/servicemonitor.yaml
- charts/argo-rollouts/templates/dashboard/clusterrolebinding.yaml
- charts/argo-rollouts/templates/dashboard/deployment.yaml
- charts/argo-rollouts/templates/dashboard/ingress.yaml
- charts/argo-rollouts/templates/dashboard/poddisruptionbudget.yaml
- charts/argo-rollouts/templates/dashboard/service.yaml
- charts/argo-rollouts/templates/dashboard/serviceaccount.yaml
Same change as https://github.com/argoproj/argo-helm/pull/1937
---
Note on DCO:
Checklist:
> fix(argo-rollouts): add namespace field for namespace scoped resources

- charts/argo-events/Chart.yaml
- charts/argo-events/templates/argo-events-controller/config.yaml
- charts/argo-events/templates/argo-events-controller/deployment.yaml
- charts/argo-events/templates/argo-events-controller/pdb.yaml
- charts/argo-events/templates/argo-events-controller/rbac.yaml
- charts/argo-events/templates/argo-events-controller/service.yaml
- charts/argo-events/templates/argo-events-controller/serviceaccount.yaml
- charts/argo-events/templates/argo-events-controller/servicemonitor.yaml
- charts/argo-events/templates/argo-events-webhook/clusterrolebinding.yaml
- charts/argo-events/templates/argo-events-webhook/deployment.yaml
- charts/argo-events/templates/argo-events-webhook/pdb.yaml
- charts/argo-events/templates/argo-events-webhook/service.yaml
- charts/argo-events/templates/argo-events-webhook/serviceaccount.yaml
Same change as https://github.com/argoproj/argo-helm/pull/1937
---
Note on DCO:
Checklist:
> fix(argo-events): add namespace field for namespace scoped resources

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/README.md
- charts/argo-rollouts/templates/controller/deployment.yaml
- charts/argo-rollouts/templates/dashboard/deployment.yaml
- charts/argo-rollouts/values.yaml
Resolves #1920
---
Note on DCO:
Checklist:
> feat(argo-rollouts): Add ability to provide additional volumes

- charts/argocd-image-updater/Chart.yaml
- charts/argocd-image-updater/templates/configmap-authscripts.yaml
- charts/argocd-image-updater/templates/configmap-sshconfig.yaml
- charts/argocd-image-updater/templates/configmap.yaml
- charts/argocd-image-updater/templates/deployment.yaml
- charts/argocd-image-updater/templates/metrics-service.yaml
- charts/argocd-image-updater/templates/rbac.yaml
- charts/argocd-image-updater/templates/secret.yaml
- charts/argocd-image-updater/templates/serviceaccount.yaml
- charts/argocd-image-updater/templates/servicemonitor.yaml
Same change as https://github.com/argoproj/argo-helm/pull/1937
---
Note on DCO:
Checklist:
> fix(argocd-image-updater): add namespace field for namespace scoped resources

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/crds/crd-application.yaml
- charts/argo-cd/templates/crds/crd-applicationset.yaml
release note: https://github.com/argoproj/argo-cd/releases/tag/v2.7.0
upgrade guide https://argo-cd.readthedocs.io/en/latest/operator-manual/upgrading/2.6-2.7/
---
Checklist:
> feat(argo-cd): Upgrade Argo CD to v2.7.0

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
ref: https://github.com/argoproj/argo-helm/pull/1989#issuecomment-1531009423 🙋 
---
Checklist:
> chore(argo-cd): Upgrade Dex and Redis

- CODEOWNERS
- CODE_OF_CONDUCT.md
- EMERITUS.md
- OWNERS
- SECURITY.md
By adding a code of conduct and security file we can set our `Community Standards` to 100% [here](https://github.com/argoproj/argo-helm/community)
Checklist:
> chore(github): Update repo files

- .github/workflows/pr-title.yml
[Example PR generate by Dependabot](https://github.com/argoproj/argo-helm/pull/2010)
[Example error about scope](https://github.com/argoproj/argo-helm/actions/runs/4900977670/jobs/8751985394?pr=2010#step:2:15)
Checklist:
> chore(github): Add deps pr title scope for dependabot PRs

- .github/workflows/lint-and-test.yml
- .github/workflows/pr-sizing.yml
- .github/workflows/pr-title.yml
- .github/workflows/publish.yml
- .github/workflows/stale.yml
Resolve some OpenSSF findings:
> ![OpenSSF findings](https://user-images.githubusercontent.com/7290987/236672536-e6481e15-0925-4b5f-bc21-a08f4b9d567f.png)
Ref: https://kooltheba.github.io/openssf-scorecard-api-visualizer/#/projects/github.com/argoproj/argo-helm
Dependabot takes care in updating these dependencies, eg:
- https://github.com/argoproj/argo-helm/pull/2012
- https://github.com/argoproj/argo-helm/pull/2011
- https://github.com/argoproj/argo-helm/pull/2010
---
Checklist:
> chore(deps): Pin all workflow deps

- artifacthub-repo.yml
Based on [this](https://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-repo.yml) by editing this metadata file we can obtain ownership
We want to manage ownership of our artifacthub setup
Checklist:
> chore(github): Update ownership of artifacthub

- .github/workflows/pr-sizing.yml
Resolves regression of:
- #2021
Checklist:
> fix(github): Remove quotes in `uses` statement

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-applicationset/service.yaml
- charts/argo-cd/values.yaml
resolves https://github.com/argoproj/argo-helm/issues/2007
---
Checklist:
> feat(argo-cd): Enable to customize Service type of applicationset-controller

- .github/workflows/lint-and-test.yml
This will help us ensure we use correct notation in our artifacthub annotations
Checklist:
> feat(github): add artifacthub linting

- index.yaml
Attempt to fix existing errors in Artifacthub
```log
error preparing package: error enriching package from annotations: 1 error occurred:
* invalid change: invalid kind: chore
(package: argo-events version: 2.3.1)
error preparing package: error enriching package from annotations: 1 error occurred:
* invalid change: invalid kind: chore
(package: argo-workflows version: 0.26.1)
error preparing package: error enriching package from annotations: 1 error occurred:
* invalid change: invalid kind: fix
(package: argo-workflows version: 0.25.2)
error preparing package: error enriching package from annotations: 1 error occurred:
* invalid change: invalid kind: fix
(package: argo-workflows version: 0.26.0)
error preparing package: error enriching package from annotations: 1 error occurred:
* invalid …
```
> fix: Attempt to fix errors in Artifacthub

- charts/argo-cd/Chart.yaml
Add the artifacthub annotation to the first chart to see what happens on the Artifacthub browser.
---
Checklist:
> feat(argo-cd): Introduce chart signing

- charts/argo-workflows/Chart.yaml
> feat(argo-workflows): Introduce chart signing

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/README.md
- charts/argo-rollouts/templates/controller/configmap.yaml
- charts/argo-rollouts/templates/crds/analysis-run-crd.yaml
- charts/argo-rollouts/templates/crds/analysis-template-crd.yaml
- charts/argo-rollouts/templates/crds/cluster-analysis-template-crd.yaml
- charts/argo-rollouts/templates/crds/experiment-crd.yaml
- charts/argo-rollouts/templates/crds/rollout-crd.yaml
- charts/argo-rollouts/values.yaml
resolves https://github.com/argoproj/argo-helm/issues/2038 .
release note: https://github.com/argoproj/argo-rollouts/releases/tag/v1.5.0
diff: https://github.com/argoproj/argo-rollouts/compare/v1.4.1...v1.5.0
---
Checklist:
> feat(argo-rollouts): Upgrade Argo Rollouts to v1.5.0

- charts/argocd-image-updater/Chart.yaml
> feat(argocd-image-updater): Introduce chart signing

- charts/argocd-apps/Chart.yaml
> feat(argocd-apps): Introduce chart signing

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-application-controller/metrics.yaml
- charts/argo-cd/templates/argocd-applicationset/metrics.yaml
- charts/argo-cd/templates/argocd-notifications/metrics.yaml
- charts/argo-cd/templates/argocd-repo-server/metrics.yaml
- charts/argo-cd/templates/argocd-server/metrics.yaml
- charts/argo-cd/templates/redis/metrics.yaml
- charts/argo-cd/values.yaml
> feat(argo-cd): Add ability to add prometheus.io/scrape annotations

- charts/argocd-apps/Chart.yaml
- charts/argocd-apps/ci/applicationsets-progressive-syncs-values.yaml
- charts/argocd-apps/templates/applicationsets.yaml
- charts/argocd-apps/values.yaml
[Progressive syncs](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Progressive-Syncs/) is a new experimental feature. [It must be explicitly enabled](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Progressive-Syncs/#enabling-progressive-syncs), so I'm not sure if we should include it in the default `values.yaml` yet.
Checklist:
> feat(argocd-apps): Add rollout strategy for ApplicationSet

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/README.md
- charts/argo-rollouts/templates/controller/deployment.yaml
- charts/argo-rollouts/templates/dashboard/deployment.yaml
- charts/argo-rollouts/values.yaml
> feat(argo-rollouts): add deployment annotations for controller

- charts/argo-cd/Chart.yaml
release notes: https://github.com/argoproj/argo-cd/releases/tag/v2.7.3
diff: https://github.com/argoproj/argo-cd/compare/v2.7.2...v2.7.3
Checklist:
> chore(argo-cd): Upgrade Argo CD to v2.7.3

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/controller/workflow-controller-servicemonitor.yaml
resolves https://github.com/argoproj/argo-helm/issues/2074 🙋 .
---
Checklist:
> chore(argo-workflows): Enable to configure Service Monitor port

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/templates/controller/workflow-controller-config-map.yaml
- charts/argo-workflows/templates/server/server-cluster-roles.yaml
- charts/argo-workflows/values.yaml
resolves https://github.com/argoproj/argo-helm/issues/1916 🙋 
---
Checklist:
> chore(argo-workflows): Declare SSO configuration explicitly on values.yaml

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/README.md
- charts/argo-rollouts/templates/controller/configmap.yaml
- charts/argo-rollouts/values.yaml
resolves https://github.com/argoproj/argo-helm/issues/2088 🙋 
Checklist:
> feat(argo-rollouts): Support Traffic Router Plugins

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/README.md.gotmpl
- charts/argo-cd/templates/argocd-application-controller/statefulset.yaml
- charts/argo-cd/templates/argocd-applicationset/deployment.yaml
- charts/argo-cd/templates/argocd-notifications/deployment.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/templates/dex/deployment.yaml
- charts/argo-cd/templates/redis/deployment.yaml
- charts/argo-cd/values.yaml
> feat(argo-cd): Add "global.env" for all deployed containers

- charts/argo-events/Chart.yaml
- charts/argo-events/README.md
- charts/argo-events/templates/argo-events-controller/deployment.yaml
- charts/argo-events/values.yaml
> fix(argo-events): add managed namespace configuration

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-applicationset/deployment.yaml
- add cmd-params checksum annotation to the applicationSet deployment to trigger an automated rollout when changed.
Checklist:
> feat(argo-cd): Update appset deployment template

- charts/argo-cd/Chart.yaml
> chore(argo-cd): Upgrade Argo CD to v2.7.7

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
Closes: https://github.com/argoproj/argo-helm/issues/2150
Checklist:
> feat(argo-cd): upgrade dexIDP from 2.36.0 -> 2.37.0

- charts/argo-cd/Chart.yaml
See - https://github.com/argoproj/argo-cd/releases/tag/v2.7.8
Checklist:
* [X ] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [X ] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [X ] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [X ] Any new values are backwards compatible and/or have sensible default.
* [X ] I have signed off all my commits as required by …
> feat(argo-cd): Upgrade argocd to v2.7.8

- charts/argo-workflows/Chart.yaml
CRD changes were to full CRDs.  We only deal in the minimals.  We're good.
https://github.com/argoproj/argo-workflows/releases/tag/v3.4.9
Checklist:
> chore(argo-workflows): Upgrade to 3.4.9

- charts/argocd-apps/Chart.yaml
- charts/argocd-apps/templates/applications.yaml
- charts/argocd-apps/values.yaml
> feat(argocd-apps): syncOptions for applications

- charts/argocd-apps/Chart.yaml
- charts/argocd-apps/ci/applications-values.yaml
- charts/argocd-apps/templates/applications.yaml
- charts/argocd-apps/values.yaml
Resolves https://github.com/argoproj/argo-helm/issues/2180 🙋 
Checklist:
> fix(argocd-apps): fix indent of syncOptions

- charts/argo-cd/Chart.yaml
Release note: https://github.com/argoproj/argo-cd/releases/tag/v2.7.11
diff: https://github.com/argoproj/argo-cd/compare/v2.7.10...v2.7.11
*Though Argo CD v2.8.0 is already coming https://github.com/argoproj/argo-cd/releases/tag/v2.8.0 😇 
Checklist:
> chore(argo-cd): Upgrade Argo CD to v2.7.11

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-application-controller/statefulset.yaml
- charts/argo-cd/templates/argocd-applicationset/deployment.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/templates/crds/crd-application.yaml
- charts/argo-cd/templates/crds/crd-applicationset.yaml
- charts/argo-cd/values.yaml
Initial draft for 2.8.0 release.
Checklist:
> feat(argo-cd): Upgrade Argo CD to 2.8.0

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/_helpers.tpl
> fix(argo-cd): Fix global log level configuration

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/NOTES.txt
- charts/argo-cd/templates/argocd-applicationset/deployment.yaml
- charts/argo-cd/values.yaml
Resolves: https://github.com/argoproj/argo-helm/issues/2193
Checklist:
> chore(argo-cd): Change applicationSet replicaCount to replicas

- charts/argo-workflows/Chart.yaml
~Release happening today after contributors meeting~ Released
https://github.com/argoproj/argo-workflows/releases/tag/v3.4.10
https://github.com/argoproj/argo-workflows/compare/v3.4.9...v3.4.10
Checklist:
> chore(argo-workflows): Upgrade to Argo Workflows v3.4.10

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/templates/controller/workflow-sa.yaml
- charts/argo-workflows/values.yaml
> feat(argo-workflows): add imagePullSecret for workflow sa

- charts/argo-cd/Chart.yaml
release note: https://github.com/argoproj/argo-cd/releases/tag/v2.8.1
diff: https://github.com/argoproj/argo-cd/compare/v2.8.0...v2.8.1
Checklist:
> chore(argo-cd): Upgrade Argo CD to v2.8.1

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/README.md.gotmpl
> fix(argo-cd): Fix applicationSet HA examples in README.md

- charts/argo-events/Chart.yaml
https://github.com/argoproj/argo-events/releases/tag/v1.8.1
Checklist:
> chore(argo-events): Upgrade argo-events to 1.8.1

- charts/argo-cd/Chart.yaml
> chore(argo-cd): Upgrade Argo CD to v2.8.3

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/templates/server/server-deployment.yaml
- charts/argo-workflows/values.yaml
Resolves https://github.com/argoproj/argo-helm/issues/2281
Checklist:
> feat(argo-workflows): Configure declarative server auth mode

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/crds/argoproj.io_workflowtaskresults.yaml
https://github.com/argoproj/argo-workflows/releases/tag/v3.5.0
Checklist:
> chore(argo-workflows): Upgrade argo-workflows to 3.5.0

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/templates/_helpers.tpl
- charts/argo-workflows/values.yaml
> feat(argo-workflows): Added commonLabels

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/values.yaml
I took over https://github.com/argoproj/argo-helm/pull/2217 .
Checklist:
> chore(argo-workflows): Add sample of PostgreSQL ssl entries in values.yaml

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/templates/controller/deployment.yaml
Fixes: #2308
Cast to int since default from values.yaml is int64 not int
<details><summary>Before</summary>
<p>
```
➜  helm install argo-rollouts . -n argo-rollouts --set controller.replicas=2 --dry-run                                                                                     
Error: INSTALLATION FAILED: template: argo-rollouts/templates/controller/deployment.yaml:51:15: executing "argo-rollouts/templates/controller/deployment.yaml" at <gt .Values.controller.replicas 1.0>: error calling gt: incompatible types for comparison
```
</p>
</details> 
<details><summary>After</summary>
<p>
```
apiVersion: apps/v1
kind: Deployment
metadata:
name: argo-rollouts
namespace: "argo-rollouts"
labels:
app.kubernetes.io/component: rollouts-controller
helm.sh/chart: argo-rollouts-2.32.1 …
```
> fix(argo-rollouts): controller replicas count comparison

- .github/configs/ct-lint.yaml
- charts/argo-cd/Chart.yaml
Checklist:
https://github.com/argoproj/argo-cd/compare/v2.8.5...v2.8.6
> chore(argo-cd): Upgrade Argo CD to v2.8.6

- charts/argo-cd/Chart.yaml
release note: https://github.com/argoproj/argo-cd/releases/tag/v2.9.1
diff: https://github.com/argoproj/argo-cd/compare/v2.9.0...v2.9.1
Checklist:
> chore(argo-cd): Upgrade Argo CD to v2.9.1

- charts/argo-cd/Chart.yaml
release note: https://github.com/argoproj/argo-cd/releases/tag/v2.9.2
diff: https://github.com/argoproj/argo-cd/compare/v2.9.1...v2.9.2
Checklist:
> chore(argo-cd): Upgrade Argo CD to v2.9.2

- SECURITY-INSIGHTS.yml
CLOMonitor claims about:
- Dependencies policy
- Security insights
While here, I updated some other sections.
Spec of this file is here: https://github.com/ossf/security-insights-spec/blob/v1.0.0/specification.md
Checklist:
> chore(github): Update SECURITY-INSIGHTS.yml to include security-contacts

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/README.md.gotmpl
Fixes: https://github.com/argoproj/argo-helm/issues/2359
Checklist:
> docs(argo-cd): Add migration guide to README for Config Management Plugins

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/templates/controller/workflow-controller-config-map.yaml
- charts/argo-workflows/values.yaml
According to https://argoproj.github.io/argo-workflows/argo-server-sso/#filtering-groups
Resolves #2378
Checklist:
> feat(argo-workflows): Add support for sso filterGroupsRegex

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/README.md.gotmpl
related to https://github.com/argoproj/argo-helm/issues/2395 .
Checklist:
> chore(argo-workflows): Add instruction for SSO

- charts/argo-cd/Chart.yaml
- charts/argo-cd/values.yaml
Related to https://github.com/argoproj/argo-helm/issues/2431 .
Checklist:
> docs(argo-cd): Add reference for Argo CD extensions

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-configs/argocd-secret.yaml
- charts/argo-cd/values.yaml
Resolves https://github.com/argoproj/argo-helm/issues/2432 .
Checklist:
> feat(argo-cd): Support Azure DevOps webhook Secret

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
Resolves https://github.com/argoproj/argo-helm/issues/2444 .
Checklist:
> chore(argo-cd): Provide Casbin matcher explicitly

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
Resolves https://github.com/argoproj/argo-helm/issues/2455
Resolves https://github.com/argoproj/argo-helm/issues/2450
Checklist:
> fix(argo-cd): Restart argocd-server when argocd-cm CM is updated

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-notifications/clusterrole.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/templates/crds/crd-project.yaml
> chore(argo-cd): refresh from upstream

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-application-controller/statefulset.yaml
- charts/argo-cd/templates/argocd-applicationset/deployment.yaml
- charts/argo-cd/templates/argocd-notifications/deployment.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/templates/crds/crd-application.yaml
- charts/argo-cd/templates/crds/crd-applicationset.yaml
- charts/argo-cd/templates/crds/crd-project.yaml
> feat(argo-cd): Upgrade Argo CD to 2.10.0

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-applicationset/ingress.yaml
- charts/argo-cd/templates/argocd-server/aws/ingress.yaml
- charts/argo-cd/templates/argocd-server/gke/ingress.yaml
- charts/argo-cd/templates/argocd-server/ingress-grpc.yaml
- charts/argo-cd/templates/argocd-server/ingress.yaml
Resolves: https://github.com/argoproj/argo-helm/issues/2478
Checklist:
> fix(argo-cd): Fix ingress extraHosts

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/README.md.gotmpl
> docs(argo-cd): Document various ingress setups

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-application-controller/statefulset.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/role.yaml
> chore(argo-cd): Remove server.config leftovers

- charts/argo-cd/Chart.yaml
- charts/argo-cd/values.yaml
> chore(argo-cd): update notifications links to latest documentation

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
> chore(argo-cd): Update Redis image to 7.2.4

- .github/workflows/renovate.yaml
- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-configs/argocd-notifications-secret.yaml
- charts/argo-cd/templates/argocd-notifications/clusterrole.yaml
- charts/argo-cd/templates/argocd-notifications/deployment.yaml
- charts/argo-cd/templates/argocd-notifications/role.yaml
- charts/argo-cd/values.yaml
> feat(argo-cd): Support setting ArgoCD Notifications secret

- charts/argo-events/Chart.yaml
- charts/argo-events/README.md
- charts/argo-events/templates/_helpers.tpl
- charts/argo-events/templates/argo-events-controller/config.yaml
- charts/argo-events/templates/argo-events-controller/deployment.yaml
- charts/argo-events/templates/argo-events-controller/pdb.yaml
- charts/argo-events/templates/argo-events-controller/rbac.yaml
- charts/argo-events/templates/argo-events-controller/service.yaml
- charts/argo-events/templates/argo-events-controller/serviceaccount.yaml
- charts/argo-events/templates/argo-events-controller/servicemonitor.yaml
- charts/argo-events/templates/argo-events-webhook/clusterrolebinding.yaml
- charts/argo-events/templates/argo-events-webhook/deployment.yaml
- charts/argo-events/templates/argo-events-webhook/pdb.yaml
- charts/argo-events/templates/argo-events-webhook/service.yaml
- charts/argo-events/templates/argo-events-webhook/serviceaccount.yaml
- charts/argo-events/values.yaml
Resolves https://github.com/argoproj/argo-helm/issues/2593
Checklist:
> feat(argo-events): Support ability to set .Values.namespaceOverride

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/README.md
- charts/argo-rollouts/templates/controller/clusterrole.yaml
- charts/argo-rollouts/templates/controller/role.yaml
- charts/argo-rollouts/values.yaml
> feat(argo-rollouts): add minimum RBAC for Gateway API

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/values.yaml
> fix(argo-workflows): hyphen typo in values.yaml comment

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/README.md
- charts/argo-rollouts/templates/controller/deployment.yaml
- charts/argo-rollouts/templates/dashboard/deployment.yaml
- charts/argo-rollouts/values.yaml
Resolves https://github.com/argoproj/argo-helm/issues/2711
Checklist:
> feat(argo-rollouts): Support revisionHistoryLimit

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-server/certificate.yaml
- charts/argo-cd/values.yaml
> feat(argo-cd): Add secrettemplate to argo-cd server certificate

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/README.md.gotmpl
We get requests to add changelog for argo-cd v7 in [CNCF slack](https://cloud-native.slack.com/archives/C02097VUKUM/p1720193838636139).
Checklist:
> docs(argo-cd): Add Changelog for v7.0.0

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-applicationset/role.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/crds/crd-application.yaml
- charts/argo-cd/templates/crds/crd-applicationset.yaml
- charts/argo-cd/templates/crds/crd-project.yaml
> feat(argo-cd): Upgrade to Argo CD 2.12.0

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-application-controller/deployment.yaml
- charts/argo-cd/templates/argocd-application-controller/statefulset.yaml
- charts/argo-cd/templates/argocd-applicationset/deployment.yaml
- charts/argo-cd/templates/argocd-notifications/deployment.yaml
- charts/argo-cd/templates/argocd-repo-server/deployment.yaml
- charts/argo-cd/templates/argocd-server/deployment.yaml
- charts/argo-cd/templates/dex/deployment.yaml
- charts/argo-cd/templates/redis/deployment.yaml
- charts/argo-cd/values.yaml
> feat(argo-cd): allow setting runtime class name

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/templates/argocd-applicationset/clusterrolebinding.yaml
- charts/argo-cd/values.yaml
Resolves issue in https://github.com/argoproj/argo-helm/pull/2935 .
Checklist:
> fix(argo-cd): Arrange for ApplicationSet in any namespace

- charts/argocd-apps/Chart.yaml
- charts/argocd-apps/ci/applicationsets-values.yaml
- charts/argocd-apps/templates/applicationsets.yaml
- charts/argocd-apps/values.yaml
> feat(argocd-apps): finalizers for applicationset

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/templates/server/server-deployment.yaml
- charts/argo-workflows/values.yaml
Resolves https://github.com/argoproj/argo-helm/issues/2996
Checklist:
> feat(argo-workflows): Support lifecycle and terminationGracePeriodSeconds for server

- SECURITY.md
Checklist:
Small PR - updates security policy for Argo Rollouts
> docs(argo-rollouts): update security policy for Argo Rollouts in SECURITY.md

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/crds/crd-application.yaml
Resolves https://github.com/argoproj/argo-helm/issues/3046
Checklist:
> fix(argo-cd): Update application CRD

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/templates/server/server-deployment.yaml
> fix(argo-workflows): Updated chart to reflect change to ARGO_BASE_HREF env

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/values.yaml
and also trying to automate in #3072
Checklist:
> feat(argo-cd): Bump argocd-extension-installer to 0.0.8

- charts/argo-cd/Chart.yaml
- charts/argo-cd/templates/argocd-server/ingress.yaml
Fixes #3114 
This is a regression of this PR:
- #3081
I tested this manually with this value file:
```yaml
server:
ingress:
enabled: true
annotations:
kubernetes.io/bool: true
kubernetes.io/quoted-bool: "true"
kubernetes.io/tpl: "{{ .Release.Namespace }}"
kubernetes.io/number: 42
```
```bash
$ helm template argocd . --values myvalues.yaml -s templates/argocd-server/ingress.yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
name: argocd-server
namespace: default
labels:
helm.sh/chart: argo-cd-7.7.16
app.kubernetes.io/name: argocd-server
app.kubernetes.io/instance: argocd
app.kubernetes.io/component: server
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/part-of: argocd
app.kubernetes.io/version: "v2.13.3"
annotations:
kubernetes.io/bool: "true"
kubernetes.io/number: …
```
> fix(argo-cd): Address ingress regression of PR #3081

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/README.md.gotmpl
> chore(argo-cd): Fix typo on README

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/README.md
- charts/argo-workflows/values.yaml
Hopefully reduces the confusion raised in https://github.com/argoproj/argo-helm/pull/3192
Checklist:
> fix(argo-workflows): Clarify the purpose of the aggregate roles in the values.yaml

- charts/argo-events/Chart.yaml
- charts/argo-events/README.md
- charts/argo-events/templates/argo-events-controller/deployment.yaml
- charts/argo-events/templates/argo-events-webhook/deployment.yaml
- charts/argo-events/values.yaml
> feat(argo-events): Add revisionhistorylimit webhook controller

- charts/argo-rollouts/Chart.yaml
- charts/argo-rollouts/templates/controller/deployment.yaml
> fix(argo-rollouts): Fix scope and path to CM for checksum calculation

- charts/argo-cd/Chart.yaml
- charts/argo-cd/README.md
- charts/argo-cd/ci/default-values.yaml
- charts/argo-cd/ci/ha-autoscaling-values.yaml
- charts/argo-cd/values.yaml
- renovate.json
Resolves https://github.com/argoproj/argo-helm/issues/3230 
Checklist:
> fix(argo-cd): Correct oliver006/redis_exporter image tag

- charts/argocd-image-updater/Chart.yaml
- charts/argocd-image-updater/README.md
- charts/argocd-image-updater/values.yaml
Also adding verbiage for auth scripts.
Checklist:
> docs(argocd-image-updater): adding examples of using workload identity with Azure Container Registry

- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/values.yaml
> fix(argo-workflows): Fix incorrect values note

- charts/argocd-image-updater/Chart.yaml
- charts/argocd-image-updater/README.md
- charts/argocd-image-updater/ci/priority-class-values.yaml
- charts/argocd-image-updater/templates/deployment.yaml
- charts/argocd-image-updater/values.yaml
Resolves https://github.com/argoproj/argo-helm/issues/3359 
Checklist:
> feat(argocd-image-updater): Support priorityClassName
